/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/smartprops/CSmartPropOperation.hpp"

namespace shade {
    namespace sdk {
        namespace smartprops {
            /* Class Parameters
             * Size: 0xd0
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class CSmartPropOperation_RestoreState : public shade::sdk::smartprops::CSmartPropOperation {
            public:
                CSmartPropAttributeStateName m_StateName; // 0x0050, 0x40 bytes
                CSmartPropAttributeBool m_bDiscardIfUknown; // 0x0090, 0x40 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CSmartPropOperation_RestoreState) == 0xD0, "CSmartPropOperation_RestoreState size mismatch");
        }
    }
}
