/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/smartprops/CSmartPropAttributeDistributionMode.hpp"
#include "shade/sdk/smartprops/CSmartPropAttributeRadiusPlacementMode.hpp"
#include "shade/sdk/smartprops/CSmartPropElement_Group.hpp"

namespace shade {
    namespace sdk {
        namespace smartprops {
            /* Class Parameters
             * Size: 0x320
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class CSmartPropElement_PlaceInSphere : public shade::sdk::smartprops::CSmartPropElement_Group {
            public:
                shade::sdk::smartprops::CSmartPropAttributeRadiusPlacementMode m_PlacementMode; // 0x00a0, 0x40 bytes
                shade::sdk::smartprops::CSmartPropAttributeDistributionMode m_DistributionMode; // 0x00e0, 0x40 bytes
                CSmartPropAttributeFloat m_flRandomness; // 0x0120, 0x40 bytes
                CSmartPropAttributeVector m_vPlaneUpDirection; // 0x0160, 0x40 bytes
                CSmartPropAttributeInt m_nCountMin; // 0x01a0, 0x40 bytes
                CSmartPropAttributeInt m_nCountMax; // 0x01e0, 0x40 bytes
                CSmartPropAttributeFloat m_flPositionRadiusInner; // 0x0220, 0x40 bytes
                CSmartPropAttributeFloat m_flPositionRadiusOuter; // 0x0260, 0x40 bytes
                CSmartPropAttributeBool m_bAlignOrientation; // 0x02a0, 0x40 bytes
                CSmartPropAttributeVector m_vAlignDirection; // 0x02e0, 0x40 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CSmartPropElement_PlaceInSphere) == 0x320, "CSmartPropElement_PlaceInSphere size mismatch");
        }
    }
}
