/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/pulse_runtime_lib/CPulseCell_BaseFlow.hpp"
#include "shade/sdk/pulse_runtime_lib/PulseSelectorOutflowList_t.hpp"
#include "shade/sdk/smartprops/ConfigurationHandleShape_t.hpp"

namespace shade {
    namespace sdk {
        namespace smartprops {
            /* Class Parameters
             * Size: 0x68
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CSmartPropPulse_PickOneSelector : public shade::sdk::pulse_runtime_lib::CPulseCell_BaseFlow {
            public:
                shade::sdk::smartprops::ConfigurationHandleShape_t m_HandleShape; // 0x0048, 0x4 bytes
                std::uint8_t pad_004c[0x4]; // 0x004c, 0x4 bytes
                shade::sdk::pulse_runtime_lib::PulseSelectorOutflowList_t m_OutflowList; // 0x0050, 0x18 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CSmartPropPulse_PickOneSelector) == 0x68, "CSmartPropPulse_PickOneSelector size mismatch");
        }
    }
}
