/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

namespace shade {
    namespace sdk {
        namespace entity2 {
            struct EntComponentInfo_t;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace entity2 {
            /* Class Parameters
             * Size: 0x28
             * Alignment: 0xff
             * Has VTable
             * Abstract Class
             * Has Trivial Destructor
             */
            #pragma pack(push, 1)
            class CEntityComponentHelper {
            public:
                std::uint8_t pad_0000[0x8]; // 0x0000, 0x8 bytes
                std::uint32_t m_flags; // 0x0008, 0x4 bytes
                std::uint8_t pad_000c[0x4]; // 0x000c, 0x4 bytes
                shade::sdk::entity2::EntComponentInfo_t *m_pInfo; // 0x0010, 0x8 bytes
                std::int32_t m_nPriority; // 0x0018, 0x4 bytes
                std::uint8_t pad_001c[0x4]; // 0x001c, 0x4 bytes
                shade::sdk::entity2::CEntityComponentHelper *m_pNext; // 0x0020, 0x8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CEntityComponentHelper) == 0x28, "CEntityComponentHelper size mismatch");
        }
    }
}
