/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/particles/CParticleFunctionPreEmission.hpp"
#include "shade/sdk/particleslib/CParticleCollectionFloatInput.hpp"

namespace shade {
    namespace sdk {
        namespace particles {
            /* Class Parameters
             * Size: 0x370
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class C_OP_SetCPOrientationToPointAtCP : public shade::sdk::particles::CParticleFunctionPreEmission {
            public:
                std::int32_t m_nInputCP; // 0x01e8, 0x4 bytes
                std::int32_t m_nOutputCP; // 0x01ec, 0x4 bytes
                shade::sdk::particleslib::CParticleCollectionFloatInput m_flInterpolation; // 0x01f0, 0x178 bytes
                bool m_b2DOrientation; // 0x0368, 0x1 bytes
                bool m_bAvoidSingularity; // 0x0369, 0x1 bytes
                bool m_bPointAway; // 0x036a, 0x1 bytes
                std::uint8_t pad_036b[0x5]; // 0x036b, 0x5 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_OP_SetCPOrientationToPointAtCP) == 0x370, "C_OP_SetCPOrientationToPointAtCP size mismatch");
        }
    }
}
