/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/particles/CParticleFunctionOperator.hpp"
#include "shade/sdk/particles/ControlPointReference_t.hpp"
#include "shade/sdk/particles/ParticleAttributeIndex_t.hpp"

namespace shade {
    namespace sdk {
        namespace particles {
            /* Class Parameters
             * Size: 0x238
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class C_OP_CalculateVectorAttribute : public shade::sdk::particles::CParticleFunctionOperator {
            public:
                Vector m_vStartValue; // 0x01d8, 0xc bytes
                shade::sdk::particles::ParticleAttributeIndex_t m_nFieldInput1; // 0x01e4, 0x4 bytes
                float m_flInputScale1; // 0x01e8, 0x4 bytes
                shade::sdk::particles::ParticleAttributeIndex_t m_nFieldInput2; // 0x01ec, 0x4 bytes
                float m_flInputScale2; // 0x01f0, 0x4 bytes
                shade::sdk::particles::ControlPointReference_t m_nControlPointInput1; // 0x01f4, 0x14 bytes
                float m_flControlPointScale1; // 0x0208, 0x4 bytes
                shade::sdk::particles::ControlPointReference_t m_nControlPointInput2; // 0x020c, 0x14 bytes
                float m_flControlPointScale2; // 0x0220, 0x4 bytes
                shade::sdk::particles::ParticleAttributeIndex_t m_nFieldOutput; // 0x0224, 0x4 bytes
                Vector m_vFinalOutputScale; // 0x0228, 0xc bytes
                std::uint8_t pad_0234[0x4]; // 0x0234, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_OP_CalculateVectorAttribute) == 0x238, "C_OP_CalculateVectorAttribute size mismatch");
        }
    }
}
