/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/particles/CParticleFunctionOperator.hpp"
#include "shade/sdk/particles/ParticleAttributeIndex_t.hpp"
#include "shade/sdk/particleslib/CParticleTransformInput.hpp"
#include "shade/sdk/particleslib/ParticleSetMethod_t.hpp"

namespace shade {
    namespace sdk {
        namespace particles {
            /* Class Parameters
             * Size: 0x270
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class C_OP_RemapTransformVisibilityToVector : public shade::sdk::particles::CParticleFunctionOperator {
            public:
                shade::sdk::particleslib::ParticleSetMethod_t m_nSetMethod; // 0x01d8, 0x4 bytes
                std::uint8_t pad_01dc[0x4]; // 0x01dc, 0x4 bytes
                shade::sdk::particleslib::CParticleTransformInput m_TransformInput; // 0x01e0, 0x68 bytes
                shade::sdk::particles::ParticleAttributeIndex_t m_nFieldOutput; // 0x0248, 0x4 bytes
                float m_flInputMin; // 0x024c, 0x4 bytes
                float m_flInputMax; // 0x0250, 0x4 bytes
                Vector m_vecOutputMin; // 0x0254, 0xc bytes
                Vector m_vecOutputMax; // 0x0260, 0xc bytes
                float m_flRadius; // 0x026c, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_OP_RemapTransformVisibilityToVector) == 0x270, "C_OP_RemapTransformVisibilityToVector size mismatch");
        }
    }
}
