/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/particles/CParticleFunctionRenderer.hpp"
#include "shade/sdk/particles/ParticleAttributeIndex_t.hpp"
#include "shade/sdk/particles/ParticleColorBlendType_t.hpp"
#include "shade/sdk/particleslib/CParticleCollectionVecInput.hpp"

namespace shade {
    namespace sdk {
        namespace resourcesystem {
            class InfoForResourceTypeCTextureBase;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace particles {
            /* Class Parameters
             * Size: 0x920
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class C_OP_RenderDeferredLight : public shade::sdk::particles::CParticleFunctionRenderer {
            public:
                bool m_bUseAlphaTestWindow; // 0x0228, 0x1 bytes
                bool m_bUseTexture; // 0x0229, 0x1 bytes
                std::uint8_t pad_022a[0x2]; // 0x022a, 0x2 bytes
                float m_flRadiusScale; // 0x022c, 0x4 bytes
                float m_flAlphaScale; // 0x0230, 0x4 bytes
                shade::sdk::particles::ParticleAttributeIndex_t m_nAlpha2Field; // 0x0234, 0x4 bytes
                shade::sdk::particleslib::CParticleCollectionVecInput m_vecColorScale; // 0x0238, 0x6b8 bytes
                shade::sdk::particles::ParticleColorBlendType_t m_nColorBlendType; // 0x08f0, 0x4 bytes
                float m_flLightDistance; // 0x08f4, 0x4 bytes
                float m_flStartFalloff; // 0x08f8, 0x4 bytes
                float m_flDistanceFalloff; // 0x08fc, 0x4 bytes
                float m_flSpotFoV; // 0x0900, 0x4 bytes
                shade::sdk::particles::ParticleAttributeIndex_t m_nAlphaTestPointField; // 0x0904, 0x4 bytes
                shade::sdk::particles::ParticleAttributeIndex_t m_nAlphaTestRangeField; // 0x0908, 0x4 bytes
                shade::sdk::particles::ParticleAttributeIndex_t m_nAlphaTestSharpnessField; // 0x090c, 0x4 bytes
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeCTextureBase> m_hTexture; // 0x0910, 0x8 bytes
                std::int32_t m_nHSVShiftControlPoint; // 0x0918, 0x4 bytes
                std::uint8_t pad_091c[0x4]; // 0x091c, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_OP_RenderDeferredLight) == 0x920, "C_OP_RenderDeferredLight size mismatch");
        }
    }
}
