/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/particles/CParticleFunctionPreEmission.hpp"
#include "shade/sdk/particleslib/CParticleCollectionVecInput.hpp"

namespace shade {
    namespace sdk {
        namespace particles {
            /* Class Parameters
             * Size: 0x8a8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class C_OP_RemapExternalWindToCP : public shade::sdk::particles::CParticleFunctionPreEmission {
            public:
                std::int32_t m_nCP; // 0x01e0, 0x4 bytes
                std::int32_t m_nCPOutput; // 0x01e4, 0x4 bytes
                shade::sdk::particleslib::CParticleCollectionVecInput m_vecScale; // 0x01e8, 0x6b8 bytes
                bool m_bSetMagnitude; // 0x08a0, 0x1 bytes
                std::uint8_t pad_08a1[0x3]; // 0x08a1, 0x3 bytes
                std::int32_t m_nOutVectorField; // 0x08a4, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_OP_RemapExternalWindToCP) == 0x8A8, "C_OP_RemapExternalWindToCP size mismatch");
        }
    }
}
