/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

namespace shade {
    namespace sdk {
        namespace particles {
            /* Class Parameters
             * Size: 0x14
             * Alignment: 0x4
             * Has Trivial Destructor
             * Construct Allowed
             */
            #pragma pack(push, 1)
            struct ControlPointReference_t {
                std::int32_t m_controlPointNameString; // 0x0000, 0x4 bytes
                Vector m_vOffsetFromControlPoint; // 0x0004, 0xc bytes
                bool m_bOffsetInLocalSpace; // 0x0010, 0x1 bytes
                std::uint8_t pad_0011[0x3]; // 0x0011, 0x3 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(ControlPointReference_t) == 0x14, "ControlPointReference_t size mismatch");
        }
    }
}
