/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CitadelAbilityVData.hpp"

namespace shade {
    namespace sdk {
        namespace resourcesystem {
            class InfoForResourceTypeIParticleSystemDefinition;
        }

        namespace server {
            class CCitadelModifier;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1c08
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CAbilityImmobilizeTrapVData : public shade::sdk::server::CitadelAbilityVData {
            public:
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_ExplodeParticle; // 0x1818, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_PreviewRingParticle; // 0x18f8, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_TrapHighlightParticle; // 0x19d8, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_ArmedParticle; // 0x1ab8, 0xe0 bytes
                CSoundEventName m_strTripSound; // 0x1b98, 0x10 bytes
                CSoundEventName m_strExplodeSound; // 0x1ba8, 0x10 bytes
                CSoundEventName m_strExpiredSound; // 0x1bb8, 0x10 bytes
                CSoundEventName m_strImmobilizeTargetSound; // 0x1bc8, 0x10 bytes
                CSoundEventName m_strArmingSound; // 0x1bd8, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_GlitchModifier; // 0x1be8, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_DebuffModifier; // 0x1bf8, 0x10 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CAbilityImmobilizeTrapVData) == 0x1C08, "CAbilityImmobilizeTrapVData size mismatch");
        }
    }
}
