/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CitadelCameraOperationsSequence_t.hpp"
#include "shade/sdk/server/CitadelAbilityVData.hpp"

namespace shade {
    namespace sdk {
        namespace resourcesystem {
            class InfoForResourceTypeIParticleSystemDefinition;
        }

        namespace server {
            class CCitadelModifier;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1ac0
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CAbility_Drifter_ShadowMark_VData : public shade::sdk::server::CitadelAbilityVData {
            public:
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_ImpactParticle; // 0x1818, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_TeleportTrailParticle; // 0x18f8, 0xe0 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_TargetModifier; // 0x19d8, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_TargetTeleportModifier; // 0x19e8, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_BuffModifier; // 0x19f8, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_PostTeleportModifier; // 0x1a08, 0x10 bytes
                CSoundEventName m_strHitHeroSound; // 0x1a18, 0x10 bytes
                CSoundEventName m_strHitNPCSound; // 0x1a28, 0x10 bytes
                shade::sdk::client::CitadelCameraOperationsSequence_t m_cameraSequenceTeleport; // 0x1a38, 0x88 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CAbility_Drifter_ShadowMark_VData) == 0x1AC0, "CAbility_Drifter_ShadowMark_VData size mismatch");
        }
    }
}
