/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CitadelAbilityVData.hpp"

namespace shade {
    namespace sdk {
        namespace resourcesystem {
            class InfoForResourceTypeIParticleSystemDefinition;
        }

        namespace server {
            class CCitadelModifier;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1670
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CAbility_Werewolf_FrenzyVData : public shade::sdk::server::CitadelAbilityVData {
            public:
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_TargetModifier; // 0x13a0, 0x10 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_AreaParticle; // 0x13b0, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_ChargeParticle; // 0x1490, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_TargetDamageParticle; // 0x1570, 0xe0 bytes
                CSoundEventName m_strHitConfirmSound; // 0x1650, 0x10 bytes
                CSoundEventName m_strPointBlankSweetenerSound; // 0x1660, 0x10 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CAbility_Werewolf_FrenzyVData) == 0x1670, "CAbility_Werewolf_FrenzyVData size mismatch");
        }
    }
}
