/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CCitadelBaseAbility.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CBaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x11a0
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CAbility_Drifter_ShadowMark : public shade::sdk::server::CCitadelBaseAbility {
            public:
                Vector m_vLastValidTeleportPosition; // 0x0f70, 0xc bytes
                CHandle<shade::sdk::server::CBaseEntity> m_hTeleportTarget; // 0x0f7c, 0x4 bytes
                bool m_bTeleported; // 0x0f80, 0x1 bytes
                std::uint8_t pad_0f81[0x3]; // 0x0f81, 0x3 bytes
                QAngle m_qPostTeleportAngles; // 0x0f84, 0xc bytes
                std::uint8_t pad_0f90[0x4]; // 0x0f90, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flExpireTime; // 0x0f94, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flTeleportedTime; // 0x0f98, 0x4 bytes
                std::uint8_t pad_0f9c[0x204]; // 0x0f9c, 0x204 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void; // Offset: 0x0, Size: 0x0, Size In Bytes: 0x0
             */

            static_assert(sizeof(CAbility_Drifter_ShadowMark) == 0x11A0, "CAbility_Drifter_ShadowMark size mismatch");
        }
    }
}
