/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CitadelAbilityVData.hpp"

namespace shade {
    namespace sdk {
        namespace resourcesystem {
            class InfoForResourceTypeIParticleSystemDefinition;
        }

        namespace server {
            class CCitadelModifier;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1ad0
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CAbilityPunkgoatUltVData : public shade::sdk::server::CitadelAbilityVData {
            public:
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_DiminishingSlowModifier; // 0x1818, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_FireRateModifier; // 0x1828, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_VulnerableModifier; // 0x1838, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_GroundAuraModifier; // 0x1848, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_PullToGroundModifier; // 0x1858, 0x10 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_BatChargingEffect; // 0x1868, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_GroundParticle; // 0x1948, 0xe0 bytes
                CSoundEventName m_strHangSound; // 0x1a28, 0x10 bytes
                CSoundEventName m_strDiveSound; // 0x1a38, 0x10 bytes
                CPiecewiseCurve m_TimeToReachGroundByHeight; // 0x1a48, 0x40 bytes
                CPiecewiseCurve m_GoUpSpeedCurve; // 0x1a88, 0x40 bytes
                float m_flGoUpDuration; // 0x1ac8, 0x4 bytes
                float m_flGoDownVelocityDampRate; // 0x1acc, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CAbilityPunkgoatUltVData) == 0x1AD0, "CAbilityPunkgoatUltVData size mismatch");
        }
    }
}
