/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CitadelAbilityVData.hpp"

namespace shade {
    namespace sdk {
        namespace resourcesystem {
            class InfoForResourceTypeIParticleSystemDefinition;
        }

        namespace server {
            class CCitadelModifier;
            class CCitadel_Modifier_LurkersAmbush_Invis;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1938
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CAbility_Fathom_LurkersAmbush_VData : public shade::sdk::server::CitadelAbilityVData {
            public:
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_ChargeUpParticle; // 0x1818, 0xe0 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadel_Modifier_LurkersAmbush_Invis> m_InvisModifier; // 0x18f8, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_RegenModifier; // 0x1908, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_DebuffModifier; // 0x1918, 0x10 bytes
                CSoundEventName m_strSwapStarted; // 0x1928, 0x10 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CAbility_Fathom_LurkersAmbush_VData) == 0x1938, "CAbility_Fathom_LurkersAmbush_VData size mismatch");
        }
    }
}
