/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CAI_PathfindFinderData_t.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x10
             * Alignment: 0x8
             * Has VTable
             * Has Trivial Destructor
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class CAI_Pathfinder {
            public:
                std::uint8_t pad_0000[0x8]; // 0x0000, 0x8 bytes
                float m_flPathMaxDetour; // 0x0008, 0x4 bytes
                shade::sdk::server::CAI_PathfindFinderData_t m_FinderData; // 0x000c, 0x1 bytes
                std::uint8_t pad_000d[0x3]; // 0x000d, 0x3 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CAI_Pathfinder) == 0x10, "CAI_Pathfinder size mismatch");
        }
    }
}
