/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CAI_Component.hpp"
#include "shade/sdk/server/AIScheduleState_t.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0xb0
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CAI_Scheduler : public shade::sdk::client::CAI_Component {
            public:
                shade::sdk::server::AIScheduleState_t m_ScheduleState; // 0x0050, 0x14 bytes
                std::uint8_t pad_0064[0xc]; // 0x0064, 0xc bytes
                CUtlSymbolLarge m_failSchedule; // 0x0070, 0x8 bytes
                CUtlSymbolLarge m_translatedSchedule; // 0x0078, 0x8 bytes
                CUtlSymbolLarge m_untranslatedSchedule; // 0x0080, 0x8 bytes
                std::uint8_t pad_0088[0x20]; // 0x0088, 0x20 bytes
                CUtlString m_sInterruptText; // 0x00a8, 0x8 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void m_pSchedule; // Offset: 0x68, Size: 0x1, Size In Bytes: 0x0
             * void m_pFailedSchedule; // Offset: 0x88, Size: 0x1, Size In Bytes: 0x0
             * void m_pInterruptedSchedule; // Offset: 0xa0, Size: 0x1, Size In Bytes: 0x0
             */

            static_assert(sizeof(CAI_Scheduler) == 0xB0, "CAI_Scheduler size mismatch");
        }
    }
}
