/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CNetworkViewOffsetVector.hpp"
#include "shade/sdk/client/HitGroup_t.hpp"
#include "shade/sdk/client/RenderFx_t.hpp"
#include "shade/sdk/client/RenderMode_t.hpp"
#include "shade/sdk/entity2/CEntityIOOutput.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CBaseEntity.hpp"
#include "shade/sdk/server/CCollisionProperty.hpp"
#include "shade/sdk/server/CGlowProperty.hpp"
#include "shade/sdk/server/CHitboxComponent.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            struct CBaseModelEntity__OnDamageLevelChangedArgs_t;
            class CChoreoComponent;
            class CDestructiblePartsComponent;
            class CRenderComponent;
            struct EntityRenderAttribute_t;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x778
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CBaseModelEntity : public shade::sdk::server::CBaseEntity {
            public:
                shade::sdk::server::CRenderComponent *m_CRenderComponent; // 0x0498, 0x8 bytes
                shade::sdk::server::CHitboxComponent m_CHitboxComponent; // 0x04a0, 0x18 bytes
                shade::sdk::server::CChoreoComponent *m_pChoreoComponent; // 0x04b8, 0x8 bytes
                shade::sdk::client::HitGroup_t m_nDestructiblePartInitialStateDestructed0; // 0x04c0, 0x4 bytes
                shade::sdk::client::HitGroup_t m_nDestructiblePartInitialStateDestructed1; // 0x04c4, 0x4 bytes
                shade::sdk::client::HitGroup_t m_nDestructiblePartInitialStateDestructed2; // 0x04c8, 0x4 bytes
                shade::sdk::client::HitGroup_t m_nDestructiblePartInitialStateDestructed3; // 0x04cc, 0x4 bytes
                shade::sdk::client::HitGroup_t m_nDestructiblePartInitialStateDestructed4; // 0x04d0, 0x4 bytes
                std::int32_t m_nDestructiblePartInitialStateDestructed0_PartIndex; // 0x04d4, 0x4 bytes
                std::int32_t m_nDestructiblePartInitialStateDestructed1_PartIndex; // 0x04d8, 0x4 bytes
                std::int32_t m_nDestructiblePartInitialStateDestructed2_PartIndex; // 0x04dc, 0x4 bytes
                std::int32_t m_nDestructiblePartInitialStateDestructed3_PartIndex; // 0x04e0, 0x4 bytes
                std::int32_t m_nDestructiblePartInitialStateDestructed4_PartIndex; // 0x04e4, 0x4 bytes
                bool m_bDestructiblePartInitialStateDestructed0_GenerateBreakpieces; // 0x04e8, 0x1 bytes
                bool m_bDestructiblePartInitialStateDestructed1_GenerateBreakpieces; // 0x04e9, 0x1 bytes
                bool m_bDestructiblePartInitialStateDestructed2_GenerateBreakpieces; // 0x04ea, 0x1 bytes
                bool m_bDestructiblePartInitialStateDestructed3_GenerateBreakpieces; // 0x04eb, 0x1 bytes
                bool m_bDestructiblePartInitialStateDestructed4_GenerateBreakpieces; // 0x04ec, 0x1 bytes
                std::uint8_t pad_04ed[0x3]; // 0x04ed, 0x3 bytes
                shade::sdk::server::CDestructiblePartsComponent *m_pDestructiblePartsSystemComponent; // 0x04f0, 0x8 bytes
                CEntityOutputTemplate<shade::sdk::server::CBaseModelEntity__OnDamageLevelChangedArgs_t> m_OnDestructibleHitGroupDamageLevelChanged; // 0x04f8, 0x28 bytes
                shade::sdk::entity2::GameTime_t m_flDissolveStartTime; // 0x0520, 0x4 bytes
                std::uint8_t pad_0524[0x4]; // 0x0524, 0x4 bytes
                shade::sdk::entity2::CEntityIOOutput m_OnIgnite; // 0x0528, 0x18 bytes
                std::int32_t m_iViewerID; // 0x0540, 0x4 bytes
                std::int32_t m_iTeamVisibilityBitmask; // 0x0544, 0x4 bytes
                shade::sdk::client::RenderMode_t m_nRenderMode; // 0x0548, 0x1 bytes
                bool m_bVisibilityDirtyFlag; // 0x0549, 0x1 bytes
                std::int16_t m_iFOWTempViewerID[0xa]; // 0x054a, 0x14 bytes
                shade::sdk::client::RenderFx_t m_nRenderFX; // 0x055e, 0x1 bytes
                bool m_bAllowFadeInView; // 0x055f, 0x1 bytes
                std::uint8_t pad_0560[0x18]; // 0x0560, 0x18 bytes
                Color m_clrRender; // 0x0578, 0x4 bytes
                std::uint8_t pad_057c[0x4]; // 0x057c, 0x4 bytes
                CUtlVectorEmbeddedNetworkVar<shade::sdk::server::EntityRenderAttribute_t> m_vecRenderAttributes; // 0x0580, 0x68 bytes
                bool m_bRenderToCubemaps; // 0x05e8, 0x1 bytes
                bool m_bNoInterpolate; // 0x05e9, 0x1 bytes
                std::uint8_t pad_05ea[0x6]; // 0x05ea, 0x6 bytes
                shade::sdk::server::CCollisionProperty m_Collision; // 0x05f0, 0xb8 bytes
                shade::sdk::server::CGlowProperty m_Glow; // 0x06a8, 0x58 bytes
                float m_flGlowBackfaceMult; // 0x0700, 0x4 bytes
                float m_fadeMinDist; // 0x0704, 0x4 bytes
                float m_fadeMaxDist; // 0x0708, 0x4 bytes
                float m_flFadeScale; // 0x070c, 0x4 bytes
                float m_flShadowStrength; // 0x0710, 0x4 bytes
                std::uint8_t m_nObjectCulling; // 0x0714, 0x1 bytes
                std::uint8_t pad_0715[0x3]; // 0x0715, 0x3 bytes
                CUtlOrderedMap<CGlobalSymbol, std::int32_t> m_bodyGroupChoices; // 0x0718, 0x28 bytes
                shade::sdk::client::CNetworkViewOffsetVector m_vecViewOffset; // 0x0740, 0x28 bytes
                std::uint8_t pad_0768[0x8]; // 0x0768, 0x8 bytes
                std::uint32_t m_bvDisabledHitGroups[0x1]; // 0x0770, 0x4 bytes
                std::uint8_t pad_0774[0x4]; // 0x0774, 0x4 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * CUtlString add_attribute; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             * Color rendercolor32; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             * std::int32_t renderamt; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             * Vector mins; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             * Vector maxs; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             * char *skin; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             * CUtlString bodygroups; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             */

            static_assert(sizeof(CBaseModelEntity) == 0x778, "CBaseModelEntity size mismatch");
        }
    }
}
