/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CNetworkViewOffsetVector.hpp"
#include "shade/sdk/client/HitGroup_t.hpp"
#include "shade/sdk/client/RenderFx_t.hpp"
#include "shade/sdk/client/RenderMode_t.hpp"
#include "shade/sdk/entity2/CEntityIOOutput.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CBaseEntity.hpp"
#include "shade/sdk/server/CCollisionProperty.hpp"
#include "shade/sdk/server/CGlowProperty.hpp"
#include "shade/sdk/server/CHitboxComponent.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            struct CBaseModelEntity__BodyGroupRequest_t;
            struct CBaseModelEntity__OnDamageLevelChangedArgs_t;
            class CChoreoComponent;
            class CDestructiblePartsComponent;
            class CRenderComponent;
            struct EntityRenderAttribute_t;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x878
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CBaseModelEntity : public shade::sdk::server::CBaseEntity {
            public:
                shade::sdk::server::CRenderComponent *m_CRenderComponent; // 0x04b0, 0x8 bytes
                shade::sdk::server::CHitboxComponent m_CHitboxComponent; // 0x04b8, 0x18 bytes
                shade::sdk::server::CChoreoComponent *m_pChoreoComponent; // 0x04d0, 0x8 bytes
                shade::sdk::client::HitGroup_t m_nDestructiblePartInitialStateDestructed0; // 0x04d8, 0x4 bytes
                shade::sdk::client::HitGroup_t m_nDestructiblePartInitialStateDestructed1; // 0x04dc, 0x4 bytes
                shade::sdk::client::HitGroup_t m_nDestructiblePartInitialStateDestructed2; // 0x04e0, 0x4 bytes
                shade::sdk::client::HitGroup_t m_nDestructiblePartInitialStateDestructed3; // 0x04e4, 0x4 bytes
                shade::sdk::client::HitGroup_t m_nDestructiblePartInitialStateDestructed4; // 0x04e8, 0x4 bytes
                std::int32_t m_nDestructiblePartInitialStateDestructed0_PartIndex; // 0x04ec, 0x4 bytes
                std::int32_t m_nDestructiblePartInitialStateDestructed1_PartIndex; // 0x04f0, 0x4 bytes
                std::int32_t m_nDestructiblePartInitialStateDestructed2_PartIndex; // 0x04f4, 0x4 bytes
                std::int32_t m_nDestructiblePartInitialStateDestructed3_PartIndex; // 0x04f8, 0x4 bytes
                std::int32_t m_nDestructiblePartInitialStateDestructed4_PartIndex; // 0x04fc, 0x4 bytes
                bool m_bDestructiblePartInitialStateDestructed0_GenerateBreakpieces; // 0x0500, 0x1 bytes
                bool m_bDestructiblePartInitialStateDestructed1_GenerateBreakpieces; // 0x0501, 0x1 bytes
                bool m_bDestructiblePartInitialStateDestructed2_GenerateBreakpieces; // 0x0502, 0x1 bytes
                bool m_bDestructiblePartInitialStateDestructed3_GenerateBreakpieces; // 0x0503, 0x1 bytes
                bool m_bDestructiblePartInitialStateDestructed4_GenerateBreakpieces; // 0x0504, 0x1 bytes
                std::uint8_t pad_0505[0x3]; // 0x0505, 0x3 bytes
                shade::sdk::server::CDestructiblePartsComponent *m_pDestructiblePartsSystemComponent; // 0x0508, 0x8 bytes
                CEntityOutputTemplate<shade::sdk::server::CBaseModelEntity__OnDamageLevelChangedArgs_t> m_OnDestructibleHitGroupDamageLevelChanged; // 0x0510, 0x28 bytes
                shade::sdk::entity2::GameTime_t m_flDissolveStartTime; // 0x0538, 0x4 bytes
                std::uint8_t pad_053c[0x4]; // 0x053c, 0x4 bytes
                shade::sdk::entity2::CEntityIOOutput m_OnIgnite; // 0x0540, 0x18 bytes
                shade::sdk::client::RenderMode_t m_nRenderMode; // 0x0558, 0x1 bytes
                shade::sdk::client::RenderFx_t m_nRenderFX; // 0x0559, 0x1 bytes
                std::uint8_t pad_055a[0x6]; // 0x055a, 0x6 bytes
                CUtlString m_szAddModifier; // 0x0560, 0x8 bytes
                bool m_bAllowFadeInView; // 0x0568, 0x1 bytes
                std::uint8_t pad_0569[0x1f]; // 0x0569, 0x1f bytes
                bool m_bHasCollision; // 0x0588, 0x1 bytes
                std::uint8_t pad_0589[0x3]; // 0x0589, 0x3 bytes
                VectorWS m_vSupport; // 0x058c, 0xc bytes
                Color m_clrRender; // 0x0598, 0x4 bytes
                std::uint8_t pad_059c[0x4]; // 0x059c, 0x4 bytes
                CUtlVectorEmbeddedNetworkVar<shade::sdk::server::EntityRenderAttribute_t> m_vecRenderAttributes; // 0x05a0, 0x68 bytes
                bool m_bRenderToCubemaps; // 0x0608, 0x1 bytes
                bool m_bExpandRenderBoundsToIncludeCloth; // 0x0609, 0x1 bytes
                bool m_bNoInterpolate; // 0x060a, 0x1 bytes
                std::uint8_t pad_060b[0x5]; // 0x060b, 0x5 bytes
                shade::sdk::server::CCollisionProperty m_Collision; // 0x0610, 0xb8 bytes
                shade::sdk::server::CGlowProperty m_Glow; // 0x06c8, 0x58 bytes
                float m_flGlowBackfaceMult; // 0x0720, 0x4 bytes
                float m_fadeMinDist; // 0x0724, 0x4 bytes
                float m_fadeMaxDist; // 0x0728, 0x4 bytes
                float m_flFadeScale; // 0x072c, 0x4 bytes
                float m_flShadowStrength; // 0x0730, 0x4 bytes
                std::uint8_t m_nObjectCulling; // 0x0734, 0x1 bytes
                std::uint8_t pad_0735[0x3]; // 0x0735, 0x3 bytes
                std::uint32_t m_bodyGroupTotalRequestCount; // 0x0738, 0x4 bytes
                std::uint8_t pad_073c[0x4]; // 0x073c, 0x4 bytes
                CUtlVectorFixedGrowable<shade::sdk::server::CBaseModelEntity__BodyGroupRequest_t, 8> m_bodyGroupRequests; // 0x0740, 0xd8 bytes
                CUtlOrderedMap<CGlobalSymbol, std::int32_t> m_bodyGroupChoices; // 0x0818, 0x28 bytes
                shade::sdk::client::CNetworkViewOffsetVector m_vecViewOffset; // 0x0840, 0x28 bytes
                std::uint8_t pad_0868[0x8]; // 0x0868, 0x8 bytes
                std::uint32_t m_bvDisabledHitGroups[0x1]; // 0x0870, 0x4 bytes
                std::uint8_t pad_0874[0x4]; // 0x0874, 0x4 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * CUtlString add_attribute; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             * Color rendercolor32; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             * std::int32_t renderamt; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             * Vector mins; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             * Vector maxs; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             * CUtlString skin; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             * CUtlString bodygroups; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             */

            static_assert(sizeof(CBaseModelEntity) == 0x878, "CBaseModelEntity size mismatch");
        }
    }
}
