/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CBaseModelEntity.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x9d8
             * Alignment: 0xff
             * Has VTable
             * Construct Disallowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CBaseClientUIEntity : public shade::sdk::server::CBaseModelEntity {
            public:
                bool m_bEnabled; // 0x0878, 0x1 bytes
                std::uint8_t pad_0879[0x7]; // 0x0879, 0x7 bytes
                CUtlSymbolLarge m_DialogXMLName; // 0x0880, 0x8 bytes
                CUtlSymbolLarge m_PanelClassName; // 0x0888, 0x8 bytes
                CUtlSymbolLarge m_PanelID; // 0x0890, 0x8 bytes
                CEntityOutputTemplate<CUtlString> m_CustomOutput0; // 0x0898, 0x20 bytes
                CEntityOutputTemplate<CUtlString> m_CustomOutput1; // 0x08b8, 0x20 bytes
                CEntityOutputTemplate<CUtlString> m_CustomOutput2; // 0x08d8, 0x20 bytes
                CEntityOutputTemplate<CUtlString> m_CustomOutput3; // 0x08f8, 0x20 bytes
                CEntityOutputTemplate<CUtlString> m_CustomOutput4; // 0x0918, 0x20 bytes
                CEntityOutputTemplate<CUtlString> m_CustomOutput5; // 0x0938, 0x20 bytes
                CEntityOutputTemplate<CUtlString> m_CustomOutput6; // 0x0958, 0x20 bytes
                CEntityOutputTemplate<CUtlString> m_CustomOutput7; // 0x0978, 0x20 bytes
                CEntityOutputTemplate<CUtlString> m_CustomOutput8; // 0x0998, 0x20 bytes
                CEntityOutputTemplate<CUtlString> m_CustomOutput9; // 0x09b8, 0x20 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CBaseClientUIEntity) == 0x9D8, "CBaseClientUIEntity size mismatch");
        }
    }
}
