/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/CEntityComponent.hpp"
#include "shade/sdk/entity2/CNetworkVarChainer.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CGameSceneNode;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x78
             * Alignment: 0xff
             * Has VTable
             * Construct Allowed
             * Construct Disallowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CBodyComponent : public shade::sdk::entity2::CEntityComponent {
            public:
                shade::sdk::server::CGameSceneNode *m_pSceneNode; // 0x0008, 0x8 bytes
                std::uint8_t pad_0010[0x38]; // 0x0010, 0x38 bytes
                shade::sdk::entity2::CNetworkVarChainer __m_pChainEntity; // 0x0048, 0x28 bytes
                std::uint8_t pad_0070[0x8]; // 0x0070, 0x8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CBodyComponent) == 0x78, "CBodyComponent size mismatch");
        }
    }
}
