/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CBaseAnimGraphController.hpp"
#include "shade/sdk/server/CBodyComponentSkeletonInstance.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0xb30
             * Alignment: 0xff
             * Has VTable
             * Construct Allowed
             * Construct Disallowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CBodyComponentBaseAnimGraph : public shade::sdk::server::CBodyComponentSkeletonInstance {
            public:
                shade::sdk::server::CBaseAnimGraphController m_animationController; // 0x04e0, 0x650 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CBodyComponentBaseAnimGraph) == 0xB30, "CBodyComponentBaseAnimGraph size mismatch");
        }
    }
}
