/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CCitadelMinimapComponent.hpp"
#include "shade/sdk/server/CTriggerModifier.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0xa38
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadelIdolReturnTrigger : public shade::sdk::server::CTriggerModifier {
            public:
                std::uint8_t pad_0a00[0x10]; // 0x0a00, 0x10 bytes
                shade::sdk::server::CCitadelMinimapComponent m_CCitadelMinimapComponent; // 0x0a10, 0x20 bytes
                std::uint8_t pad_0a30[0x8]; // 0x0a30, 0x8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadelIdolReturnTrigger) == 0xA38, "CCitadelIdolReturnTrigger size mismatch");
        }
    }
}
