/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CCitadel_Neutral_Attack_BulletToPointModifierVData.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1400
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Neutral_Attack_LobSporesVData : public shade::sdk::server::CCitadel_Neutral_Attack_BulletToPointModifierVData {
            public:
                float m_flCenterShotRadius; // 0x13f0, 0x4 bytes
                float m_flMinRadius; // 0x13f4, 0x4 bytes
                float m_flMaxRadius; // 0x13f8, 0x4 bytes
                std::uint8_t pad_13fc[0x4]; // 0x13fc, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Neutral_Attack_LobSporesVData) == 0x1400, "CCitadel_Neutral_Attack_LobSporesVData size mismatch");
        }
    }
}
