/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CCitadelModifier.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x168
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Modifier_DPSTracker : public shade::sdk::server::CCitadelModifier {
            public:
                std::uint8_t pad_0140[0x18]; // 0x0140, 0x18 bytes
                float m_flInterval; // 0x0158, 0x4 bytes
                float m_flProgress; // 0x015c, 0x4 bytes
                float m_flDistToTarget; // 0x0160, 0x4 bytes
                std::uint8_t pad_0164[0x4]; // 0x0164, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Modifier_DPSTracker) == 0x168, "CCitadel_Modifier_DPSTracker size mismatch");
        }
    }
}
