/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CBaseModelEntity.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CBaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x970
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadelZipLineNode : public shade::sdk::server::CBaseModelEntity {
            public:
                std::uint8_t pad_0878[0x38]; // 0x0878, 0x38 bytes
                CNetworkUtlVectorBase<CHandle<shade::sdk::server::CCitadelZipLineNode>> m_vecConnections; // 0x08b0, 0x18 bytes
                CNetworkUtlVectorBase<std::int32_t> m_vecConnectionDir; // 0x08c8, 0x18 bytes
                Vector m_vTangentIn; // 0x08e0, 0xc bytes
                Vector m_vTangentOut; // 0x08ec, 0xc bytes
                float m_flCumulativeDistance; // 0x08f8, 0x4 bytes
                std::uint8_t pad_08fc[0x24]; // 0x08fc, 0x24 bytes
                CUtlSymbolLarge m_strGuardBossName; // 0x0920, 0x8 bytes
                CUtlSymbolLarge m_strGuardBossName2; // 0x0928, 0x8 bytes
                CUtlSymbolLarge m_strGuardBossName3; // 0x0930, 0x8 bytes
                std::uint8_t pad_0938[0x4]; // 0x0938, 0x4 bytes
                std::int16_t m_iNodeIndex; // 0x093c, 0x2 bytes
                std::int16_t m_eCaptureState; // 0x093e, 0x2 bytes
                std::int16_t m_iPrimaryLane; // 0x0940, 0x2 bytes
                std::int16_t m_nRopesParity; // 0x0942, 0x2 bytes
                bool m_bCornerNode; // 0x0944, 0x1 bytes
                bool m_bCapturable; // 0x0945, 0x1 bytes
                bool m_bDisableZippingToByPlayers; // 0x0946, 0x1 bytes
                std::uint8_t pad_0947[0x1]; // 0x0947, 0x1 bytes
                float m_flSpeedMultiplierToBaseBonus; // 0x0948, 0x4 bytes
                float m_flSpeedMultiplierFromBaseBonus; // 0x094c, 0x4 bytes
                CNetworkUtlVectorBase<CHandle<shade::sdk::server::CBaseEntity>> m_hGuardingBosses; // 0x0950, 0x18 bytes
                float m_flRopeRadius; // 0x0968, 0x4 bytes
                std::uint8_t pad_096c[0x4]; // 0x096c, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadelZipLineNode) == 0x970, "CCitadelZipLineNode size mismatch");
        }
    }
}
