/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CCitadelModifier.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CBaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x4f0
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Modifier_Gravity_Lasso_Self : public shade::sdk::server::CCitadelModifier {
            public:
                bool m_bHasUsedBouncePad; // 0x00d0, 0x1 bytes
                std::uint8_t pad_00d1[0x7]; // 0x00d1, 0x7 bytes
                CUtlVector<CHandle<shade::sdk::server::CBaseEntity>> m_vCastTargets; // 0x00d8, 0x18 bytes
                std::uint8_t pad_00f0[0x400]; // 0x00f0, 0x400 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Modifier_Gravity_Lasso_Self) == 0x4F0, "CCitadel_Modifier_Gravity_Lasso_Self size mismatch");
        }
    }
}
