/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/ParticleIndex_t.hpp"
#include "shade/sdk/server/CCitadelProjectile.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0xdd0
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Projectile_WebWall : public shade::sdk::server::CCitadelProjectile {
            public:
                bool bHasDetonatedOnTarget; // 0x0968, 0x1 bytes
                std::uint8_t pad_0969[0x3]; // 0x0969, 0x3 bytes
                shade::sdk::client::ParticleIndex_t m_nWebWallFxIndex; // 0x096c, 0x4 bytes
                std::uint8_t pad_0970[0x10]; // 0x0970, 0x10 bytes
                VectorWS m_vecCastPosition; // 0x0980, 0xc bytes
                Vector m_vecCastPositionNormal; // 0x098c, 0xc bytes
                VectorWS m_vecEndPosition; // 0x0998, 0xc bytes
                Vector m_vecEndPositionNormal; // 0x09a4, 0xc bytes
                std::uint8_t pad_09b0[0x420]; // 0x09b0, 0x420 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Projectile_WebWall) == 0xDD0, "CCitadel_Projectile_WebWall size mismatch");
        }
    }
}
