/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CCitadelAutoScaledTime.hpp"
#include "shade/sdk/server/CCitadelBaseAbility.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1998
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Ability_FireBomb : public shade::sdk::server::CCitadelBaseAbility {
            public:
                std::uint8_t pad_14a0[0x4d8]; // 0x14a0, 0x4d8 bytes
                shade::sdk::server::CCitadelAutoScaledTime m_flDetonateTime; // 0x1978, 0x18 bytes
                shade::sdk::entity2::GameTime_t m_flStartTime; // 0x1990, 0x4 bytes
                std::uint8_t pad_1994[0x4]; // 0x1994, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Ability_FireBomb) == 0x1998, "CCitadel_Ability_FireBomb size mismatch");
        }
    }
}
