/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CCitadelBaseAbility.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CBaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x11c8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Ability_WreckerTeleport : public shade::sdk::server::CCitadelBaseAbility {
            public:
                std::uint8_t pad_0f70[0x8]; // 0x0f70, 0x8 bytes
                CHandle<shade::sdk::server::CBaseEntity> m_hProjectile; // 0x0f78, 0x4 bytes
                float m_flArrowSpeed; // 0x0f7c, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flSnapAnglesBackTime; // 0x0f80, 0x4 bytes
                float m_flCastTimeDamage; // 0x0f84, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flCastTime; // 0x0f88, 0x4 bytes
                bool m_bNeedsExplosion; // 0x0f8c, 0x1 bytes
                std::uint8_t pad_0f8d[0x3]; // 0x0f8d, 0x3 bytes
                Vector m_vProjectileRemovedOrigin; // 0x0f90, 0xc bytes
                QAngle m_angCasterAnglesAtCastTime; // 0x0f9c, 0xc bytes
                float m_flTravelDistance; // 0x0fa8, 0x4 bytes
                std::uint8_t pad_0fac[0x21c]; // 0x0fac, 0x21c bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void; // Offset: 0x0, Size: 0x0, Size In Bytes: 0x0
             */

            static_assert(sizeof(CCitadel_Ability_WreckerTeleport) == 0x11C8, "CCitadel_Ability_WreckerTeleport size mismatch");
        }
    }
}
