/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CCitadelModifier.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1d8
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadelModifierDruidLeechSeed : public shade::sdk::server::CCitadelModifier {
            public:
                std::int32_t m_nDamagePulsesDone; // 0x00d0, 0x4 bytes
                std::uint8_t pad_00d4[0x104]; // 0x00d4, 0x104 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadelModifierDruidLeechSeed) == 0x1D8, "CCitadelModifierDruidLeechSeed size mismatch");
        }
    }
}
