/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/CEntityIOOutput.hpp"
#include "shade/sdk/server/CBaseTrigger.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x958
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadelHideoutTeleportTrigger : public shade::sdk::server::CBaseTrigger {
            public:
                std::uint8_t pad_08e0[0x40]; // 0x08e0, 0x40 bytes
                CUtlSymbolLarge m_strDestLandmark; // 0x0920, 0x8 bytes
                CUtlSymbolLarge m_strDestMap; // 0x0928, 0x8 bytes
                CUtlSymbolLarge m_strDestLocString; // 0x0930, 0x8 bytes
                shade::sdk::entity2::CEntityIOOutput m_OnHideoutTeleport; // 0x0938, 0x18 bytes
                CUtlSymbolLarge m_strPropModel; // 0x0950, 0x8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadelHideoutTeleportTrigger) == 0x958, "CCitadelHideoutTeleportTrigger size mismatch");
        }
    }
}
