/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CCitadel_Modifier_BaseBulletPreRollProc.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x3c8
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Modifier_ChainLightning : public shade::sdk::server::CCitadel_Modifier_BaseBulletPreRollProc {
            public:
                std::uint8_t pad_02f8[0xc8]; // 0x02f8, 0xc8 bytes
                shade::sdk::entity2::GameTime_t m_flNextProcTime; // 0x03c0, 0x4 bytes
                std::uint8_t pad_03c4[0x4]; // 0x03c4, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Modifier_ChainLightning) == 0x3C8, "CCitadel_Modifier_ChainLightning size mismatch");
        }
    }
}
