/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CCitadelModifier.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x2e8
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Modifier_Werewolf_Kickflip_SucessSelf : public shade::sdk::server::CCitadelModifier {
            public:
                std::uint8_t pad_00d0[0x200]; // 0x00d0, 0x200 bytes
                Vector m_vecInitialVelocity; // 0x02d0, 0xc bytes
                Vector m_vecKickOffVelocity; // 0x02dc, 0xc bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Modifier_Werewolf_Kickflip_SucessSelf) == 0x2E8, "CCitadel_Modifier_Werewolf_Kickflip_SucessSelf size mismatch");
        }
    }
}
