/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CCitadel_Item.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1228
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_WeaponUpgrade_ExpressShot : public shade::sdk::server::CCitadel_Item {
            public:
                std::uint8_t pad_0f78[0x280]; // 0x0f78, 0x280 bytes
                std::int32_t m_iShotsToCreate; // 0x11f8, 0x4 bytes
                bool m_bIsInExpressShot; // 0x11fc, 0x1 bytes
                std::uint8_t pad_11fd[0x3]; // 0x11fd, 0x3 bytes
                shade::sdk::entity2::GameTime_t m_tNextShotTime; // 0x1200, 0x4 bytes
                std::uint8_t pad_1204[0x1c]; // 0x1204, 0x1c bytes
                bool m_bIsPrimaryProc; // 0x1220, 0x1 bytes
                std::uint8_t pad_1221[0x7]; // 0x1221, 0x7 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void; // Offset: 0x0, Size: 0x0, Size In Bytes: 0x0
             */

            static_assert(sizeof(CCitadel_WeaponUpgrade_ExpressShot) == 0x1228, "CCitadel_WeaponUpgrade_ExpressShot size mismatch");
        }
    }
}
