/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CCitadelAnimatingModelEntity.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CCitadelBaseAbility;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0xc20
             * Alignment: 0x10
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Nano_Predatory_Statue : public shade::sdk::server::CCitadelAnimatingModelEntity {
            public:
                std::uint8_t pad_0bf0[0x28]; // 0x0bf0, 0x28 bytes
                CHandle<shade::sdk::server::CCitadelBaseAbility> m_hAbility; // 0x0c18, 0x4 bytes
                float m_flLifetime; // 0x0c1c, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Nano_Predatory_Statue) == 0xC20, "CCitadel_Nano_Predatory_Statue size mismatch");
        }
    }
}
