/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/ParticleIndex_t.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CCitadelBaseAbility.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x13d0
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Ability_SuperNeutralCharge : public shade::sdk::server::CCitadelBaseAbility {
            public:
                std::uint8_t pad_0f70[0x400]; // 0x0f70, 0x400 bytes
                bool m_bPreparing; // 0x1370, 0x1 bytes
                bool m_bTackling; // 0x1371, 0x1 bytes
                std::uint8_t pad_1372[0x2]; // 0x1372, 0x2 bytes
                shade::sdk::entity2::GameTime_t m_flTackleStartTime; // 0x1374, 0x4 bytes
                float m_flTackleDuration; // 0x1378, 0x4 bytes
                Vector m_vecTackleDir; // 0x137c, 0xc bytes
                Vector m_vecLastPosition; // 0x1388, 0xc bytes
                std::int32_t m_nStuckFramesCount; // 0x1394, 0x4 bytes
                CUtlVector<CEntityIndex> m_vecHitEnemies; // 0x1398, 0x18 bytes
                shade::sdk::entity2::GameTime_t m_flPrepareStartTime; // 0x13b0, 0x4 bytes
                shade::sdk::client::ParticleIndex_t m_nDistancePreview; // 0x13b4, 0x4 bytes
                std::uint8_t pad_13b8[0x18]; // 0x13b8, 0x18 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void; // Offset: 0x0, Size: 0x0, Size In Bytes: 0x0
             */

            static_assert(sizeof(CCitadel_Ability_SuperNeutralCharge) == 0x13D0, "CCitadel_Ability_SuperNeutralCharge size mismatch");
        }
    }
}
