/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/ParticleIndex_t.hpp"
#include "shade/sdk/server/CCitadelModifier.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CBaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x390
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Modifier_ChronoSwap_BubbleMove : public shade::sdk::server::CCitadelModifier {
            public:
                bool m_bOtherIsInFrontAtStart; // 0x00d0, 0x1 bytes
                std::uint8_t pad_00d1[0x3]; // 0x00d1, 0x3 bytes
                Vector m_vOtherToDest; // 0x00d4, 0xc bytes
                VectorWS m_vStart; // 0x00e0, 0xc bytes
                VectorWS m_vDest; // 0x00ec, 0xc bytes
                CHandle<shade::sdk::server::CBaseEntity> m_hOther; // 0x00f8, 0x4 bytes
                VectorWS m_vLastSafePos; // 0x00fc, 0xc bytes
                bool m_bDoFinalTeleport; // 0x0108, 0x1 bytes
                std::uint8_t pad_0109[0x3]; // 0x0109, 0x3 bytes
                shade::sdk::client::ParticleIndex_t m_nBeamIndex; // 0x010c, 0x4 bytes
                std::uint8_t pad_0110[0x280]; // 0x0110, 0x280 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Modifier_ChronoSwap_BubbleMove) == 0x390, "CCitadel_Modifier_ChronoSwap_BubbleMove size mismatch");
        }
    }
}
