/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CAI_CitadelNPC.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CBaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1810
             * Alignment: 0x10
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_PestilenceDroneDispenser : public shade::sdk::server::CAI_CitadelNPC {
            public:
                std::uint8_t pad_17b0[0x10]; // 0x17b0, 0x10 bytes
                CHandle<shade::sdk::server::CBaseEntity> m_hAbility; // 0x17c0, 0x4 bytes
                std::uint8_t pad_17c4[0x4c]; // 0x17c4, 0x4c bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_PestilenceDroneDispenser) == 0x1810, "CCitadel_PestilenceDroneDispenser size mismatch");
        }
    }
}
