/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/EViscousBowlingBallState_t.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CCitadelBaseAbility.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CCitadelViscousBall;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x20f8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Ability_GooBowlingBall : public shade::sdk::server::CCitadelBaseAbility {
            public:
                std::uint8_t pad_14a0[0x9a0]; // 0x14a0, 0x9a0 bytes
                std::int32_t m_nAirJumpsLeft; // 0x1e40, 0x4 bytes
                bool m_bIsRolling; // 0x1e44, 0x1 bytes
                std::uint8_t pad_1e45[0x3]; // 0x1e45, 0x3 bytes
                CHandle<shade::sdk::server::CCitadelViscousBall> m_hBall; // 0x1e48, 0x4 bytes
                shade::sdk::client::EViscousBowlingBallState_t m_eRollingState; // 0x1e4c, 0x1 bytes
                std::uint8_t pad_1e4d[0x3]; // 0x1e4d, 0x3 bytes
                shade::sdk::entity2::GameTime_t m_flNextStateTime; // 0x1e50, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flNextWallCheck; // 0x1e54, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flRollStartTime; // 0x1e58, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flWallExitTime; // 0x1e5c, 0x4 bytes
                Vector m_vecWallExitVelocity; // 0x1e60, 0xc bytes
                std::uint8_t pad_1e6c[0x28c]; // 0x1e6c, 0x28c bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Ability_GooBowlingBall) == 0x20F8, "CCitadel_Ability_GooBowlingBall size mismatch");
        }
    }
}
