/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CitadelCameraOperationsSequence_t.hpp"
#include "shade/sdk/server/CitadelAbilityVData.hpp"

namespace shade {
    namespace sdk {
        namespace resourcesystem {
            class InfoForResourceTypeIParticleSystemDefinition;
        }

        namespace server {
            class CCitadelModifier;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1ce8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Ability_AirheartRocketeer3VData : public shade::sdk::server::CitadelAbilityVData {
            public:
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_JetpackFireFX; // 0x1818, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_VTOLExplosionFX; // 0x18f8, 0xe0 bytes
                float m_flAirDashDistancePct; // 0x19d8, 0x4 bytes
                float m_flAirDrag; // 0x19dc, 0x4 bytes
                float m_flAirSpeed; // 0x19e0, 0x4 bytes
                float m_flBeginJetpackingVelocityMultiplier; // 0x19e4, 0x4 bytes
                float m_flTimeToHoldBeforeBeginJetpack; // 0x19e8, 0x4 bytes
                float m_flVerticalDampening_FallingBelowNeutral; // 0x19ec, 0x4 bytes
                float m_flVerticalDampening_FallingAboveNeutral; // 0x19f0, 0x4 bytes
                float m_flVerticalDampening_RisingBelowNeutral; // 0x19f4, 0x4 bytes
                float m_flVerticalDampening_RisingAboveNeutral; // 0x19f8, 0x4 bytes
                float m_flVerticalDeadzoneSoft; // 0x19fc, 0x4 bytes
                float m_flVerticalDeadzoneHard; // 0x1a00, 0x4 bytes
                float m_flPreservedVelocityDecaySpeed; // 0x1a04, 0x4 bytes
                float m_flIntentMultiplierApproachSpeed; // 0x1a08, 0x4 bytes
                float m_flMPCOriginCoeff; // 0x1a0c, 0x4 bytes
                float m_flMPCVelocityCoeff; // 0x1a10, 0x4 bytes
                float m_flMPCScale; // 0x1a14, 0x4 bytes
                float m_flMPCMaxAccel; // 0x1a18, 0x4 bytes
                float m_flMoveSpaceSpeed_ZUp; // 0x1a1c, 0x4 bytes
                float m_flMoveSpaceSpeed_ZDown; // 0x1a20, 0x4 bytes
                float m_flMoveSpaceSpeed_Lateral; // 0x1a24, 0x4 bytes
                float m_flMoveSpaceSpeed_LateralZUp; // 0x1a28, 0x4 bytes
                float m_flMoveSpaceSpeed_Forward; // 0x1a2c, 0x4 bytes
                float m_flMoveSpaceSpeed_Backward; // 0x1a30, 0x4 bytes
                float m_flIntentSpaceSoftZone; // 0x1a34, 0x4 bytes
                float m_flIntentSpaceHardZone; // 0x1a38, 0x4 bytes
                float m_flHardZoneCoeffFrac; // 0x1a3c, 0x4 bytes
                float m_flSoftZoneCoeffFrac; // 0x1a40, 0x4 bytes
                std::uint8_t pad_1a44[0x4]; // 0x1a44, 0x4 bytes
                CPiecewiseCurve m_OverdriveLateral; // 0x1a48, 0x40 bytes
                float m_flOverdriveCooldown; // 0x1a88, 0x4 bytes
                float m_flConsumedBySideThrusting; // 0x1a8c, 0x4 bytes
                float m_flConsumedWhileActive; // 0x1a90, 0x4 bytes
                float m_flHoverVelocityDecaySpeed; // 0x1a94, 0x4 bytes
                CPiecewiseCurve m_VTOLSpeedByTime; // 0x1a98, 0x40 bytes
                float m_flVTOLCamTurnRate; // 0x1ad8, 0x4 bytes
                std::uint8_t pad_1adc[0x4]; // 0x1adc, 0x4 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_VTOLModifier; // 0x1ae0, 0x10 bytes
                float m_flMaxVTOLBounceSpeed; // 0x1af0, 0x4 bytes
                float m_flVTOLFloorBounceZSpeed; // 0x1af4, 0x4 bytes
                float m_flWallAttachCooldown; // 0x1af8, 0x4 bytes
                float m_flWallJumpSpeed; // 0x1afc, 0x4 bytes
                float m_flWallAttachMinDuration; // 0x1b00, 0x4 bytes
                std::uint8_t pad_1b04[0x4]; // 0x1b04, 0x4 bytes
                CSoundEventName m_strOutOfFuelSound; // 0x1b08, 0x10 bytes
                CSoundEventName m_strOverdriveActivatedSound; // 0x1b18, 0x10 bytes
                CSoundEventName m_strJetpackingLoop; // 0x1b28, 0x10 bytes
                CSoundEventName m_strJetpackingThrustingLoop; // 0x1b38, 0x10 bytes
                shade::sdk::client::CitadelCameraOperationsSequence_t m_cameraSequenceVTOL; // 0x1b48, 0x88 bytes
                shade::sdk::client::CitadelCameraOperationsSequence_t m_cameraSequenceHover; // 0x1bd0, 0x88 bytes
                shade::sdk::client::CitadelCameraOperationsSequence_t m_cameraSequenceWallAttach; // 0x1c58, 0x88 bytes
                float flScreenShake_VTOL_Amplitude; // 0x1ce0, 0x4 bytes
                float flScreenShake_VTOL_Frequency; // 0x1ce4, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Ability_AirheartRocketeer3VData) == 0x1CE8, "CCitadel_Ability_AirheartRocketeer3VData size mismatch");
        }
    }
}
