/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CCitadel_Modifier_InvisVData.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0xa38
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Modifier_LurkersAmbush_InvisVData : public shade::sdk::server::CCitadel_Modifier_InvisVData {
            public:
                float m_flMaxCameraAngleForSeeing; // 0x0a28, 0x4 bytes
                float m_flMaxDistanceForSeeing; // 0x0a2c, 0x4 bytes
                float m_flInvisBias; // 0x0a30, 0x4 bytes
                float m_flSpottedMinTimeToStart; // 0x0a34, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Modifier_LurkersAmbush_InvisVData) == 0xA38, "CCitadel_Modifier_LurkersAmbush_InvisVData size mismatch");
        }
    }
}
