/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CCitadelModifier.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x420
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Modifier_PunkgoatPull : public shade::sdk::server::CCitadelModifier {
            public:
                float m_flDamageToDealAtEnd; // 0x0140, 0x4 bytes
                float m_flDamageLeftToDealOverPull; // 0x0144, 0x4 bytes
                float m_flDamageOverPullAccumulator; // 0x0148, 0x4 bytes
                VectorWS m_vPullToLocation; // 0x014c, 0xc bytes
                bool m_bAllowTrackTarget; // 0x0158, 0x1 bytes
                std::uint8_t pad_0159[0x3]; // 0x0159, 0x3 bytes
                float m_flCurrentVerticalSpeed; // 0x015c, 0x4 bytes
                std::uint8_t pad_0160[0x2c0]; // 0x0160, 0x2c0 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Modifier_PunkgoatPull) == 0x420, "CCitadel_Modifier_PunkgoatPull size mismatch");
        }
    }
}
