/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CCitadelModifierVData.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            struct RatArmorPiece_t;
        }

        namespace resourcesystem {
            class InfoForResourceTypeIParticleSystemDefinition;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0xc48
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Modifier_RatKing_RatArmorVData : public shade::sdk::server::CCitadelModifierVData {
            public:
                CSoundEventName m_strKnockoffArmorSound; // 0x0790, 0x10 bytes
                CSoundEventName m_strBlockedDamageSound; // 0x07a0, 0x10 bytes
                CSoundEventName m_strAttackerHitSound; // 0x07b0, 0x10 bytes
                CSoundEventName m_strHitProcSound; // 0x07c0, 0x10 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_RatParticle; // 0x07d0, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_AttackerHitFx; // 0x08b0, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_ImpactParticle; // 0x0990, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_KnockoffParticle; // 0x0a70, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_RatShieldStartParticle; // 0x0b50, 0xe0 bytes
                CUtlVector<shade::sdk::client::RatArmorPiece_t> m_vecArmorPieces; // 0x0c30, 0x18 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Modifier_RatKing_RatArmorVData) == 0xC48, "CCitadel_Modifier_RatKing_RatArmorVData size mismatch");
        }
    }
}
