/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CCitadelModifier.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CCitadelPortalTrigger;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x100
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Modifier_Link : public shade::sdk::server::CCitadelModifier {
            public:
                CHandle<shade::sdk::server::CCitadelPortalTrigger> m_hPortalToCaster; // 0x00d0, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flPortalStartTime; // 0x00d4, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flPortalEndTime; // 0x00d8, 0x4 bytes
                std::uint8_t pad_00dc[0x4]; // 0x00dc, 0x4 bytes
                CUtlString m_sCasterAttachment; // 0x00e0, 0x8 bytes
                CUtlString m_sParentAttachment; // 0x00e8, 0x8 bytes
                VectorWS m_vecLinkPosition; // 0x00f0, 0xc bytes
                std::uint8_t pad_00fc[0x4]; // 0x00fc, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Modifier_Link) == 0x100, "CCitadel_Modifier_Link size mismatch");
        }
    }
}
