/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CCitadelModifier.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x168
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Modifier_Doorman_DimishingTimestop : public shade::sdk::server::CCitadelModifier {
            public:
                float m_flSlowPercent; // 0x00d0, 0x4 bytes
                float m_flDelay; // 0x00d4, 0x4 bytes
                bool m_bEscaped; // 0x00d8, 0x1 bytes
                std::uint8_t pad_00d9[0x87]; // 0x00d9, 0x87 bytes
                bool m_bStunApplied; // 0x0160, 0x1 bytes
                std::uint8_t pad_0161[0x7]; // 0x0161, 0x7 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Modifier_Doorman_DimishingTimestop) == 0x168, "CCitadel_Modifier_Doorman_DimishingTimestop size mismatch");
        }
    }
}
