/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CCitadelBaseAbility.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CBaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x11f8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Ability_Perched_Predator : public shade::sdk::server::CCitadelBaseAbility {
            public:
                std::uint8_t pad_0f70[0x280]; // 0x0f70, 0x280 bytes
                CHandle<shade::sdk::server::CBaseEntity> m_hActiveProjectile; // 0x11f0, 0x4 bytes
                std::uint8_t pad_11f4[0x4]; // 0x11f4, 0x4 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void; // Offset: 0x0, Size: 0x0, Size In Bytes: 0x0
             */

            static_assert(sizeof(CCitadel_Ability_Perched_Predator) == 0x11F8, "CCitadel_Ability_Perched_Predator size mismatch");
        }
    }
}
