/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/ParticleIndex_t.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CCitadelBaseYamatoAbility.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CBaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1368
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Ability_FlyingStrike : public shade::sdk::server::CCitadelBaseYamatoAbility {
            public:
                std::uint8_t pad_0f78[0x28]; // 0x0f78, 0x28 bytes
                std::int32_t m_iTargetPosIndex; // 0x0fa0, 0x4 bytes
                bool m_bShadowFormCast; // 0x0fa4, 0x1 bytes
                std::uint8_t pad_0fa5[0x3]; // 0x0fa5, 0x3 bytes
                Vector m_vYamatoCastPos; // 0x0fa8, 0xc bytes
                Vector m_vTargetCastPos; // 0x0fb4, 0xc bytes
                shade::sdk::entity2::GameTime_t m_flFlyingToTargetStartTime; // 0x0fc0, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flEndAttackTime; // 0x0fc4, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flGrappleStartTime; // 0x0fc8, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flGrappleArriveTime; // 0x0fcc, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flAttackLatchTime; // 0x0fd0, 0x4 bytes
                Vector m_vAttackLatchPos; // 0x0fd4, 0xc bytes
                CHandle<shade::sdk::server::CBaseEntity> m_hTarget; // 0x0fe0, 0x4 bytes
                bool m_bIsTargetAlly; // 0x0fe4, 0x1 bytes
                std::uint8_t pad_0fe5[0x3]; // 0x0fe5, 0x3 bytes
                shade::sdk::entity2::GameTime_t m_flGrappleShotAttackTime; // 0x0fe8, 0x4 bytes
                CHandle<shade::sdk::server::CBaseEntity> m_hAttackTarget; // 0x0fec, 0x4 bytes
                Vector m_rgPath[0x14]; // 0x0ff0, 0xf0 bytes
                std::int32_t m_nPathIdx; // 0x10e0, 0x4 bytes
                std::int32_t m_nPathSize; // 0x10e4, 0x4 bytes
                float m_flPathLength; // 0x10e8, 0x4 bytes
                Vector m_vFlyingInitialOffsetToPath; // 0x10ec, 0xc bytes
                float flDistFlown; // 0x10f8, 0x4 bytes
                Vector m_vLastSafePos; // 0x10fc, 0xc bytes
                std::uint8_t pad_1108[0x200]; // 0x1108, 0x200 bytes
                shade::sdk::client::ParticleIndex_t m_nGrappleTravelEffect; // 0x1308, 0x4 bytes
                std::uint8_t pad_130c[0x54]; // 0x130c, 0x54 bytes
                bool m_bPathDirty; // 0x1360, 0x1 bytes
                std::uint8_t pad_1361[0x7]; // 0x1361, 0x7 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void; // Offset: 0x0, Size: 0x0, Size In Bytes: 0x0
             */

            static_assert(sizeof(CCitadel_Ability_FlyingStrike) == 0x1368, "CCitadel_Ability_FlyingStrike size mismatch");
        }
    }
}
