/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CBaseModelEntity.hpp"
#include "shade/sdk/server/ice_path_shard_model_desc_t.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x8d0
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Ice_Path_Shard_Physics : public shade::sdk::server::CBaseModelEntity {
            public:
                shade::sdk::server::ice_path_shard_model_desc_t m_ShardDesc; // 0x0878, 0x38 bytes
                QAngle m_qForward; // 0x08b0, 0xc bytes
                shade::sdk::entity2::GameTime_t m_flStartTime; // 0x08bc, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flEndTime; // 0x08c0, 0x4 bytes
                float m_flShardWidth; // 0x08c4, 0x4 bytes
                std::uint8_t pad_08c8[0x8]; // 0x08c8, 0x8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Ice_Path_Shard_Physics) == 0x8D0, "CCitadel_Ice_Path_Shard_Physics size mismatch");
        }
    }
}
