/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/GameTime_t.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CPointCommentaryNode;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x60
             * Alignment: 0xff
             * Has VTable
             */
            #pragma pack(push, 1)
            class CCommentarySystem {
            public:
                std::uint8_t pad_0000[0x11]; // 0x0000, 0x11 bytes
                bool m_bCommentaryConvarsChanging; // 0x0011, 0x1 bytes
                bool m_bCommentaryEnabledMidGame; // 0x0012, 0x1 bytes
                std::uint8_t pad_0013[0x1]; // 0x0013, 0x1 bytes
                shade::sdk::entity2::GameTime_t m_flNextTeleportTime; // 0x0014, 0x4 bytes
                std::int32_t m_iTeleportStage; // 0x0018, 0x4 bytes
                bool m_bCheatState; // 0x001c, 0x1 bytes
                bool m_bIsFirstSpawnGroupToLoad; // 0x001d, 0x1 bytes
                std::uint8_t pad_001e[0x1a]; // 0x001e, 0x1a bytes
                CHandle<shade::sdk::server::CPointCommentaryNode> m_hCurrentNode; // 0x0038, 0x4 bytes
                CHandle<shade::sdk::server::CPointCommentaryNode> m_hActiveCommentaryNode; // 0x003c, 0x4 bytes
                CHandle<shade::sdk::server::CPointCommentaryNode> m_hLastCommentaryNode; // 0x0040, 0x4 bytes
                std::uint8_t pad_0044[0x4]; // 0x0044, 0x4 bytes
                CUtlVector<CHandle<shade::sdk::server::CPointCommentaryNode>> m_vecNodes; // 0x0048, 0x18 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void m_ModifiedConvars; // Offset: 0x20, Size: 0x1, Size In Bytes: 0x18
             */

            static_assert(sizeof(CCommentarySystem) == 0x60, "CCommentarySystem size mismatch");
        }
    }
}
