/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CPlayer_UseServices.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CBaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x58
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCSPlayer_UseServices : public shade::sdk::server::CPlayer_UseServices {
            public:
                CHandle<shade::sdk::server::CBaseEntity> m_hLastKnownUseEntity; // 0x0048, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flLastUseTimeStamp; // 0x004c, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flTimeLastUsedWindow; // 0x0050, 0x4 bytes
                std::uint8_t pad_0054[0x4]; // 0x0054, 0x4 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void; // Offset: 0x0, Size: 0x0, Size In Bytes: 0x0
             */

            static_assert(sizeof(CCSPlayer_UseServices) == 0x58, "CCSPlayer_UseServices size mismatch");
        }
    }
}
