/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CBaseEntity.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x540
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCSPlayerResource : public shade::sdk::server::CBaseEntity {
            public:
                bool m_bHostageAlive[0xc]; // 0x04a8, 0xc bytes
                bool m_isHostageFollowingSomeone[0xc]; // 0x04b4, 0xc bytes
                CEntityIndex m_iHostageEntityIDs[0xc]; // 0x04c0, 0x30 bytes
                VectorWS m_bombsiteCenterA; // 0x04f0, 0xc bytes
                VectorWS m_bombsiteCenterB; // 0x04fc, 0xc bytes
                std::int32_t m_hostageRescueX[0x4]; // 0x0508, 0x10 bytes
                std::int32_t m_hostageRescueY[0x4]; // 0x0518, 0x10 bytes
                std::int32_t m_hostageRescueZ[0x4]; // 0x0528, 0x10 bytes
                bool m_bEndMatchNextMapAllVoted; // 0x0538, 0x1 bytes
                bool m_foundGoalPositions; // 0x0539, 0x1 bytes
                std::uint8_t pad_053a[0x6]; // 0x053a, 0x6 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void; // Offset: 0x0, Size: 0x0, Size In Bytes: 0x0
             */

            static_assert(sizeof(CCSPlayerResource) == 0x540, "CCSPlayerResource size mismatch");
        }
    }
}
