/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CEntitySubclassVDataBase.hpp"

namespace shade {
    namespace sdk {
        namespace resourcesystem {
            class InfoForResourceTypeCModel;
            class InfoForResourceTypeIParticleSystemDefinition;
        }

        namespace server {
            class CCitadelModifier;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x460
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDestructableBuildingVData : public shade::sdk::client::CEntitySubclassVDataBase {
            public:
                float m_flEnemyTrooperProtectionRange; // 0x0028, 0x4 bytes
                float m_flTrooperJumpRange; // 0x002c, 0x4 bytes
                float m_flFinishedDyingThink; // 0x0030, 0x4 bytes
                std::uint8_t pad_0034[0x4]; // 0x0034, 0x4 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeCModel>> m_sAmberModelName; // 0x0038, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeCModel>> m_sSapphModelName; // 0x0118, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_AmberDeathParticle; // 0x01f8, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_SapphDeathParticle; // 0x02d8, 0xe0 bytes
                CSoundEventName m_AmberDeathSound; // 0x03b8, 0x10 bytes
                CSoundEventName m_SapphDeathSound; // 0x03c8, 0x10 bytes
                std::int32_t m_iMaxHealthFinal; // 0x03d8, 0x4 bytes
                std::int32_t m_iMaxHealthGenerator; // 0x03dc, 0x4 bytes
                std::int32_t m_iMaxHealthGeneratorSecond; // 0x03e0, 0x4 bytes
                std::uint8_t pad_03e4[0x4]; // 0x03e4, 0x4 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_PowerGenerator; // 0x03e8, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_ObjectiveRegen; // 0x03f8, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_BackdoorBulletResistModifier; // 0x0408, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_BackdoorProtectionModifier; // 0x0418, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_RangedArmorModifier; // 0x0428, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::server::CCitadelModifier> m_BarrackBossProtection; // 0x0438, 0x10 bytes
                CUtlVector<CEmbeddedSubclass<shade::sdk::server::CCitadelModifier>> m_vecIntrinsicModifiers; // 0x0448, 0x18 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDestructableBuildingVData) == 0x460, "CDestructableBuildingVData size mismatch");
        }
    }
}
