/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CDOTA_Buff.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1ac8
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTA_Modifier_MonkeyKing_BoundlessStrike_ShardMovement : public shade::sdk::client::CDOTA_Buff {
            public:
                float m_flPredictedTotalTime; // 0x1a78, 0x4 bytes
                VectorWS m_vStartPosition; // 0x1a7c, 0xc bytes
                float m_flCurrentTimeHoriz; // 0x1a88, 0x4 bytes
                float m_flCurrentTimeVert; // 0x1a8c, 0x4 bytes
                bool m_bHorizontalMotionInterrupted; // 0x1a90, 0x1 bytes
                std::uint8_t pad_1a91[0x3]; // 0x1a91, 0x3 bytes
                Vector m_vHorizontalVelocity; // 0x1a94, 0xc bytes
                VectorWS m_vLastKnownTargetPosition; // 0x1aa0, 0xc bytes
                float m_flInitialVelocityZ; // 0x1aac, 0x4 bytes
                std::int32_t acceleration_z; // 0x1ab0, 0x4 bytes
                std::int32_t min_height_above_lowest; // 0x1ab4, 0x4 bytes
                std::int32_t min_height_above_highest; // 0x1ab8, 0x4 bytes
                std::int32_t max_horizontal_acceleration; // 0x1abc, 0x4 bytes
                std::int32_t spring_channel_pct; // 0x1ac0, 0x4 bytes
                std::uint8_t pad_1ac4[0x4]; // 0x1ac4, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTA_Modifier_MonkeyKing_BoundlessStrike_ShardMovement) == 0x1AC8, "CDOTA_Modifier_MonkeyKing_BoundlessStrike_ShardMovement size mismatch");
        }
    }
}
