/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CDOTA_Buff.hpp"
#include "shade/sdk/client/ParticleIndex_t.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CBaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1b20
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTA_Modifier_Hoodwink_ArcingBoomerang : public shade::sdk::client::CDOTA_Buff {
            public:
                VectorWS m_vLeftControl; // 0x1a78, 0xc bytes
                VectorWS m_vRightControl; // 0x1a84, 0xc bytes
                VectorWS m_vTargetLoc; // 0x1a90, 0xc bytes
                VectorWS m_vOriginalTargetLoc; // 0x1a9c, 0xc bytes
                VectorWS m_vSourceLoc; // 0x1aa8, 0xc bytes
                bool m_bGroundTargeted; // 0x1ab4, 0x1 bytes
                std::uint8_t pad_1ab5[0x3]; // 0x1ab5, 0x3 bytes
                float m_flTravelDuration; // 0x1ab8, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flBoomerangDieTime; // 0x1abc, 0x4 bytes
                bool m_bReturning; // 0x1ac0, 0x1 bytes
                bool m_bCatchingBoomerang; // 0x1ac1, 0x1 bytes
                bool m_bDisjointed; // 0x1ac2, 0x1 bytes
                std::uint8_t pad_1ac3[0x1]; // 0x1ac3, 0x1 bytes
                std::int32_t m_nFramesToWait; // 0x1ac4, 0x4 bytes
                CHandle<shade::sdk::server::CBaseEntity> m_hBoomerang; // 0x1ac8, 0x4 bytes
                CHandle<shade::sdk::server::CBaseEntity> m_hTarget; // 0x1acc, 0x4 bytes
                shade::sdk::client::ParticleIndex_t m_nBoomerangFXIndex; // 0x1ad0, 0x4 bytes
                shade::sdk::client::ParticleIndex_t m_nOldBoomerangFXindex; // 0x1ad4, 0x4 bytes
                CUtlVector<CHandle<shade::sdk::server::CBaseEntity>> m_vecUniqueHitList; // 0x1ad8, 0x18 bytes
                float radius; // 0x1af0, 0x4 bytes
                float spread; // 0x1af4, 0x4 bytes
                float damage; // 0x1af8, 0x4 bytes
                float mark_duration; // 0x1afc, 0x4 bytes
                float min_throw_duration; // 0x1b00, 0x4 bytes
                float max_throw_duration; // 0x1b04, 0x4 bytes
                std::uint8_t pad_1b08[0x18]; // 0x1b08, 0x18 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTA_Modifier_Hoodwink_ArcingBoomerang) == 0x1B20, "CDOTA_Modifier_Hoodwink_ArcingBoomerang size mismatch");
        }
    }
}
