/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CDOTABehaviorCompanion.hpp"
#include "shade/sdk/server/CountdownTimer.hpp"
#include "shade/sdk/server/PetCoopStates_t.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CBaseEntity;
            class CDOTA_BaseNPC;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x2f0
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTABehaviorLargoFrogling : public shade::sdk::server::CDOTABehaviorCompanion {
            public:
                std::uint8_t pad_0180[0x10]; // 0x0180, 0x10 bytes
                float m_flThreatLevel; // 0x0190, 0x4 bytes
                std::uint8_t pad_0194[0x4]; // 0x0194, 0x4 bytes
                shade::sdk::server::CountdownTimer m_ThreatTimer; // 0x0198, 0x18 bytes
                shade::sdk::server::CountdownTimer m_StuckTimer; // 0x01b0, 0x18 bytes
                bool m_bHasVanished; // 0x01c8, 0x1 bytes
                std::uint8_t pad_01c9[0x7]; // 0x01c9, 0x7 bytes
                shade::sdk::server::CountdownTimer m_VanishOnThreatTimer; // 0x01d0, 0x18 bytes
                VectorWS m_vecFleeCurrentTarget; // 0x01e8, 0xc bytes
                Vector m_vecFleeDirection; // 0x01f4, 0xc bytes
                Vector m_vecOldFleeDirection; // 0x0200, 0xc bytes
                std::uint8_t pad_020c[0x4]; // 0x020c, 0x4 bytes
                shade::sdk::server::CountdownTimer m_FleePersistTimer; // 0x0210, 0x18 bytes
                shade::sdk::server::CountdownTimer m_CombatRepositionTimer; // 0x0228, 0x18 bytes
                CHandle<shade::sdk::server::CDOTA_BaseNPC> m_hNearestEnemyHero; // 0x0240, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flLastInWater; // 0x0244, 0x4 bytes
                VectorWS m_vecHomeBasePosition; // 0x0248, 0xc bytes
                bool m_bReturnToBase; // 0x0254, 0x1 bytes
                std::uint8_t pad_0255[0x3]; // 0x0255, 0x3 bytes
                shade::sdk::server::CountdownTimer m_ReturnToBaseTimer; // 0x0258, 0x18 bytes
                shade::sdk::server::PetCoopStates_t m_nCoopTeleportState; // 0x0270, 0x4 bytes
                std::uint8_t pad_0274[0x4]; // 0x0274, 0x4 bytes
                shade::sdk::server::CountdownTimer m_CarryItemTimer; // 0x0278, 0x18 bytes
                shade::sdk::server::CountdownTimer m_PickupDelayTimer; // 0x0290, 0x18 bytes
                shade::sdk::server::CountdownTimer m_LevelupCheckTimer; // 0x02a8, 0x18 bytes
                bool m_bIsEmoting; // 0x02c0, 0x1 bytes
                std::uint8_t pad_02c1[0x3]; // 0x02c1, 0x3 bytes
                CHandle<shade::sdk::server::CDOTA_BaseNPC> m_hEmoteTarget; // 0x02c4, 0x4 bytes
                shade::sdk::server::CountdownTimer m_EmoteTimer; // 0x02c8, 0x18 bytes
                std::int32_t m_nEmoteActivity; // 0x02e0, 0x4 bytes
                CHandle<shade::sdk::server::CBaseEntity> m_tempGoalEntity; // 0x02e4, 0x4 bytes
                bool m_bFollowingTempGoal; // 0x02e8, 0x1 bytes
                std::uint8_t pad_02e9[0x3]; // 0x02e9, 0x3 bytes
                std::int32_t m_event_dota_illusions_created; // 0x02ec, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTABehaviorLargoFrogling) == 0x2F0, "CDOTABehaviorLargoFrogling size mismatch");
        }
    }
}
