/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CDOTA_Buff.hpp"
#include "shade/sdk/client/ParticleIndex_t.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1ad0
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTA_Modifier_ArcWarden_Flux : public shade::sdk::client::CDOTA_Buff {
            public:
                std::int32_t m_nCasterTeam; // 0x1aa8, 0x4 bytes
                float damage_per_second; // 0x1aac, 0x4 bytes
                std::int32_t search_radius; // 0x1ab0, 0x4 bytes
                float move_speed_slow_pct; // 0x1ab4, 0x4 bytes
                std::int32_t status_resist; // 0x1ab8, 0x4 bytes
                float think_interval; // 0x1abc, 0x4 bytes
                std::int32_t applies_silence; // 0x1ac0, 0x4 bytes
                std::int32_t m_nCurrentMovementSlow; // 0x1ac4, 0x4 bytes
                std::int32_t m_nCurrentStatusResistance; // 0x1ac8, 0x4 bytes
                shade::sdk::client::ParticleIndex_t m_nFXIndex; // 0x1acc, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTA_Modifier_ArcWarden_Flux) == 0x1AD0, "CDOTA_Modifier_ArcWarden_Flux size mismatch");
        }
    }
}
