/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CDOTA_ArcanaDataEntity_Base.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x38
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTA_ArcanaDataEntity_Razor : public shade::sdk::client::CDOTA_ArcanaDataEntity_Base {
            public:
                std::int32_t m_nEmpoweredKills; // 0x0030, 0x4 bytes
                std::uint8_t pad_0034[0x4]; // 0x0034, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTA_ArcanaDataEntity_Razor) == 0x38, "CDOTA_ArcanaDataEntity_Razor size mismatch");
        }
    }
}
