/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CDOTA_Buff.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1aa0
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTA_Modifier_TemplarAssassin_Trap_Slow : public shade::sdk::client::CDOTA_Buff {
            public:
                std::int32_t movement_speed_min; // 0x1a78, 0x4 bytes
                std::int32_t movement_speed_max; // 0x1a7c, 0x4 bytes
                std::int32_t extra_damage; // 0x1a80, 0x4 bytes
                float trap_max_charge_duration; // 0x1a84, 0x4 bytes
                float min_silence_duration; // 0x1a88, 0x4 bytes
                float max_silence_duration; // 0x1a8c, 0x4 bytes
                float stage; // 0x1a90, 0x4 bytes
                float flDamagePerTick; // 0x1a94, 0x4 bytes
                bool bExtraDamage; // 0x1a98, 0x1 bytes
                std::uint8_t pad_1a99[0x7]; // 0x1a99, 0x7 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTA_Modifier_TemplarAssassin_Trap_Slow) == 0x1AA0, "CDOTA_Modifier_TemplarAssassin_Trap_Slow size mismatch");
        }
    }
}
