/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CDOTA_Buff.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1a80
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTA_Modifier_Orb_Of_Revelations_Reveal : public shade::sdk::client::CDOTA_Buff {
            public:
                std::int32_t movespeed; // 0x1a78, 0x4 bytes
                bool m_bCastOnInvisibleHero; // 0x1a7c, 0x1 bytes
                std::uint8_t pad_1a7d[0x3]; // 0x1a7d, 0x3 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTA_Modifier_Orb_Of_Revelations_Reveal) == 0x1A80, "CDOTA_Modifier_Orb_Of_Revelations_Reveal size mismatch");
        }
    }
}
