/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/ParticleIndex_t.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CDOTABaseAbility.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x5a8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTA_Ability_QueenOfPain_SonicWave : public shade::sdk::server::CDOTABaseAbility {
            public:
                shade::sdk::entity2::GameTime_t m_fStartTime; // 0x0580, 0x4 bytes
                float m_fTotalTime; // 0x0584, 0x4 bytes
                shade::sdk::client::ParticleIndex_t m_nFXIndex; // 0x0588, 0x4 bytes
                float starting_aoe; // 0x058c, 0x4 bytes
                float final_aoe; // 0x0590, 0x4 bytes
                std::uint8_t pad_0594[0x14]; // 0x0594, 0x14 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void; // Offset: 0x0, Size: 0x0, Size In Bytes: 0x0
             */

            static_assert(sizeof(CDOTA_Ability_QueenOfPain_SonicWave) == 0x5A8, "CDOTA_Ability_QueenOfPain_SonicWave size mismatch");
        }
    }
}
