/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CDOTA_Buff.hpp"
#include "shade/sdk/client/ParticleIndex_t.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CBaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1b00
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTA_Modifier_Marci_Lunge_Arc : public shade::sdk::client::CDOTA_Buff {
            public:
                float m_flPredictedTotalTime; // 0x1a78, 0x4 bytes
                VectorWS m_vStartPosition; // 0x1a7c, 0xc bytes
                float m_flCurrentTimeHoriz; // 0x1a88, 0x4 bytes
                float m_flCurrentTimeVert; // 0x1a8c, 0x4 bytes
                bool m_bDamageApplied; // 0x1a90, 0x1 bytes
                bool m_bTargetTeleported; // 0x1a91, 0x1 bytes
                std::uint8_t pad_1a92[0x2]; // 0x1a92, 0x2 bytes
                Vector m_vHorizontalVelocity; // 0x1a94, 0xc bytes
                VectorWS m_vLastKnownTargetPosition; // 0x1aa0, 0xc bytes
                float m_flInitialVelocityZ; // 0x1aac, 0x4 bytes
                float m_fClampedProjectileSpeed; // 0x1ab0, 0x4 bytes
                shade::sdk::client::ParticleIndex_t m_nFXIndex; // 0x1ab4, 0x4 bytes
                float m_fAcceleration; // 0x1ab8, 0x4 bytes
                bool m_bTriggeredLandingAnim; // 0x1abc, 0x1 bytes
                std::uint8_t pad_1abd[0x3]; // 0x1abd, 0x3 bytes
                std::int32_t m_nMaxJumpDistance; // 0x1ac0, 0x4 bytes
                std::int32_t min_jump_distance; // 0x1ac4, 0x4 bytes
                std::int32_t max_jump_distance; // 0x1ac8, 0x4 bytes
                float min_lob_travel_time; // 0x1acc, 0x4 bytes
                float max_lob_travel_time; // 0x1ad0, 0x4 bytes
                float landing_radius; // 0x1ad4, 0x4 bytes
                float debuff_duration; // 0x1ad8, 0x4 bytes
                float min_height_above_lowest; // 0x1adc, 0x4 bytes
                float min_height_above_highest; // 0x1ae0, 0x4 bytes
                float min_acceleration; // 0x1ae4, 0x4 bytes
                float max_acceleration; // 0x1ae8, 0x4 bytes
                float impact_damage; // 0x1aec, 0x4 bytes
                std::int32_t impact_position_offset; // 0x1af0, 0x4 bytes
                std::int32_t ally_impact_damage_pct; // 0x1af4, 0x4 bytes
                float ally_buff_duration; // 0x1af8, 0x4 bytes
                CHandle<shade::sdk::server::CBaseEntity> m_hBounceEntity; // 0x1afc, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTA_Modifier_Marci_Lunge_Arc) == 0x1B00, "CDOTA_Modifier_Marci_Lunge_Arc size mismatch");
        }
    }
}
