/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CDOTA_Buff.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1aa0
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTA_Modifier_Techies_SnareTrap_Slowed : public shade::sdk::client::CDOTA_Buff {
            public:
                std::uint8_t pad_1a78[0x4]; // 0x1a78, 0x4 bytes
                float damage; // 0x1a7c, 0x4 bytes
                float damage_interval; // 0x1a80, 0x4 bytes
                float move_slow_pct; // 0x1a84, 0x4 bytes
                float cast_slow_pct; // 0x1a88, 0x4 bytes
                float effect_radius; // 0x1a8c, 0x4 bytes
                bool m_bEscaped; // 0x1a90, 0x1 bytes
                std::uint8_t pad_1a91[0x3]; // 0x1a91, 0x3 bytes
                VectorWS vTetherOrigin; // 0x1a94, 0xc bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTA_Modifier_Techies_SnareTrap_Slowed) == 0x1AA0, "CDOTA_Modifier_Techies_SnareTrap_Slowed size mismatch");
        }
    }
}
