/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CDOTA_Buff.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1af8
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTA_Modifier_ContextualTips : public shade::sdk::client::CDOTA_Buff {
            public:
                bool m_bAllEnemiesBots; // 0x1a78, 0x1 bytes
                std::uint8_t pad_1a79[0x3]; // 0x1a79, 0x3 bytes
                shade::sdk::entity2::GameTime_t m_flGloblLastTipSendTime; // 0x1a7c, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flLastEnemyHeroDamageTime; // 0x1a80, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flLastEnemyHeroVisibleTime; // 0x1a84, 0x4 bytes
                std::uint8_t pad_1a88[0x70]; // 0x1a88, 0x70 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTA_Modifier_ContextualTips) == 0x1AF8, "CDOTA_Modifier_ContextualTips size mismatch");
        }
    }
}
