/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CDOTA_Buff.hpp"
#include "shade/sdk/client/ParticleIndex_t.hpp"
#include "shade/sdk/server/CountdownTimer.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1b48
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTA_Modifier_Passive_Lotus_Pool : public shade::sdk::client::CDOTA_Buff {
            public:
                float first_lotus_pickup_time; // 0x1aa8, 0x4 bytes
                float pickup_time_reduction_pct; // 0x1aac, 0x4 bytes
                float min_lotus_pickup_time; // 0x1ab0, 0x4 bytes
                float think_interval; // 0x1ab4, 0x4 bytes
                float radius; // 0x1ab8, 0x4 bytes
                float m_flRemainingPickupTime; // 0x1abc, 0x4 bytes
                float m_flCurrentMaxPickupTime; // 0x1ac0, 0x4 bytes
                std::int32_t m_nLotusSeconds; // 0x1ac4, 0x4 bytes
                shade::sdk::server::CountdownTimer m_LotusTimer; // 0x1ac8, 0x18 bytes
                std::int32_t m_nRespawnSeconds; // 0x1ae0, 0x4 bytes
                std::uint8_t pad_1ae4[0x4]; // 0x1ae4, 0x4 bytes
                shade::sdk::server::CountdownTimer m_RespawnTimer; // 0x1ae8, 0x18 bytes
                std::int32_t m_nLotusesAvailable; // 0x1b00, 0x4 bytes
                std::uint8_t pad_1b04[0x1c]; // 0x1b04, 0x1c bytes
                shade::sdk::server::CountdownTimer m_LotusUpgradeTimer; // 0x1b20, 0x18 bytes
                std::int32_t m_nLotusIndex; // 0x1b38, 0x4 bytes
                shade::sdk::client::ParticleIndex_t m_nFxProgress; // 0x1b3c, 0x4 bytes
                bool m_bWasInUse; // 0x1b40, 0x1 bytes
                std::uint8_t pad_1b41[0x3]; // 0x1b41, 0x3 bytes
                std::int32_t m_iAssociatedTeam; // 0x1b44, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTA_Modifier_Passive_Lotus_Pool) == 0x1B48, "CDOTA_Modifier_Passive_Lotus_Pool size mismatch");
        }
    }
}
