/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CDOTA_Buff_Item.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            struct AttackRecord_t;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1ac0
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTA_Modifier_Item_Bloodthorn : public shade::sdk::server::CDOTA_Buff_Item {
            public:
                CUtlVector<shade::sdk::client::AttackRecord_t> m_InFlightAttackRecords; // 0x1a78, 0x18 bytes
                std::int32_t bonus_intellect; // 0x1a90, 0x4 bytes
                float bonus_mana_regen; // 0x1a94, 0x4 bytes
                std::int32_t bonus_damage; // 0x1a98, 0x4 bytes
                std::int32_t bonus_attack_speed; // 0x1a9c, 0x4 bytes
                std::int32_t spell_amp; // 0x1aa0, 0x4 bytes
                std::int32_t mana_regen_multiplier; // 0x1aa4, 0x4 bytes
                std::int32_t bonus_magic_resist; // 0x1aa8, 0x4 bytes
                float duration; // 0x1aac, 0x4 bytes
                std::int32_t passive_proc_damage; // 0x1ab0, 0x4 bytes
                std::int32_t proc_chance; // 0x1ab4, 0x4 bytes
                float bonus_health_regen; // 0x1ab8, 0x4 bytes
                std::uint8_t pad_1abc[0x4]; // 0x1abc, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTA_Modifier_Item_Bloodthorn) == 0x1AC0, "CDOTA_Modifier_Item_Bloodthorn size mismatch");
        }
    }
}
