/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CDynamicProp.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0xc90
             * Alignment: 0x10
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDynamicPropAlias_cable_dynamic : public shade::sdk::server::CDynamicProp {
            public:
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDynamicPropAlias_cable_dynamic) == 0xC90, "CDynamicPropAlias_cable_dynamic size mismatch");
        }
    }
}
