/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CPointEntity.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x4b8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CEnvTilt : public shade::sdk::server::CPointEntity {
            public:
                float m_Duration; // 0x04a8, 0x4 bytes
                float m_Radius; // 0x04ac, 0x4 bytes
                float m_TiltTime; // 0x04b0, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_stopTime; // 0x04b4, 0x4 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void InputStartTilt; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             * void InputStopTilt; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             */

            static_assert(sizeof(CEnvTilt) == 0x4B8, "CEnvTilt size mismatch");
        }
    }
}
