/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CBaseModelEntity.hpp"

namespace shade {
    namespace sdk {
        namespace resourcesystem {
            class InfoForResourceTypeIMaterial2;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x7d0
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CEnvSky : public shade::sdk::server::CBaseModelEntity {
            public:
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeIMaterial2> m_hSkyMaterial; // 0x0770, 0x8 bytes
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeIMaterial2> m_hSkyMaterialLightingOnly; // 0x0778, 0x8 bytes
                bool m_bStartDisabled; // 0x0780, 0x1 bytes
                Color m_vTintColor; // 0x0781, 0x4 bytes
                Color m_vTintColorLightingOnly; // 0x0785, 0x4 bytes
                std::uint8_t pad_0789[0x3]; // 0x0789, 0x3 bytes
                float m_flBrightnessScale; // 0x078c, 0x4 bytes
                std::int32_t m_nFogType; // 0x0790, 0x4 bytes
                float m_flFogMinStart; // 0x0794, 0x4 bytes
                float m_flFogMinEnd; // 0x0798, 0x4 bytes
                float m_flFogMaxStart; // 0x079c, 0x4 bytes
                float m_flFogMaxEnd; // 0x07a0, 0x4 bytes
                bool m_bEnabled; // 0x07a4, 0x1 bytes
                std::uint8_t pad_07a5[0x2b]; // 0x07a5, 0x2b bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CEnvSky) == 0x7D0, "CEnvSky size mismatch");
        }
    }
}
