/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CBaseEntity.hpp"

namespace shade {
    namespace sdk {
        namespace resourcesystem {
            class InfoForResourceTypeCTextureBase;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1538
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CEnvLightProbeVolume : public shade::sdk::server::CBaseEntity {
            public:
                std::uint8_t pad_04a8[0xff8]; // 0x04a8, 0xff8 bytes
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeCTextureBase> m_Entity_hLightProbeTexture_AmbientCube; // 0x14a0, 0x8 bytes
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeCTextureBase> m_Entity_hLightProbeTexture_SDF; // 0x14a8, 0x8 bytes
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeCTextureBase> m_Entity_hLightProbeTexture_SH2_DC; // 0x14b0, 0x8 bytes
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeCTextureBase> m_Entity_hLightProbeTexture_SH2_R; // 0x14b8, 0x8 bytes
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeCTextureBase> m_Entity_hLightProbeTexture_SH2_G; // 0x14c0, 0x8 bytes
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeCTextureBase> m_Entity_hLightProbeTexture_SH2_B; // 0x14c8, 0x8 bytes
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeCTextureBase> m_Entity_hLightProbeDirectLightIndicesTexture; // 0x14d0, 0x8 bytes
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeCTextureBase> m_Entity_hLightProbeDirectLightScalarsTexture; // 0x14d8, 0x8 bytes
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeCTextureBase> m_Entity_hLightProbeDirectLightShadowsTexture; // 0x14e0, 0x8 bytes
                Vector m_Entity_vBoxMins; // 0x14e8, 0xc bytes
                Vector m_Entity_vBoxMaxs; // 0x14f4, 0xc bytes
                bool m_Entity_bMoveable; // 0x1500, 0x1 bytes
                std::uint8_t pad_1501[0x3]; // 0x1501, 0x3 bytes
                std::int32_t m_Entity_nHandshake; // 0x1504, 0x4 bytes
                std::int32_t m_Entity_nPriority; // 0x1508, 0x4 bytes
                bool m_Entity_bStartDisabled; // 0x150c, 0x1 bytes
                std::uint8_t pad_150d[0x3]; // 0x150d, 0x3 bytes
                std::int32_t m_Entity_nLightProbeSizeX; // 0x1510, 0x4 bytes
                std::int32_t m_Entity_nLightProbeSizeY; // 0x1514, 0x4 bytes
                std::int32_t m_Entity_nLightProbeSizeZ; // 0x1518, 0x4 bytes
                std::int32_t m_Entity_nLightProbeAtlasX; // 0x151c, 0x4 bytes
                std::int32_t m_Entity_nLightProbeAtlasY; // 0x1520, 0x4 bytes
                std::int32_t m_Entity_nLightProbeAtlasZ; // 0x1524, 0x4 bytes
                std::uint8_t pad_1528[0x9]; // 0x1528, 0x9 bytes
                bool m_Entity_bEnabled; // 0x1531, 0x1 bytes
                std::uint8_t pad_1532[0x6]; // 0x1532, 0x6 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CEnvLightProbeVolume) == 0x1538, "CEnvLightProbeVolume size mismatch");
        }
    }
}
