/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CBeam.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CSprite;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x838
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CEnvLaser : public shade::sdk::server::CBeam {
            public:
                CUtlSymbolLarge m_iszLaserTarget; // 0x0810, 0x8 bytes
                CHandle<shade::sdk::server::CSprite> m_pSprite; // 0x0818, 0x4 bytes
                std::uint8_t pad_081c[0x4]; // 0x081c, 0x4 bytes
                CUtlSymbolLarge m_iszSpriteName; // 0x0820, 0x8 bytes
                Vector m_firePosition; // 0x0828, 0xc bytes
                float m_flStartFrame; // 0x0834, 0x4 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void InputTurnOn; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             * void InputTurnOff; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             * void InputToggle; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             * float width; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             * std::int32_t NoiseAmplitude; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             * std::int32_t TextureScroll; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             * CUtlString texture; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             */

            static_assert(sizeof(CEnvLaser) == 0x838, "CEnvLaser size mismatch");
        }
    }
}
