/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CBaseEntity.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            struct FowBlocker_t;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x518
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CFoWBlockerRegion : public shade::sdk::server::CBaseEntity {
            public:
                CUtlVectorEmbeddedNetworkVar<shade::sdk::server::FowBlocker_t> m_vecFowBlockers; // 0x0498, 0x68 bytes
                float m_flMinX; // 0x0500, 0x4 bytes
                float m_flMaxX; // 0x0504, 0x4 bytes
                float m_flMinY; // 0x0508, 0x4 bytes
                float m_flMaxY; // 0x050c, 0x4 bytes
                float m_flGridSize; // 0x0510, 0x4 bytes
                std::uint8_t pad_0514[0x4]; // 0x0514, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CFoWBlockerRegion) == 0x518, "CFoWBlockerRegion size mismatch");
        }
    }
}
