/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CBasePlatTrain.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x908
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CFuncPlat : public shade::sdk::server::CBasePlatTrain {
            public:
                float m_flSpeed; // 0x08f8, 0x4 bytes
                std::uint8_t pad_08fc[0x4]; // 0x08fc, 0x4 bytes
                CUtlSymbolLarge m_sNoise; // 0x0900, 0x8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CFuncPlat) == 0x908, "CFuncPlat size mismatch");
        }
    }
}
