/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CCitadelMinimapComponent.hpp"
#include "shade/sdk/server/CPointEntity.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x508
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CInfoTrooperNeutralCamp : public shade::sdk::server::CPointEntity {
            public:
                shade::sdk::server::CCitadelMinimapComponent m_CCitadelMinimapComponent; // 0x04a0, 0x20 bytes
                std::uint8_t pad_04c0[0x18]; // 0x04c0, 0x18 bytes
                CUtlSymbolLarge m_iszCampName; // 0x04d8, 0x8 bytes
                std::uint8_t pad_04e0[0x28]; // 0x04e0, 0x28 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * bool InputSetDisabled; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             */

            static_assert(sizeof(CInfoTrooperNeutralCamp) == 0x508, "CInfoTrooperNeutralCamp size mismatch");
        }
    }
}
