/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CSceneEntity.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CBaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x7f8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CInstancedSceneEntity : public shade::sdk::server::CSceneEntity {
            public:
                CHandle<shade::sdk::server::CBaseEntity> m_hOwner; // 0x07e0, 0x4 bytes
                bool m_bHadOwner; // 0x07e4, 0x1 bytes
                std::uint8_t pad_07e5[0x3]; // 0x07e5, 0x3 bytes
                float m_flPostSpeakDelay; // 0x07e8, 0x4 bytes
                float m_flPreDelay; // 0x07ec, 0x4 bytes
                bool m_bIsBackground; // 0x07f0, 0x1 bytes
                bool m_bRemoveOnCompletion; // 0x07f1, 0x1 bytes
                std::uint8_t pad_07f2[0x2]; // 0x07f2, 0x2 bytes
                CHandle<shade::sdk::server::CBaseEntity> m_hTarget; // 0x07f4, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CInstancedSceneEntity) == 0x7F8, "CInstancedSceneEntity size mismatch");
        }
    }
}
