/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CitadelAbilityProjectileCreateInfo_t.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x138
             * Alignment: 0xff
             */
            #pragma pack(push, 1)
            struct CitadelCurvedAbilityProjectileCreateInfo_t : public shade::sdk::server::CitadelAbilityProjectileCreateInfo_t {
                float m_flTimeToReturn; // 0x0130, 0x4 bytes
                std::uint8_t pad_0134[0x4]; // 0x0134, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CitadelCurvedAbilityProjectileCreateInfo_t) == 0x138, "CitadelCurvedAbilityProjectileCreateInfo_t size mismatch");
        }
    }
}
