/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CBaseModelEntity.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CItemGeneric;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x788
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CItemGenericTriggerHelper : public shade::sdk::server::CBaseModelEntity {
            public:
                CHandle<shade::sdk::server::CItemGeneric> m_hParentItem; // 0x0780, 0x4 bytes
                std::uint8_t pad_0784[0x4]; // 0x0784, 0x4 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void CItemGenericTriggerHelperItemGenericTriggerHelperTouch; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             */

            static_assert(sizeof(CItemGenericTriggerHelper) == 0x788, "CItemGenericTriggerHelper size mismatch");
        }
    }
}
