/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CPointEntity.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class IPhysicsMotionController;
        }

        namespace server {
            class CBaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x4d8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CKeepUpright : public shade::sdk::server::CPointEntity {
            public:
                std::uint8_t pad_0498[0x8]; // 0x0498, 0x8 bytes
                Vector m_worldGoalAxis; // 0x04a0, 0xc bytes
                Vector m_localTestAxis; // 0x04ac, 0xc bytes
                shade::sdk::client::IPhysicsMotionController *m_pController; // 0x04b8, 0x8 bytes
                CUtlSymbolLarge m_nameAttach; // 0x04c0, 0x8 bytes
                CHandle<shade::sdk::server::CBaseEntity> m_attachedObject; // 0x04c8, 0x4 bytes
                float m_angularLimit; // 0x04cc, 0x4 bytes
                bool m_bActive; // 0x04d0, 0x1 bytes
                bool m_bDampAllRotation; // 0x04d1, 0x1 bytes
                std::uint8_t pad_04d2[0x6]; // 0x04d2, 0x6 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void InputTurnOn; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             * void InputTurnOff; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             * float InputSetAngularLimit; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             */

            static_assert(sizeof(CKeepUpright) == 0x4D8, "CKeepUpright size mismatch");
        }
    }
}
