/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/CEntityIOOutput.hpp"
#include "shade/sdk/server/CBaseEntity.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x500
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CLogicAutoCitadel : public shade::sdk::server::CBaseEntity {
            public:
                shade::sdk::entity2::CEntityIOOutput m_OnWaitingForPlayersToJoin; // 0x04b0, 0x18 bytes
                shade::sdk::entity2::CEntityIOOutput m_OnPreGameWait; // 0x04c8, 0x18 bytes
                shade::sdk::entity2::CEntityIOOutput m_OnGameInProgress; // 0x04e0, 0x18 bytes
                std::uint8_t pad_04f8[0x8]; // 0x04f8, 0x8 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void; // Offset: 0x0, Size: 0x0, Size In Bytes: 0x0
             */

            static_assert(sizeof(CLogicAutoCitadel) == 0x500, "CLogicAutoCitadel size mismatch");
        }
    }
}
