/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/CEntityIOOutput.hpp"
#include "shade/sdk/server/CLogicalEntity.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x510
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CLogicDistanceCheck : public shade::sdk::server::CLogicalEntity {
            public:
                CUtlSymbolLarge m_iszEntityA; // 0x04b0, 0x8 bytes
                CUtlSymbolLarge m_iszEntityB; // 0x04b8, 0x8 bytes
                float m_flZone1Distance; // 0x04c0, 0x4 bytes
                float m_flZone2Distance; // 0x04c4, 0x4 bytes
                shade::sdk::entity2::CEntityIOOutput m_InZone1; // 0x04c8, 0x18 bytes
                shade::sdk::entity2::CEntityIOOutput m_InZone2; // 0x04e0, 0x18 bytes
                shade::sdk::entity2::CEntityIOOutput m_InZone3; // 0x04f8, 0x18 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CLogicDistanceCheck) == 0x510, "CLogicDistanceCheck size mismatch");
        }
    }
}
