/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/CEntityIOOutput.hpp"
#include "shade/sdk/server/CLogicalEntity.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CBaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x518
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CLogicPlayerProxy : public shade::sdk::server::CLogicalEntity {
            public:
                shade::sdk::entity2::CEntityIOOutput m_PlayerHasAmmo; // 0x04a8, 0x18 bytes
                shade::sdk::entity2::CEntityIOOutput m_PlayerHasNoAmmo; // 0x04c0, 0x18 bytes
                shade::sdk::entity2::CEntityIOOutput m_PlayerDied; // 0x04d8, 0x18 bytes
                CEntityOutputTemplate<std::int32_t> m_RequestedPlayerHealth; // 0x04f0, 0x20 bytes
                CHandle<shade::sdk::server::CBaseEntity> m_hPlayer; // 0x0510, 0x4 bytes
                std::uint8_t pad_0514[0x4]; // 0x0514, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CLogicPlayerProxy) == 0x518, "CLogicPlayerProxy size mismatch");
        }
    }
}
