/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/WaypointFlags_t.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x30
             * Alignment: 0xff
             * Has Trivial Destructor
             */
            #pragma pack(push, 1)
            class CPathfindLocalData {
            public:
                VectorWS m_vLocalStart; // 0x0000, 0xc bytes
                VectorWS m_vLocalEnd; // 0x000c, 0xc bytes
                std::uint8_t pad_0018[0x8]; // 0x0018, 0x8 bytes
                shade::sdk::server::WaypointFlags_t m_nEndFlags; // 0x0020, 0x4 bytes
                std::int32_t m_nBuildFlags; // 0x0024, 0x4 bytes
                float m_flYaw; // 0x0028, 0x4 bytes
                std::uint8_t pad_002c[0x4]; // 0x002c, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CPathfindLocalData) == 0x30, "CPathfindLocalData size mismatch");
        }
    }
}
