/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CPhysicsProp.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0xd10
             * Alignment: 0x10
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CPhysicsPropMultiplayer : public shade::sdk::server::CPhysicsProp {
            public:
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CPhysicsPropMultiplayer) == 0xD10, "CPhysicsPropMultiplayer size mismatch");
        }
    }
}
