/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CBaseEntity.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x4c0
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CPlayerVisibility : public shade::sdk::server::CBaseEntity {
            public:
                float m_flVisibilityStrength; // 0x04a8, 0x4 bytes
                float m_flFogDistanceMultiplier; // 0x04ac, 0x4 bytes
                float m_flFogMaxDensityMultiplier; // 0x04b0, 0x4 bytes
                float m_flFadeTime; // 0x04b4, 0x4 bytes
                bool m_bStartDisabled; // 0x04b8, 0x1 bytes
                bool m_bIsEnabled; // 0x04b9, 0x1 bytes
                std::uint8_t pad_04ba[0x6]; // 0x04ba, 0x6 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * bool InputEnable; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             * bool InputDisable; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             * float InputSetPlayerVisibilityStrength; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             * float InputSetPlayerFogDistanceMultiplier; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             * float InputSetPlayerFogMaxDensityMultiplier; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             */

            static_assert(sizeof(CPlayerVisibility) == 0x4C0, "CPlayerVisibility size mismatch");
        }
    }
}
