/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CreatureAbilityType.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            class CBaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x34
             * Alignment: 0xff
             * Has Trivial Destructor
             */
            #pragma pack(push, 1)
            struct CreatureAbilityData_t {
                CHandle<shade::sdk::server::CBaseEntity> hAbility; // 0x0000, 0x4 bytes
                bool bIsDamage; // 0x0004, 0x1 bytes
                bool bIsDebuff; // 0x0005, 0x1 bytes
                bool bIsStun; // 0x0006, 0x1 bytes
                bool bIsAOE; // 0x0007, 0x1 bytes
                bool bIsLinear; // 0x0008, 0x1 bytes
                bool bUseOnCreeps; // 0x0009, 0x1 bytes
                bool bIsHeal; // 0x000a, 0x1 bytes
                bool bIsBuff; // 0x000b, 0x1 bytes
                bool bUseSelfishly; // 0x000c, 0x1 bytes
                bool bCanHelpOthersEscape; // 0x000d, 0x1 bytes
                bool bUseOnTrees; // 0x000e, 0x1 bytes
                bool bUseOnStrongestAlly; // 0x000f, 0x1 bytes
                std::int32_t nUseAtHealthPercent; // 0x0010, 0x4 bytes
                std::int32_t nRadius; // 0x0014, 0x4 bytes
                std::int32_t nMinimumTargets; // 0x0018, 0x4 bytes
                std::int32_t nMaximumTargets; // 0x001c, 0x4 bytes
                std::int32_t nMinimumHP; // 0x0020, 0x4 bytes
                std::int32_t nMinimumRange; // 0x0024, 0x4 bytes
                float flInitialCooldownMin; // 0x0028, 0x4 bytes
                float flInitialCooldownMax; // 0x002c, 0x4 bytes
                shade::sdk::server::CreatureAbilityType nAbilityType; // 0x0030, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CreatureAbilityData_t) == 0x34, "CreatureAbilityData_t size mismatch");
        }
    }
}
