/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/server/CSoundOpvarSetPointEntity.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x758
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CSoundOpvarSetDomeEntity : public shade::sdk::server::CSoundOpvarSetPointEntity {
            public:
                CUtlVector<Vector> m_arDirections; // 0x0638, 0x18 bytes
                CUtlVector<float> m_arOpenness; // 0x0650, 0x18 bytes
                CUtlVector<std::int32_t> m_arNeighbors; // 0x0668, 0x18 bytes
                std::int32_t m_nCurrentIndex; // 0x0680, 0x4 bytes
                std::uint8_t pad_0684[0x4]; // 0x0684, 0x4 bytes
                CUtlVector<std::int32_t> m_arClusterParent; // 0x0688, 0x18 bytes
                CUtlVector<std::int32_t> m_arClusterSize; // 0x06a0, 0x18 bytes
                CUtlVector<float> m_arClusterWeight; // 0x06b8, 0x18 bytes
                CUtlVector<Vector> m_arClusterDirSum; // 0x06d0, 0x18 bytes
                std::int32_t m_nClusterIndex; // 0x06e8, 0x4 bytes
                float m_flClusteredOpenness; // 0x06ec, 0x4 bytes
                Vector m_vClusterDirection; // 0x06f0, 0xc bytes
                Vector m_vSmoothedOpenDir; // 0x06fc, 0xc bytes
                std::int32_t m_nDirWarmupThinksRemaining; // 0x0708, 0x4 bytes
                VectorWS m_vLastTraceOrigin; // 0x070c, 0xc bytes
                bool m_bTraceOriginValid; // 0x0718, 0x1 bytes
                std::uint8_t pad_0719[0x3]; // 0x0719, 0x3 bytes
                std::int32_t m_nCatchUpThinksRemaining; // 0x071c, 0x4 bytes
                bool m_bDiscontinuityPending; // 0x0720, 0x1 bytes
                std::uint8_t pad_0721[0x3]; // 0x0721, 0x3 bytes
                float m_flSmoothedOpenness; // 0x0724, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flLastSmoothTime; // 0x0728, 0x4 bytes
                float m_flSize; // 0x072c, 0x4 bytes
                std::int32_t m_nTotalDirections; // 0x0730, 0x4 bytes
                std::int32_t m_nTracesPerFrame; // 0x0734, 0x4 bytes
                bool m_bDomeMode; // 0x0738, 0x1 bytes
                bool m_bMultiWall; // 0x0739, 0x1 bytes
                std::uint8_t pad_073a[0x2]; // 0x073a, 0x2 bytes
                float m_flWallTransmission; // 0x073c, 0x4 bytes
                std::int32_t m_nClusterK; // 0x0740, 0x4 bytes
                float m_flClusterP; // 0x0744, 0x4 bytes
                float m_flClusterBlend; // 0x0748, 0x4 bytes
                float m_flOpennessExponent; // 0x074c, 0x4 bytes
                float m_flShoulderExponent; // 0x0750, 0x4 bytes
                float m_flSmoothHalfLife; // 0x0754, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CSoundOpvarSetDomeEntity) == 0x758, "CSoundOpvarSetDomeEntity size mismatch");
        }
    }
}
