/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x10
             * Alignment: 0x8
             * Has Trivial Destructor
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            struct CTestPulseIO__FloatStringArgs_t {
                float flOutFloat; // 0x0000, 0x4 bytes
                std::uint8_t pad_0004[0x4]; // 0x0004, 0x4 bytes
                CUtlSymbolLarge strOutString; // 0x0008, 0x8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CTestPulseIO__FloatStringArgs_t) == 0x10, "CTestPulseIO__FloatStringArgs_t size mismatch");
        }
    }
}
