/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CBaseTrigger.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0xa28
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CTriggerTeamBase : public shade::sdk::server::CBaseTrigger {
            public:
                std::uint8_t pad_09f0[0x38]; // 0x09f0, 0x38 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CTriggerTeamBase) == 0xA28, "CTriggerTeamBase size mismatch");
        }
    }
}
