/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CBaseTrigger.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x8f8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CTriggerTeleport : public shade::sdk::server::CBaseTrigger {
            public:
                CUtlSymbolLarge m_iLandmark; // 0x08e8, 0x8 bytes
                bool m_bUseLandmarkAngles; // 0x08f0, 0x1 bytes
                bool m_bMirrorPlayer; // 0x08f1, 0x1 bytes
                bool m_bCheckDestIfClearForPlayer; // 0x08f2, 0x1 bytes
                std::uint8_t pad_08f3[0x5]; // 0x08f3, 0x5 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CTriggerTeleport) == 0x8F8, "CTriggerTeleport size mismatch");
        }
    }
}
