/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/CCSWeaponBase.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x1060
             * Alignment: 0xff
             * Has VTable
             * Construct Disallowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CWeaponBaseItem : public shade::sdk::server::CCSWeaponBase {
            public:
                bool m_bSequenceInProgress; // 0x1050, 0x1 bytes
                bool m_bRedraw; // 0x1051, 0x1 bytes
                std::uint8_t pad_1052[0xe]; // 0x1052, 0xe bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void; // Offset: 0x0, Size: 0x0, Size In Bytes: 0x0
             */

            static_assert(sizeof(CWeaponBaseItem) == 0x1060, "CWeaponBaseItem size mismatch");
        }
    }
}
