/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/server/dynpitchvol_base_t.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x64
             * Alignment: 0x4
             * Has Trivial Constructor
             * Has Trivial Destructor
             * Construct Allowed
             */
            #pragma pack(push, 1)
            struct dynpitchvol_t : public shade::sdk::server::dynpitchvol_base_t {
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(dynpitchvol_t) == 0x64, "dynpitchvol_t size mismatch");
        }
    }
}
