/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

namespace shade {
    namespace sdk {
        namespace server {
            enum class EBotTestNodeType : std::uint32_t {
                EBotTestNode_NotSet = 0x0,
                EBotTestNode_StandingMantleStart = 0x1,
                EBotTestNode_MovingMantleStart = 0x2,
                EBotTestNode_Dest = 0x4,
                EBotTestNode_ShootTarget = 0x8,
                EBotTestNode_TargetDummy = 0x10,
                EBotTestNode_GunDPSTest = 0x20
            };
        }
    }
}
