/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/ItemTradeRoundID_t.hpp"

namespace shade {
    namespace sdk {
        namespace server {
            struct ItemTradeOption_t;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace server {
            /* Class Parameters
             * Size: 0x78
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            struct ItemTradeRoundState_t {
                std::uint8_t pad_0000[0x8]; // 0x0000, 0x8 bytes
                CUtlVectorEmbeddedNetworkVar<shade::sdk::server::ItemTradeOption_t> m_vecOptions; // 0x0008, 0x68 bytes
                shade::sdk::client::ItemTradeRoundID_t m_nID; // 0x0070, 0x4 bytes
                std::int32_t m_nRerolls; // 0x0074, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(ItemTradeRoundState_t) == 0x78, "ItemTradeRoundState_t size mismatch");
        }
    }
}
