/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

namespace shade {
    namespace sdk {
        namespace server {
            enum class NavType_t : std::int32_t {
                AI_NAV_NONE = -0x1,
                AI_NAV_GROUND = 0x0,
                AI_NAV_JUMP = 0x1,
                AI_NAV_FLY = 0x2,
                AI_NAV_CLIMB = 0x3,
                AI_NAV_NAVLINK = 0x4,
                AI_NAV_TRANSITION = 0x5,
                AI_NAV_ORIENTED = 0x6
            };
        }
    }
}
