/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

namespace shade {
    namespace sdk {
        namespace resourcesystem {
            struct InfoForResourceTypeManifestTestResource_t;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace resourcesystem {
            /* Class Parameters
             * Size: 0x10
             * Alignment: 0x8
             * Construct Allowed
             */
            #pragma pack(push, 1)
            struct ManifestTestResource_t {
                CUtlString m_name; // 0x0000, 0x8 bytes
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeManifestTestResource_t> m_child; // 0x0008, 0x8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(ManifestTestResource_t) == 0x10, "ManifestTestResource_t size mismatch");
        }
    }
}
