/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

namespace shade {
    namespace sdk {
        namespace worldrenderer {
            struct EntityIOConnectionData_t;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace worldrenderer {
            /* Class Parameters
             * Size: 0x38
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             */
            #pragma pack(push, 1)
            struct EntityKeyValueData_t {
                std::uint8_t pad_0000[0x8]; // 0x0000, 0x8 bytes
                CUtlVector<shade::sdk::worldrenderer::EntityIOConnectionData_t> m_connections; // 0x0008, 0x18 bytes
                CUtlBinaryBlock m_keyValuesData; // 0x0020, 0x10 bytes
                std::uint8_t pad_0030[0x8]; // 0x0030, 0x8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(EntityKeyValueData_t) == 0x38, "EntityKeyValueData_t size mismatch");
        }
    }
}
