/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/soundsystem_lowlevel/CVMixBaseProcessorDesc.hpp"

namespace shade {
    namespace sdk {
        namespace soundsystem_lowlevel {
            /* Class Parameters
             * Size: 0x20
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class CVMixStereoDelayProcessorDesc : public shade::sdk::soundsystem_lowlevel::CVMixBaseProcessorDesc {
            public:
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CVMixStereoDelayProcessorDesc) == 0x20, "CVMixStereoDelayProcessorDesc size mismatch");
        }
    }
}
