/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

namespace shade {
    namespace sdk {
        namespace soundsystem_lowlevel {
            /* Class Parameters
             * Size: 0x10
             * Alignment: 0x4
             * Has Trivial Constructor
             * Has Trivial Destructor
             * Construct Allowed
             */
            #pragma pack(push, 1)
            struct VMixDiffusorDesc_t {
                float m_flSize; // 0x0000, 0x4 bytes
                float m_flComplexity; // 0x0004, 0x4 bytes
                float m_flFeedback; // 0x0008, 0x4 bytes
                float m_flOutputGain; // 0x000c, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(VMixDiffusorDesc_t) == 0x10, "VMixDiffusorDesc_t size mismatch");
        }
    }
}
