/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

namespace shade {
    namespace sdk {
        namespace physicslib {
            /* Class Parameters
             * Size: 0x90
             * Alignment: 0x8
             * Construct Allowed
             */
            #pragma pack(push, 1)
            struct FeMorphLayerDepr_t {
                CUtlString m_Name; // 0x0000, 0x8 bytes
                std::uint32_t m_nNameHash; // 0x0008, 0x4 bytes
                std::uint8_t pad_000c[0x4]; // 0x000c, 0x4 bytes
                CUtlVector<std::uint16_t> m_Nodes; // 0x0010, 0x18 bytes
                CUtlVector<Vector> m_InitPos; // 0x0028, 0x18 bytes
                CUtlVector<float> m_Gravity; // 0x0040, 0x18 bytes
                CUtlVector<float> m_GoalStrength; // 0x0058, 0x18 bytes
                CUtlVector<float> m_GoalDamping; // 0x0070, 0x18 bytes
                std::uint32_t m_nFlags; // 0x0088, 0x4 bytes
                std::uint8_t pad_008c[0x4]; // 0x008c, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(FeMorphLayerDepr_t) == 0x90, "FeMorphLayerDepr_t size mismatch");
        }
    }
}
