/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/modellib/AnimNodeID.hpp"

namespace shade {
    namespace sdk {
        namespace animgraphlib {
            /* Class Parameters
             * Size: 0x30
             * Alignment: 0x4
             * Has Trivial Destructor
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class CAnimNodePath {
            public:
                shade::sdk::modellib::AnimNodeID m_path[0xb]; // 0x0000, 0x2c bytes
                std::int32_t m_nCount; // 0x002c, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CAnimNodePath) == 0x30, "CAnimNodePath size mismatch");
        }
    }
}
