/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/animgraphlib/AnimNodeNetworkMode.hpp"
#include "shade/sdk/animgraphlib/CAnimNodePath.hpp"

namespace shade {
    namespace sdk {
        namespace animgraphlib {
            /* Class Parameters
             * Size: 0x58
             * Alignment: 0xff
             * Has VTable
             * Abstract Class
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class CAnimUpdateNodeBase {
            public:
                std::uint8_t pad_0000[0x18]; // 0x0000, 0x18 bytes
                shade::sdk::animgraphlib::CAnimNodePath m_nodePath; // 0x0018, 0x30 bytes
                shade::sdk::animgraphlib::AnimNodeNetworkMode m_networkMode; // 0x0048, 0x4 bytes
                std::uint8_t pad_004c[0x4]; // 0x004c, 0x4 bytes
                CUtlString m_name; // 0x0050, 0x8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CAnimUpdateNodeBase) == 0x58, "CAnimUpdateNodeBase size mismatch");
        }
    }
}
