/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/animgraphlib/CMotionMetricEvaluator.hpp"

namespace shade {
    namespace sdk {
        namespace animgraphlib {
            /* Class Parameters
             * Size: 0x68
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class CDistanceRemainingMetricEvaluator : public shade::sdk::animgraphlib::CMotionMetricEvaluator {
            public:
                float m_flMaxDistance; // 0x0050, 0x4 bytes
                float m_flMinDistance; // 0x0054, 0x4 bytes
                float m_flStartGoalFilterDistance; // 0x0058, 0x4 bytes
                float m_flMaxGoalOvershootScale; // 0x005c, 0x4 bytes
                bool m_bFilterFixedMinDistance; // 0x0060, 0x1 bytes
                bool m_bFilterGoalDistance; // 0x0061, 0x1 bytes
                bool m_bFilterGoalOvershoot; // 0x0062, 0x1 bytes
                std::uint8_t pad_0063[0x5]; // 0x0063, 0x5 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDistanceRemainingMetricEvaluator) == 0x68, "CDistanceRemainingMetricEvaluator size mismatch");
        }
    }
}
