/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

namespace shade {
    namespace sdk {
        namespace animgraphlib {
            /* Class Parameters
             * Size: 0x48
             * Alignment: 0x4
             * Has Trivial Destructor
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class CFootAdjustmentInstanceData {
            public:
                std::uint8_t pad_0000[0xc]; // 0x0000, 0xc bytes
                CAnimNetVar<float> m_flStartTime; // 0x000c, 0xc bytes
                CAnimNetVar<float> m_flDuration; // 0x0018, 0xc bytes
                std::uint8_t pad_0024[0x18]; // 0x0024, 0x18 bytes
                float m_flStartHeadingWS; // 0x003c, 0x4 bytes
                std::uint8_t pad_0040[0x8]; // 0x0040, 0x8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CFootAdjustmentInstanceData) == 0x48, "CFootAdjustmentInstanceData size mismatch");
        }
    }
}
