/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/animationsystem/ParticleAttachment_t.hpp"
#include "shade/sdk/animgraphlib/CAnimTagBase.hpp"

namespace shade {
    namespace sdk {
        namespace resourcesystem {
            class InfoForResourceTypeIParticleSystemDefinition;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace animgraphlib {
            /* Class Parameters
             * Size: 0x98
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class CParticleAnimTag : public shade::sdk::animgraphlib::CAnimTagBase {
            public:
                std::uint8_t pad_0050[0x8]; // 0x0050, 0x8 bytes
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition> m_hParticleSystem; // 0x0058, 0x8 bytes
                CUtlString m_particleSystemName; // 0x0060, 0x8 bytes
                CUtlString m_configName; // 0x0068, 0x8 bytes
                bool m_bDetachFromOwner; // 0x0070, 0x1 bytes
                bool m_bAggregate; // 0x0071, 0x1 bytes
                bool m_bStopWhenTagEnds; // 0x0072, 0x1 bytes
                bool m_bTagEndStopIsInstant; // 0x0073, 0x1 bytes
                std::uint8_t pad_0074[0x4]; // 0x0074, 0x4 bytes
                CUtlString m_attachmentName; // 0x0078, 0x8 bytes
                shade::sdk::animationsystem::ParticleAttachment_t m_attachmentType; // 0x0080, 0x4 bytes
                std::uint8_t pad_0084[0x4]; // 0x0084, 0x4 bytes
                CUtlString m_attachmentCP1Name; // 0x0088, 0x8 bytes
                shade::sdk::animationsystem::ParticleAttachment_t m_attachmentCP1Type; // 0x0090, 0x4 bytes
                std::uint8_t pad_0094[0x4]; // 0x0094, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CParticleAnimTag) == 0x98, "CParticleAnimTag size mismatch");
        }
    }
}
