/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/animgraphlib/CUnaryUpdateNode.hpp"
#include "shade/sdk/animgraphlib/RagdollPoseControl.hpp"

namespace shade {
    namespace sdk {
        namespace animgraphlib {
            /* Class Parameters
             * Size: 0x78
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class CRagdollUpdateNode : public shade::sdk::animgraphlib::CUnaryUpdateNode {
            public:
                std::int32_t m_nWeightListIndex; // 0x0070, 0x4 bytes
                shade::sdk::animgraphlib::RagdollPoseControl m_poseControlMethod; // 0x0074, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CRagdollUpdateNode) == 0x78, "CRagdollUpdateNode size mismatch");
        }
    }
}
