/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

namespace shade {
    namespace sdk {
        namespace animgraphlib {
            /* Class Parameters
             * Size: 0x30
             * Alignment: 0xff
             * Has Trivial Destructor
             * Construct Allowed
             * Construct Disallowed
             */
            #pragma pack(push, 1)
            struct TargetSelectorInstanceData_t {
                CAnimNetVar<std::int32_t> m_currentIndex; // 0x0000, 0xc bytes
                std::uint8_t pad_000c[0x10]; // 0x000c, 0x10 bytes
                CAnimNetVar<Vector> m_vMSRootMotionAnlyzerTarget; // 0x001c, 0x14 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(TargetSelectorInstanceData_t) == 0x30, "TargetSelectorInstanceData_t size mismatch");
        }
    }
}
