/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            struct AI_MotorServices_DebugSnapshotData_t__MotorPathWaypoint_t;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x30
             * Alignment: 0x8
             * Construct Allowed
             */
            #pragma pack(push, 1)
            struct AI_MotorServices_DebugSnapshotData_t {
                CGlobalSymbol active_motor; // 0x0000, 0x8 bytes
                float desired_speed; // 0x0008, 0x4 bytes
                Vector motor_velocity; // 0x000c, 0xc bytes
                CUtlVector<shade::sdk::client::AI_MotorServices_DebugSnapshotData_t__MotorPathWaypoint_t> motor_path; // 0x0018, 0x18 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(AI_MotorServices_DebugSnapshotData_t) == 0x30, "AI_MotorServices_DebugSnapshotData_t size mismatch");
        }
    }
}
