/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_BaseModelEntity.hpp"
#include "shade/sdk/entity2/CEntityIOOutput.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"

namespace shade {
    namespace sdk {
        namespace resourcesystem {
            class InfoForResourceTypeCTextureBase;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x13a8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class C_BarnLight : public shade::sdk::client::C_BaseModelEntity {
            public:
                bool m_bEnabled; // 0x1098, 0x1 bytes
                std::uint8_t pad_1099[0x3]; // 0x1099, 0x3 bytes
                std::int32_t m_nColorMode; // 0x109c, 0x4 bytes
                Color m_Color; // 0x10a0, 0x4 bytes
                float m_flColorTemperature; // 0x10a4, 0x4 bytes
                float m_flBrightness; // 0x10a8, 0x4 bytes
                float m_flBrightnessScale; // 0x10ac, 0x4 bytes
                std::int32_t m_nDirectLight; // 0x10b0, 0x4 bytes
                std::int32_t m_nBakedShadowIndex; // 0x10b4, 0x4 bytes
                std::int32_t m_nLightPathUniqueId; // 0x10b8, 0x4 bytes
                std::int32_t m_nLightMapUniqueId; // 0x10bc, 0x4 bytes
                std::int32_t m_nLuminaireShape; // 0x10c0, 0x4 bytes
                float m_flLuminaireSize; // 0x10c4, 0x4 bytes
                float m_flLuminaireAnisotropy; // 0x10c8, 0x4 bytes
                std::uint8_t pad_10cc[0x4]; // 0x10cc, 0x4 bytes
                CUtlString m_LightStyleString; // 0x10d0, 0x8 bytes
                shade::sdk::entity2::GameTime_t m_flLightStyleStartTime; // 0x10d8, 0x4 bytes
                std::uint8_t pad_10dc[0x4]; // 0x10dc, 0x4 bytes
                C_NetworkUtlVectorBase<CUtlString> m_QueuedLightStyleStrings; // 0x10e0, 0x18 bytes
                C_NetworkUtlVectorBase<CUtlString> m_LightStyleEvents; // 0x10f8, 0x18 bytes
                C_NetworkUtlVectorBase<CHandle<shade::sdk::client::C_BaseModelEntity>> m_LightStyleTargets; // 0x1110, 0x18 bytes
                shade::sdk::entity2::CEntityIOOutput m_StyleEvent[0x4]; // 0x1128, 0x60 bytes
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeCTextureBase> m_hLightCookie; // 0x1188, 0x8 bytes
                float m_flShape; // 0x1190, 0x4 bytes
                float m_flSoftX; // 0x1194, 0x4 bytes
                float m_flSoftY; // 0x1198, 0x4 bytes
                float m_flSkirt; // 0x119c, 0x4 bytes
                float m_flSkirtNear; // 0x11a0, 0x4 bytes
                Vector m_vSizeParams; // 0x11a4, 0xc bytes
                float m_flRange; // 0x11b0, 0x4 bytes
                Vector m_vShear; // 0x11b4, 0xc bytes
                std::int32_t m_nBakeSpecularToCubemaps; // 0x11c0, 0x4 bytes
                Vector m_vBakeSpecularToCubemapsSize; // 0x11c4, 0xc bytes
                float m_flBakeSpecularToCubemapsScale; // 0x11d0, 0x4 bytes
                std::int32_t m_nCastShadows; // 0x11d4, 0x4 bytes
                std::int32_t m_nShadowMapSize; // 0x11d8, 0x4 bytes
                std::int32_t m_nShadowPriority; // 0x11dc, 0x4 bytes
                bool m_bContactShadow; // 0x11e0, 0x1 bytes
                bool m_bForceShadowsEnabled; // 0x11e1, 0x1 bytes
                std::uint8_t pad_11e2[0x2]; // 0x11e2, 0x2 bytes
                std::int32_t m_nBounceLight; // 0x11e4, 0x4 bytes
                float m_flBounceScale; // 0x11e8, 0x4 bytes
                float m_flMinRoughness; // 0x11ec, 0x4 bytes
                Vector m_vAlternateColor; // 0x11f0, 0xc bytes
                float m_fAlternateColorBrightness; // 0x11fc, 0x4 bytes
                std::int32_t m_nFog; // 0x1200, 0x4 bytes
                float m_flFogStrength; // 0x1204, 0x4 bytes
                std::int32_t m_nFogShadows; // 0x1208, 0x4 bytes
                float m_flFogScale; // 0x120c, 0x4 bytes
                float m_flFadeSizeStart; // 0x1210, 0x4 bytes
                float m_flFadeSizeEnd; // 0x1214, 0x4 bytes
                float m_flShadowFadeSizeStart; // 0x1218, 0x4 bytes
                float m_flShadowFadeSizeEnd; // 0x121c, 0x4 bytes
                bool m_bPrecomputedFieldsValid; // 0x1220, 0x1 bytes
                std::uint8_t pad_1221[0x3]; // 0x1221, 0x3 bytes
                Vector m_vPrecomputedBoundsMins; // 0x1224, 0xc bytes
                Vector m_vPrecomputedBoundsMaxs; // 0x1230, 0xc bytes
                Vector m_vPrecomputedOBBOrigin; // 0x123c, 0xc bytes
                QAngle m_vPrecomputedOBBAngles; // 0x1248, 0xc bytes
                Vector m_vPrecomputedOBBExtent; // 0x1254, 0xc bytes
                std::int32_t m_nPrecomputedSubFrusta; // 0x1260, 0x4 bytes
                Vector m_vPrecomputedOBBOrigin0; // 0x1264, 0xc bytes
                QAngle m_vPrecomputedOBBAngles0; // 0x1270, 0xc bytes
                Vector m_vPrecomputedOBBExtent0; // 0x127c, 0xc bytes
                Vector m_vPrecomputedOBBOrigin1; // 0x1288, 0xc bytes
                QAngle m_vPrecomputedOBBAngles1; // 0x1294, 0xc bytes
                Vector m_vPrecomputedOBBExtent1; // 0x12a0, 0xc bytes
                Vector m_vPrecomputedOBBOrigin2; // 0x12ac, 0xc bytes
                QAngle m_vPrecomputedOBBAngles2; // 0x12b8, 0xc bytes
                Vector m_vPrecomputedOBBExtent2; // 0x12c4, 0xc bytes
                Vector m_vPrecomputedOBBOrigin3; // 0x12d0, 0xc bytes
                QAngle m_vPrecomputedOBBAngles3; // 0x12dc, 0xc bytes
                Vector m_vPrecomputedOBBExtent3; // 0x12e8, 0xc bytes
                Vector m_vPrecomputedOBBOrigin4; // 0x12f4, 0xc bytes
                QAngle m_vPrecomputedOBBAngles4; // 0x1300, 0xc bytes
                Vector m_vPrecomputedOBBExtent4; // 0x130c, 0xc bytes
                Vector m_vPrecomputedOBBOrigin5; // 0x1318, 0xc bytes
                QAngle m_vPrecomputedOBBAngles5; // 0x1324, 0xc bytes
                Vector m_vPrecomputedOBBExtent5; // 0x1330, 0xc bytes
                std::uint8_t pad_133c[0x44]; // 0x133c, 0x44 bytes
                bool m_bInitialBoneSetup; // 0x1380, 0x1 bytes
                std::uint8_t pad_1381[0x7]; // 0x1381, 0x7 bytes
                C_NetworkUtlVectorBase<std::uint16_t> m_VisClusters; // 0x1388, 0x18 bytes
                std::uint8_t pad_13a0[0x8]; // 0x13a0, 0x8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_BarnLight) == 0x13A8, "C_BarnLight size mismatch");
        }
    }
}
