/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CAnimGraphControllerBase.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x130
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class C_Citadel_BreakableProp_GraphController : public shade::sdk::client::CAnimGraphControllerBase {
            public:
                CAnimGraphParamRef<bool> m_bSetInit; // 0x0090, 0x28 bytes
                CAnimGraphParamRef<float> m_flDamageReceived; // 0x00b8, 0x28 bytes
                CAnimGraphParamRef<bool> m_bOnRespawn; // 0x00e0, 0x28 bytes
                CAnimGraphParamRef<bool> m_bHitTrigger; // 0x0108, 0x28 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_Citadel_BreakableProp_GraphController) == 0x130, "C_Citadel_BreakableProp_GraphController size mismatch");
        }
    }
}
