/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CStreetBrawlController.hpp"
#include "shade/sdk/client/C_TeamplayRules.hpp"
#include "shade/sdk/client/ECitadelGameMode.hpp"
#include "shade/sdk/client/ECitadelMatchMode.hpp"
#include "shade/sdk/client/EGameState.hpp"
#include "shade/sdk/client/MatchID_t.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class CCitadelPlayOfTheGame;
            class CCitadelTrooperMinimap;
            class C_BaseEntity;
            struct HeroID_t;
            struct TeamKothState_t;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0xa0d8
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class C_CitadelGameRules : public shade::sdk::client::C_TeamplayRules {
            public:
                std::uint8_t pad_0040[0x18]; // 0x0040, 0x18 bytes
                bool m_bFreezePeriod; // 0x0058, 0x1 bytes
                std::uint8_t pad_0059[0x3]; // 0x0059, 0x3 bytes
                shade::sdk::entity2::GameTime_t m_fLevelStartTime; // 0x005c, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flGameStartTime; // 0x0060, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flGameStateStartTime; // 0x0064, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flGameStateEndTime; // 0x0068, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flRoundStartTime; // 0x006c, 0x4 bytes
                float m_flPlayOfTheGameStateEndTime; // 0x0070, 0x4 bytes
                shade::sdk::client::EGameState m_eGameState; // 0x0074, 0x4 bytes
                CHandle<shade::sdk::client::C_BaseEntity> m_hTowerAmber; // 0x0078, 0x4 bytes
                CHandle<shade::sdk::client::C_BaseEntity> m_hTowerSapphire; // 0x007c, 0x4 bytes
                bool m_bEnemyInAmberBase; // 0x0080, 0x1 bytes
                bool m_bEnemyInSapphireBase; // 0x0081, 0x1 bytes
                bool m_bEnemyPlayersInAmberBase; // 0x0082, 0x1 bytes
                bool m_bEnemyPlayersInSapphireBase; // 0x0083, 0x1 bytes
                VectorWS m_vMinimapMins; // 0x0084, 0xc bytes
                VectorWS m_vMinimapMaxs; // 0x0090, 0xc bytes
                bool m_bMatchSafeToAbandon; // 0x009c, 0x1 bytes
                bool m_bMatchNotScored; // 0x009d, 0x1 bytes
                std::uint8_t pad_009e[0x2]; // 0x009e, 0x2 bytes
                shade::sdk::entity2::GameTime_t m_tAbandonTriggerEarlyTime; // 0x00a0, 0x4 bytes
                bool m_bAbandonTriggerSapphire; // 0x00a4, 0x1 bytes
                bool m_bAbandonTriggerAmber; // 0x00a5, 0x1 bytes
                std::uint8_t pad_00a6[0x2]; // 0x00a6, 0x2 bytes
                shade::sdk::client::ECitadelMatchMode m_eMatchMode; // 0x00a8, 0x4 bytes
                shade::sdk::client::ECitadelGameMode m_eGameMode; // 0x00ac, 0x4 bytes
                std::uint32_t m_unSpectatorCount; // 0x00b0, 0x4 bytes
                std::uint32_t m_unExpectedPlayerCount; // 0x00b4, 0x4 bytes
                std::uint32_t m_nHideoutOwner; // 0x00b8, 0x4 bytes
                CHandle<shade::sdk::client::CCitadelTrooperMinimap> m_hTrooperMinimap; // 0x00bc, 0x4 bytes
                std::int32_t m_iWinningTeam; // 0x00c0, 0x4 bytes
                std::uint8_t pad_00c4[0x4]; // 0x00c4, 0x4 bytes
                C_NetworkUtlVectorBase<shade::sdk::client::HeroID_t> m_vecBannedHeroes; // 0x00c8, 0x18 bytes
                std::uint32_t m_nCorruptedPenaltySeed; // 0x00e0, 0x4 bytes
                std::int32_t m_nNumCorruptedItemsLimit; // 0x00e4, 0x4 bytes
                C_UtlVectorEmbeddedNetworkVar<shade::sdk::client::TeamKothState_t> m_vecTeamKothStates; // 0x00e8, 0x108 bytes
                std::int32_t m_nKothScoringTeam; // 0x01f0, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_timeKothScoring; // 0x01f4, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_timeKothCashInStarted; // 0x01f8, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_timeKothGiveUp; // 0x01fc, 0x4 bytes
                std::int32_t m_nAmberGold; // 0x0200, 0x4 bytes
                std::int32_t m_nSapphireGold; // 0x0204, 0x4 bytes
                VectorWS m_vKothCashInCurrentLocation; // 0x0208, 0xc bytes
                CHandle<shade::sdk::client::C_BaseEntity> m_hCurrentHeroDrafterRebels; // 0x0214, 0x4 bytes
                CHandle<shade::sdk::client::C_BaseEntity> m_hCurrentHeroDrafterCombine; // 0x0218, 0x4 bytes
                bool m_bDontUploadStats; // 0x021c, 0x1 bytes
                std::uint8_t pad_021d[0x3]; // 0x021d, 0x3 bytes
                std::int32_t m_iMidbossKillCount; // 0x0220, 0x4 bytes
                std::int32_t m_iAmberRejuvCount; // 0x0224, 0x4 bytes
                std::int32_t m_iSapphireRejuvCount; // 0x0228, 0x4 bytes
                float m_tNextMidBossSpawnTime; // 0x022c, 0x4 bytes
                C_NetworkUtlVectorBase<VectorWS> m_vecNeutralCampTimerOrigins; // 0x0230, 0x18 bytes
                C_NetworkUtlVectorBase<float> m_vecNeutralCampNextSpawnTimes; // 0x0248, 0x18 bytes
                C_NetworkUtlVectorBase<bool> m_vecNeutralCampTimerIsMidBoss; // 0x0260, 0x18 bytes
                std::uint8_t pad_0278[0x9d58]; // 0x0278, 0x9d58 bytes
                bool m_bServerPaused; // 0x9fd0, 0x1 bytes
                std::uint8_t pad_9fd1[0x3]; // 0x9fd1, 0x3 bytes
                std::int32_t m_iPauseTeam; // 0x9fd4, 0x4 bytes
                std::int32_t m_nMatchClockUpdateTick; // 0x9fd8, 0x4 bytes
                float m_flMatchClockAtLastUpdate; // 0x9fdc, 0x4 bytes
                double m_flPauseTime; // 0x9fe0, 0x8 bytes
                CPlayerSlot m_pausingPlayerId; // 0x9fe8, 0x4 bytes
                CPlayerSlot m_unpausingPlayerId; // 0x9fec, 0x4 bytes
                float m_fPauseRawTime; // 0x9ff0, 0x4 bytes
                float m_fPauseCurTime; // 0x9ff4, 0x4 bytes
                float m_fUnpauseRawTime; // 0x9ff8, 0x4 bytes
                float m_fUnpauseCurTime; // 0x9ffc, 0x4 bytes
                std::uint8_t pad_a000[0x50]; // 0xa000, 0x50 bytes
                std::int32_t m_nLastPreGameCount; // 0xa050, 0x4 bytes
                std::int32_t m_eGGTeam; // 0xa054, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flGGEndsAtTime; // 0xa058, 0x4 bytes
                bool m_bGGMarkAsNotScored; // 0xa05c, 0x1 bytes
                std::uint8_t pad_a05d[0x3]; // 0xa05d, 0x3 bytes
                shade::sdk::client::MatchID_t m_unMatchID; // 0xa060, 0x8 bytes
                CUtlString m_sGameplayExperiment; // 0xa068, 0x8 bytes
                std::uint32_t m_ExperimentTokenHashCode; // 0xa070, 0x4 bytes
                std::int32_t m_nPlayerDeathEventID; // 0xa074, 0x4 bytes
                std::int32_t m_nReplayChangedEvent; // 0xa078, 0x4 bytes
                std::int32_t m_nGameOverEvent; // 0xa07c, 0x4 bytes
                std::uint8_t pad_a080[0x20]; // 0xa080, 0x20 bytes
                shade::sdk::entity2::GameTime_t m_flHeroDiedTime; // 0xa0a0, 0x4 bytes
                std::uint8_t pad_a0a4[0x4]; // 0xa0a4, 0x4 bytes
                shade::sdk::client::CCitadelPlayOfTheGame *m_pPlayOfTheGame; // 0xa0a8, 0x8 bytes
                shade::sdk::client::CStreetBrawlController m_tStreetBrawl; // 0xa0b0, 0x28 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_CitadelGameRules) == 0xA0D8, "C_CitadelGameRules size mismatch");
        }
    }
}
