/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CBaseAnimGraph.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0xcb8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class C_Citadel_PickupItemSpawner : public shade::sdk::client::CBaseAnimGraph {
            public:
                std::uint8_t pad_0ca8[0x8]; // 0x0ca8, 0x8 bytes
                shade::sdk::entity2::GameTime_t m_tNextDropTime; // 0x0cb0, 0x4 bytes
                bool m_bPowerupActive; // 0x0cb4, 0x1 bytes
                std::uint8_t pad_0cb5[0x3]; // 0x0cb5, 0x3 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_Citadel_PickupItemSpawner) == 0xCB8, "C_Citadel_PickupItemSpawner size mismatch");
        }
    }
}
