/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_CSWeaponBase.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x1f40
             * Alignment: 0x10
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class C_CSWeaponBaseGun : public shade::sdk::client::C_CSWeaponBase {
            public:
                std::int32_t m_zoomLevel; // 0x1f10, 0x4 bytes
                std::int32_t m_iBurstShotsRemaining; // 0x1f14, 0x4 bytes
                std::int32_t m_iSilencerBodygroup; // 0x1f18, 0x4 bytes
                std::uint8_t pad_1f1c[0xc]; // 0x1f1c, 0xc bytes
                std::int32_t m_silencedModelIndex; // 0x1f28, 0x4 bytes
                bool m_inPrecache; // 0x1f2c, 0x1 bytes
                bool m_bNeedsBoltAction; // 0x1f2d, 0x1 bytes
                std::uint8_t pad_1f2e[0x2]; // 0x1f2e, 0x2 bytes
                std::int32_t m_nRevolverCylinderIdx; // 0x1f30, 0x4 bytes
                std::uint8_t pad_1f34[0xc]; // 0x1f34, 0xc bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_CSWeaponBaseGun) == 0x1F40, "C_CSWeaponBaseGun size mismatch");
        }
    }
}
