/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_DOTABaseAbility.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x6b0
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class C_DOTA_Ability_PrimalBeast_Uproar : public shade::sdk::client::C_DOTABaseAbility {
            public:
                std::int32_t m_iUproarStatus; // 0x06a8, 0x4 bytes
                bool m_bUpdateIcons; // 0x06ac, 0x1 bytes
                std::uint8_t pad_06ad[0x3]; // 0x06ad, 0x3 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void; // Offset: 0x0, Size: 0x0, Size In Bytes: 0x0
             */

            static_assert(sizeof(C_DOTA_Ability_PrimalBeast_Uproar) == 0x6B0, "C_DOTA_Ability_PrimalBeast_Uproar size mismatch");
        }
    }
}
