/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CountdownTimer.hpp"
#include "shade/sdk/entity2/CNetworkVarChainer.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class sPlayerSnapshot;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x9f8
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class C_DOTASpectatorGraphManager {
            public:
                std::uint8_t pad_0000[0x28]; // 0x0000, 0x28 bytes
                shade::sdk::entity2::CNetworkVarChainer __m_pChainEntity; // 0x0028, 0x28 bytes
                bool m_bTrackingTeamStats; // 0x0050, 0x1 bytes
                std::uint8_t pad_0051[0x3]; // 0x0051, 0x3 bytes
                shade::sdk::entity2::GameTime_t m_flStartTime; // 0x0054, 0x4 bytes
                std::int32_t m_rgRadiantTotalEarnedGold[0x40]; // 0x0058, 0x100 bytes
                std::int32_t m_rgDireTotalEarnedGold[0x40]; // 0x0158, 0x100 bytes
                std::int32_t m_rgRadiantTotalEarnedXP[0x40]; // 0x0258, 0x100 bytes
                std::int32_t m_rgDireTotalEarnedXP[0x40]; // 0x0358, 0x100 bytes
                std::int32_t m_rgRadiantNetWorth[0x40]; // 0x0458, 0x100 bytes
                std::int32_t m_rgDireNetWorth[0x40]; // 0x0558, 0x100 bytes
                shade::sdk::entity2::GameTime_t m_flTotalEarnedGoldStartTime; // 0x0658, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flTotalEarnedGoldEndTime; // 0x065c, 0x4 bytes
                std::int32_t m_nGoldGraphVersion; // 0x0660, 0x4 bytes
                std::int32_t m_rgRadiantWinChance[0x40]; // 0x0664, 0x100 bytes
                std::uint8_t pad_0764[0x4]; // 0x0764, 0x4 bytes
                shade::sdk::client::CountdownTimer m_TeamStatsUpdateTimer; // 0x0768, 0x18 bytes
                shade::sdk::client::CountdownTimer m_HeroInventorySnapshotTimer; // 0x0780, 0x18 bytes
                CUtlVector<shade::sdk::client::sPlayerSnapshot> m_vecPlayerSnapshots[0x18]; // 0x0798, 0x240 bytes
                std::uint8_t pad_09d8[0x18]; // 0x09d8, 0x18 bytes
                std::uint32_t m_unDataChangedCount; // 0x09f0, 0x4 bytes
                std::uint8_t pad_09f4[0x4]; // 0x09f4, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_DOTASpectatorGraphManager) == 0x9F8, "C_DOTASpectatorGraphManager size mismatch");
        }
    }
}
