/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CBaseAnimatingActivity.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0xd90
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class C_DOTA_Item_Rune : public shade::sdk::client::CBaseAnimatingActivity {
            public:
                std::uint8_t pad_0ac0[0x18]; // 0x0ac0, 0x18 bytes
                std::int32_t m_iRuneType; // 0x0ad8, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flRuneTime; // 0x0adc, 0x4 bytes
                std::int32_t m_nMapLocationTeam; // 0x0ae0, 0x4 bytes
                char m_szLocation[0x200]; // 0x0ae4, 0x200 bytes
                std::int32_t m_iOldRuneType; // 0x0ce4, 0x4 bytes
                bool m_bShowingTooltip; // 0x0ce8, 0x1 bytes
                std::uint8_t pad_0ce9[0xa7]; // 0x0ce9, 0xa7 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void; // Offset: 0x0, Size: 0x0, Size In Bytes: 0x0
             */

            static_assert(sizeof(C_DOTA_Item_Rune) == 0xD90, "C_DOTA_Item_Rune size mismatch");
        }
    }
}
