/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_DOTABaseAbility.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x6b8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class C_DOTA_Ability_Largo_AmphibianRhapsody_Song : public shade::sdk::client::C_DOTABaseAbility {
            public:
                std::int32_t double_song; // 0x06a8, 0x4 bytes
                float song_cost_reduction_per_stack; // 0x06ac, 0x4 bytes
                bool m_bInRhythmTiming; // 0x06b0, 0x1 bytes
                std::uint8_t pad_06b1[0x7]; // 0x06b1, 0x7 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void; // Offset: 0x0, Size: 0x0, Size In Bytes: 0x0
             */

            static_assert(sizeof(C_DOTA_Ability_Largo_AmphibianRhapsody_Song) == 0x6B8, "C_DOTA_Ability_Largo_AmphibianRhapsody_Song size mismatch");
        }
    }
}
