/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_DOTABaseAbility.hpp"
#include "shade/sdk/client/CountdownTimer.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x700
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class C_DOTA_Ability_Nian_Roar : public shade::sdk::client::C_DOTABaseAbility {
            public:
                std::int32_t base_projectiles; // 0x06a8, 0x4 bytes
                std::int32_t max_projectiles; // 0x06ac, 0x4 bytes
                std::int32_t projectile_step; // 0x06b0, 0x4 bytes
                std::int32_t base_speed; // 0x06b4, 0x4 bytes
                std::int32_t speed_step; // 0x06b8, 0x4 bytes
                std::int32_t initial_radius; // 0x06bc, 0x4 bytes
                std::int32_t end_radius; // 0x06c0, 0x4 bytes
                std::int32_t damage; // 0x06c4, 0x4 bytes
                float base_interval; // 0x06c8, 0x4 bytes
                float interval_step; // 0x06cc, 0x4 bytes
                std::int32_t m_nCastCount; // 0x06d0, 0x4 bytes
                std::int32_t m_nProjectiles; // 0x06d4, 0x4 bytes
                std::int32_t m_nWaveCount; // 0x06d8, 0x4 bytes
                std::uint8_t pad_06dc[0x4]; // 0x06dc, 0x4 bytes
                shade::sdk::client::CountdownTimer m_ctTimer; // 0x06e0, 0x18 bytes
                float m_flTiming; // 0x06f8, 0x4 bytes
                bool m_bScriptRoar; // 0x06fc, 0x1 bytes
                std::uint8_t pad_06fd[0x3]; // 0x06fd, 0x3 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void; // Offset: 0x0, Size: 0x0, Size In Bytes: 0x0
             */

            static_assert(sizeof(C_DOTA_Ability_Nian_Roar) == 0x700, "C_DOTA_Ability_Nian_Roar size mismatch");
        }
    }
}
