/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_DOTA_BaseNPC_Building.hpp"
#include "shade/sdk/client/DOTA_SHOP_TYPE.hpp"
#include "shade/sdk/client/ParticleIndex_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x1b68
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class C_DOTA_BaseNPC_Shop : public shade::sdk::client::C_DOTA_BaseNPC_Building {
            public:
                shade::sdk::client::DOTA_SHOP_TYPE m_ShopType; // 0x1b28, 0x4 bytes
                std::uint8_t pad_1b2c[0x24]; // 0x1b2c, 0x24 bytes
                shade::sdk::client::ParticleIndex_t m_nShopFX; // 0x1b50, 0x4 bytes
                VectorWS m_vShopFXOrigin; // 0x1b54, 0xc bytes
                float m_flLastSpeech; // 0x1b60, 0x4 bytes
                std::uint8_t pad_1b64[0x4]; // 0x1b64, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_DOTA_BaseNPC_Shop) == 0x1B68, "C_DOTA_BaseNPC_Shop size mismatch");
        }
    }
}
