/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_EconEntity.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x1920
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class C_EconWearable : public shade::sdk::client::C_EconEntity {
            public:
                std::int32_t m_nForceSkin; // 0x1918, 0x4 bytes
                bool m_bAlwaysAllow; // 0x191c, 0x1 bytes
                std::uint8_t pad_191d[0x3]; // 0x191d, 0x3 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_EconWearable) == 0x1920, "C_EconWearable size mismatch");
        }
    }
}
