/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_NPC_SimpleAnimatingAI.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0xcc8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class C_NPC_BaseDefenseSentry : public shade::sdk::client::C_NPC_SimpleAnimatingAI {
            public:
                Vector m_vecUnitStatusOffset; // 0x0cb8, 0xc bytes
                std::uint8_t pad_0cc4[0x4]; // 0x0cc4, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_NPC_BaseDefenseSentry) == 0xCC8, "C_NPC_BaseDefenseSentry size mismatch");
        }
    }
}
