/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_BaseClientUIEntity.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class C_BaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x9e0
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class C_PointClientUIDialog : public shade::sdk::client::C_BaseClientUIEntity {
            public:
                CHandle<shade::sdk::client::C_BaseEntity> m_hActivator; // 0x09d8, 0x4 bytes
                bool m_bStartEnabled; // 0x09dc, 0x1 bytes
                std::uint8_t pad_09dd[0x3]; // 0x09dd, 0x3 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_PointClientUIDialog) == 0x9E0, "C_PointClientUIDialog size mismatch");
        }
    }
}
