/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_BaseModelEntity.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"
#include "shade/sdk/modellib/AttachmentHandle_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class C_BaseEntity;
        }

        namespace resourcesystem {
            class InfoForResourceTypeIMaterial2;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0xa20
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class C_Sprite : public shade::sdk::client::C_BaseModelEntity {
            public:
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeIMaterial2> m_hSpriteMaterial; // 0x09a8, 0x8 bytes
                CHandle<shade::sdk::client::C_BaseEntity> m_hAttachedToEntity; // 0x09b0, 0x4 bytes
                shade::sdk::modellib::AttachmentHandle_t m_nAttachment; // 0x09b4, 0x1 bytes
                std::uint8_t pad_09b5[0x3]; // 0x09b5, 0x3 bytes
                float m_flSpriteFramerate; // 0x09b8, 0x4 bytes
                float m_flFrame; // 0x09bc, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flDieTime; // 0x09c0, 0x4 bytes
                std::uint8_t pad_09c4[0xc]; // 0x09c4, 0xc bytes
                std::uint32_t m_nBrightness; // 0x09d0, 0x4 bytes
                float m_flBrightnessDuration; // 0x09d4, 0x4 bytes
                float m_flSpriteScale; // 0x09d8, 0x4 bytes
                float m_flScaleDuration; // 0x09dc, 0x4 bytes
                bool m_bWorldSpaceScale; // 0x09e0, 0x1 bytes
                std::uint8_t pad_09e1[0x3]; // 0x09e1, 0x3 bytes
                float m_flGlowProxySize; // 0x09e4, 0x4 bytes
                float m_flHDRColorScale; // 0x09e8, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flLastTime; // 0x09ec, 0x4 bytes
                float m_flMaxFrame; // 0x09f0, 0x4 bytes
                float m_flStartScale; // 0x09f4, 0x4 bytes
                float m_flDestScale; // 0x09f8, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flScaleTimeStart; // 0x09fc, 0x4 bytes
                std::int32_t m_nStartBrightness; // 0x0a00, 0x4 bytes
                std::int32_t m_nDestBrightness; // 0x0a04, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flBrightnessTimeStart; // 0x0a08, 0x4 bytes
                std::uint8_t pad_0a0c[0xc]; // 0x0a0c, 0xc bytes
                std::int32_t m_nSpriteWidth; // 0x0a18, 0x4 bytes
                std::int32_t m_nSpriteHeight; // 0x0a1c, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_Sprite) == 0xA20, "C_Sprite size mismatch");
        }
    }
}
