/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_BaseEntity.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x638
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class C_VoteController : public shade::sdk::client::C_BaseEntity {
            public:
                std::uint8_t pad_0600[0x10]; // 0x0600, 0x10 bytes
                std::int32_t m_iActiveIssueIndex; // 0x0610, 0x4 bytes
                std::int32_t m_iOnlyTeamToVote; // 0x0614, 0x4 bytes
                std::int32_t m_nVoteOptionCount[0x5]; // 0x0618, 0x14 bytes
                std::int32_t m_nPotentialVotes; // 0x062c, 0x4 bytes
                bool m_bVotesDirty; // 0x0630, 0x1 bytes
                bool m_bTypeDirty; // 0x0631, 0x1 bytes
                bool m_bIsYesNoVote; // 0x0632, 0x1 bytes
                std::uint8_t pad_0633[0x5]; // 0x0633, 0x5 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void; // Offset: 0x0, Size: 0x0, Size In Bytes: 0x0
             */

            static_assert(sizeof(C_VoteController) == 0x638, "C_VoteController size mismatch");
        }
    }
}
