/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_BaseModelEntity.hpp"

namespace shade {
    namespace sdk {
        namespace resourcesystem {
            class InfoForResourceTypeCTextureBase;
            class InfoForResourceTypeIMaterial2;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0xac8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class C_World : public shade::sdk::client::C_BaseModelEntity {
            public:
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeIMaterial2> m_skyBoxFaces[0x6]; // 0x0a88, 0x30 bytes
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeCTextureBase> m_hHeightFogTexture; // 0x0ab8, 0x8 bytes
                CStrongHandle<shade::sdk::resourcesystem::InfoForResourceTypeCTextureBase> m_hHeightFogMaskTexture; // 0x0ac0, 0x8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(C_World) == 0xAC8, "C_World size mismatch");
        }
    }
}
