/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CitadelAbilityVData.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class CCitadelModifier;
        }

        namespace resourcesystem {
            class InfoForResourceTypeIParticleSystemDefinition;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x1698
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CAbility_Mirage_Teleport_VData : public shade::sdk::client::CitadelAbilityVData {
            public:
                CEmbeddedSubclass<shade::sdk::client::CCitadelModifier> m_InterruptNotificationModifier; // 0x13a0, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::client::CCitadelModifier> m_BuffModifier; // 0x13b0, 0x10 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_preTeleportParticle; // 0x13c0, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_TeleportStartParticle; // 0x14a0, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_TeleportEndParticle; // 0x1580, 0xe0 bytes
                CSoundEventName m_strArriveSound; // 0x1660, 0x10 bytes
                CSoundEventName m_strDepartSound; // 0x1670, 0x10 bytes
                CSoundEventName m_strChannelDestinationSound; // 0x1680, 0x10 bytes
                float m_flObjectiveOffset; // 0x1690, 0x4 bytes
                std::uint8_t pad_1694[0x4]; // 0x1694, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CAbility_Mirage_Teleport_VData) == 0x1698, "CAbility_Mirage_Teleport_VData size mismatch");
        }
    }
}
