/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CavernCrawlItemType_t.hpp"
#include "shade/sdk/client/CavernCrawlRewardType_t.hpp"
#include "shade/sdk/client/style_index_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x38
             * Alignment: 0xff
             */
            #pragma pack(push, 1)
            struct CavernCrawlReward_t {
                std::uint32_t m_nActionID; // 0x0000, 0x4 bytes
                std::uint8_t pad_0004[0x4]; // 0x0004, 0x4 bytes
                CUtlString m_rewardName; // 0x0008, 0x8 bytes
                shade::sdk::client::CavernCrawlItemType_t m_nItemType; // 0x0010, 0x1 bytes
                std::uint8_t pad_0011[0x7]; // 0x0011, 0x7 bytes
                CUtlString m_locString; // 0x0018, 0x8 bytes
                CUtlString m_tooltipString; // 0x0020, 0x8 bytes
                CUtlString m_image; // 0x0028, 0x8 bytes
                shade::sdk::client::CavernCrawlRewardType_t m_nStyleUnlockRewardType; // 0x0030, 0x1 bytes
                std::uint8_t m_nPriority; // 0x0031, 0x1 bytes
                shade::sdk::client::style_index_t m_nBundleItemDefStyle; // 0x0032, 0x1 bytes
                bool m_bImageIsBundleItemDef; // 0x0033, 0x1 bytes
                bool m_bCannotBeReplacedWithUltraRareReward; // 0x0034, 0x1 bytes
                bool m_bIsUltraRareReward; // 0x0035, 0x1 bytes
                std::uint8_t pad_0036[0x2]; // 0x0036, 0x2 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CavernCrawlReward_t) == 0x38, "CavernCrawlReward_t size mismatch");
        }
    }
}
