/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CAnimGraphControllerManager.hpp"
#include "shade/sdk/client/C_BaseModelEntity.hpp"
#include "shade/sdk/client/PhysicsRagdollPose_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class CAnimGraphControllerBase;
            struct CBaseAnimGraph__ModifierHandleVector_t;
        }

        namespace modellib {
            class AnimTagID;
        }

        namespace vphysics2 {
            class IPhysicsRagdollControl;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0xca8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CBaseAnimGraph : public shade::sdk::client::C_BaseModelEntity {
            public:
                shade::sdk::client::CAnimGraphControllerManager m_graphControllerManager; // 0x09a8, 0xb0 bytes
                shade::sdk::client::CAnimGraphControllerBase *m_pMainGraphController; // 0x0a58, 0x8 bytes
                bool m_bInitiallyPopulateInterpHistory; // 0x0a60, 0x1 bytes
                std::uint8_t pad_0a61[0x1]; // 0x0a61, 0x1 bytes
                bool m_bSuppressAnimEventSounds; // 0x0a62, 0x1 bytes
                std::uint8_t pad_0a63[0xd]; // 0x0a63, 0xd bytes
                bool m_bAnimGraphUpdateEnabled; // 0x0a70, 0x1 bytes
                std::uint8_t pad_0a71[0x3]; // 0x0a71, 0x3 bytes
                float m_flMaxSlopeDistance; // 0x0a74, 0x4 bytes
                VectorWS m_vLastSlopeCheckPos; // 0x0a78, 0xc bytes
                std::uint32_t m_nAnimGraphUpdateId; // 0x0a84, 0x4 bytes
                bool m_bAnimationUpdateScheduled; // 0x0a88, 0x1 bytes
                std::uint8_t pad_0a89[0x3]; // 0x0a89, 0x3 bytes
                Vector m_vecForce; // 0x0a8c, 0xc bytes
                std::int32_t m_nForceBone; // 0x0a98, 0x4 bytes
                std::uint8_t pad_0a9c[0x4]; // 0x0a9c, 0x4 bytes
                shade::sdk::client::CBaseAnimGraph *m_pClientsideRagdoll; // 0x0aa0, 0x8 bytes
                bool m_bBuiltRagdoll; // 0x0aa8, 0x1 bytes
                std::uint8_t pad_0aa9[0xf]; // 0x0aa9, 0xf bytes
                shade::sdk::vphysics2::IPhysicsRagdollControl *m_pRagdollControl; // 0x0ab8, 0x8 bytes
                shade::sdk::client::PhysicsRagdollPose_t m_RagdollPose; // 0x0ac0, 0x48 bytes
                bool m_bRagdollEnabled; // 0x0b08, 0x1 bytes
                bool m_bRagdollClientSide; // 0x0b09, 0x1 bytes
                std::uint8_t pad_0b0a[0xe]; // 0x0b0a, 0xe bytes
                bool m_bHasAnimatedMaterialAttributes; // 0x0b18, 0x1 bytes
                std::uint8_t pad_0b19[0x107]; // 0x0b19, 0x107 bytes
                CUtlHashtable<shade::sdk::modellib::AnimTagID, shade::sdk::client::CBaseAnimGraph__ModifierHandleVector_t> m_bodyGroupModifiers; // 0x0c20, 0x20 bytes
                std::uint8_t pad_0c40[0x68]; // 0x0c40, 0x68 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * float InputSetPlaybackRate; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             * CUtlSymbolLarge InputSetBodyGroup; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             * CUtlSymbolLarge InputSetTargetIdentifierOverride; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             * void InputClearTargetIdentifierOverride; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             * bool InputDisableAnimEventSounds; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             */

            static_assert(sizeof(CBaseAnimGraph) == 0xCA8, "CBaseAnimGraph size mismatch");
        }
    }
}
