/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CLogicalEntity.hpp"
#include "shade/sdk/entity2/CEntityIOOutput.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x638
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CBaseFilter : public shade::sdk::client::CLogicalEntity {
            public:
                bool m_bNegated; // 0x0600, 0x1 bytes
                std::uint8_t pad_0601[0x7]; // 0x0601, 0x7 bytes
                shade::sdk::entity2::CEntityIOOutput m_OnPass; // 0x0608, 0x18 bytes
                shade::sdk::entity2::CEntityIOOutput m_OnFail; // 0x0620, 0x18 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * void InputTestActivator; // Offset: 0x0, Size: 0x1, Size In Bytes: 0x0
             */

            static_assert(sizeof(CBaseFilter) == 0x638, "CBaseFilter size mismatch");
        }
    }
}
