/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CCitadelAutoScaledTime.hpp"
#include "shade/sdk/client/C_CitadelBaseAbility.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x1d58
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Ability_RocketBarrage : public shade::sdk::client::C_CitadelBaseAbility {
            public:
                shade::sdk::client::CCitadelAutoScaledTime m_flBarrageEndTime; // 0x16d8, 0x18 bytes
                std::uint8_t pad_16f0[0x630]; // 0x16f0, 0x630 bytes
                float m_flCurrentTimeScale; // 0x1d20, 0x4 bytes
                VectorWS m_vecAimPos; // 0x1d24, 0xc bytes
                Vector m_vecAimVel; // 0x1d30, 0xc bytes
                shade::sdk::entity2::GameTime_t m_flLastUpdateTime; // 0x1d3c, 0x4 bytes
                std::uint8_t pad_1d40[0x18]; // 0x1d40, 0x18 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Ability_RocketBarrage) == 0x1D58, "CCitadel_Ability_RocketBarrage size mismatch");
        }
    }
}
