/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_BaseTrigger.hpp"
#include "shade/sdk/client/ParticleIndex_t.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class C_BaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0xcf0
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadelControlPointTrigger : public shade::sdk::client::C_BaseTrigger {
            public:
                float m_flInitialRadius; // 0x0c98, 0x4 bytes
                float m_flEndRadius; // 0x0c9c, 0x4 bytes
                float m_flProgress; // 0x0ca0, 0x4 bytes
                float m_flCaptureTime; // 0x0ca4, 0x4 bytes
                CHandle<shade::sdk::client::C_BaseEntity> m_hUnlockPrereq; // 0x0ca8, 0x4 bytes
                bool m_bAvailable; // 0x0cac, 0x1 bytes
                bool m_bIsBeingCaptured; // 0x0cad, 0x1 bytes
                bool m_bIsBeingBlocked; // 0x0cae, 0x1 bytes
                std::uint8_t pad_0caf[0x9]; // 0x0caf, 0x9 bytes
                shade::sdk::entity2::GameTime_t m_flLastTouchedTime; // 0x0cb8, 0x4 bytes
                VectorWS m_vecBeamTarget; // 0x0cbc, 0xc bytes
                VectorWS m_vecBeamStart; // 0x0cc8, 0xc bytes
                shade::sdk::client::ParticleIndex_t m_nFXProgressBeam; // 0x0cd4, 0x4 bytes
                CUtlSymbolLarge m_strUnlockPrereq; // 0x0cd8, 0x8 bytes
                CUtlSymbolLarge m_strBeamStart; // 0x0ce0, 0x8 bytes
                CUtlSymbolLarge m_strBeamTarget; // 0x0ce8, 0x8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadelControlPointTrigger) == 0xCF0, "CCitadelControlPointTrigger size mismatch");
        }
    }
}
