/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CCitadelModifier.hpp"
#include "shade/sdk/client/ParticleIndex_t.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class CPointModifierThinker;
            class C_Citadel_Ice_Dome_Blocker;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x2e8
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Modifier_IceDome : public shade::sdk::client::CCitadelModifier {
            public:
                CHandle<shade::sdk::client::C_Citadel_Ice_Dome_Blocker> m_hBlocker; // 0x00c0, 0x4 bytes
                CHandle<shade::sdk::client::CPointModifierThinker> m_hFriendlyAura; // 0x00c4, 0x4 bytes
                CHandle<shade::sdk::client::CPointModifierThinker> m_hEnemyAura; // 0x00c8, 0x4 bytes
                shade::sdk::client::ParticleIndex_t m_nParticleIndex; // 0x00cc, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flStartTime; // 0x00d0, 0x4 bytes
                std::uint8_t pad_00d4[0x204]; // 0x00d4, 0x204 bytes
                Vector m_vOrigin; // 0x02d8, 0xc bytes
                std::uint8_t pad_02e4[0x4]; // 0x02e4, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Modifier_IceDome) == 0x2E8, "CCitadel_Modifier_IceDome size mismatch");
        }
    }
}
