/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CCitadelModifierVData.hpp"
#include "shade/sdk/client/CCitadelProjectileTrackingParams.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class CCitadelModifier;
        }

        namespace resourcesystem {
            class InfoForResourceTypeIParticleSystemDefinition;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0xb48
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Modifier_DazzlingOrbWatcherVData : public shade::sdk::client::CCitadelModifierVData {
            public:
                CEmbeddedSubclass<shade::sdk::client::CCitadelModifier> m_SlowModifier; // 0x0750, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::client::CCitadelModifier> m_NextTargetModifier; // 0x0760, 0x10 bytes
                CEmbeddedSubclass<shade::sdk::client::CCitadelModifier> m_OrbFriendlyBounceWatcherModifier; // 0x0770, 0x10 bytes
                CSoundEventName m_strExplodeSound; // 0x0780, 0x10 bytes
                CSoundEventName m_strFinalExplodeSound; // 0x0790, 0x10 bytes
                CSoundEventName m_strWorldHitSound; // 0x07a0, 0x10 bytes
                CSoundEventName m_strGraceLoopSound; // 0x07b0, 0x10 bytes
                CSoundEventName m_strExpireSound; // 0x07c0, 0x10 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_ExplodeParticle; // 0x07d0, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_BounceParticle; // 0x08b0, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_GraceParticle; // 0x0990, 0xe0 bytes
                CPiecewiseCurve m_BouncePositionCurve; // 0x0a70, 0x40 bytes
                float m_flMinProjectileTravelTime; // 0x0ab0, 0x4 bytes
                std::uint8_t pad_0ab4[0x4]; // 0x0ab4, 0x4 bytes
                shade::sdk::client::CCitadelProjectileTrackingParams m_TrackingParams; // 0x0ab8, 0x90 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Modifier_DazzlingOrbWatcherVData) == 0xB48, "CCitadel_Modifier_DazzlingOrbWatcherVData size mismatch");
        }
    }
}
