/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CCitadelModifierVData.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class CCitadelModifier;
        }

        namespace resourcesystem {
            class InfoForResourceTypeIParticleSystemDefinition;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0xb58
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Modifier_Baba_Ult2_Mark_VData : public shade::sdk::client::CCitadelModifierVData {
            public:
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_LockingOnParticle; // 0x0790, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_LockingOnParticleCaster; // 0x0870, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_TickParticle; // 0x0950, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_FinalTickParticle; // 0x0a30, 0xe0 bytes
                CSoundEventName m_strVictimLockonSound; // 0x0b10, 0x10 bytes
                CSoundEventName m_strVictimMaxLockonSound; // 0x0b20, 0x10 bytes
                CSoundEventName m_strFinalPigeonWarning; // 0x0b30, 0x10 bytes
                float m_flImpactDelay; // 0x0b40, 0x4 bytes
                std::uint8_t pad_0b44[0x4]; // 0x0b44, 0x4 bytes
                CEmbeddedSubclass<shade::sdk::client::CCitadelModifier> m_ImpactModifier; // 0x0b48, 0x10 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Modifier_Baba_Ult2_Mark_VData) == 0xB58, "CCitadel_Modifier_Baba_Ult2_Mark_VData size mismatch");
        }
    }
}
