/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CCitadelModifier.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x4d8
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Modifier_Mirage_SandPhantom_Passive_Victim : public shade::sdk::client::CCitadelModifier {
            public:
                std::uint8_t pad_00c0[0x10]; // 0x00c0, 0x10 bytes
                shade::sdk::entity2::GameTime_t m_flLastProcTime; // 0x00d0, 0x4 bytes
                std::uint8_t pad_00d4[0x404]; // 0x00d4, 0x404 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Modifier_Mirage_SandPhantom_Passive_Victim) == 0x4D8, "CCitadel_Modifier_Mirage_SandPhantom_Passive_Victim size mismatch");
        }
    }
}
