/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_CitadelBaseAbility.hpp"
#include "shade/sdk/client/ParticleIndex_t.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            struct LockonTarget_t;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x1b70
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadelBaseLockonAbility : public shade::sdk::client::C_CitadelBaseAbility {
            public:
                std::uint8_t pad_16d8[0x420]; // 0x16d8, 0x420 bytes
                C_UtlVectorEmbeddedNetworkVar<shade::sdk::client::LockonTarget_t> m_vecLockonTargets; // 0x1af8, 0x68 bytes
                shade::sdk::entity2::GameTime_t m_LockOnStartTime; // 0x1b60, 0x4 bytes
                std::uint8_t pad_1b64[0x4]; // 0x1b64, 0x4 bytes
                shade::sdk::client::ParticleIndex_t m_nTargetingLightEffect; // 0x1b68, 0x4 bytes
                std::uint8_t pad_1b6c[0x4]; // 0x1b6c, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadelBaseLockonAbility) == 0x1B70, "CCitadelBaseLockonAbility size mismatch");
        }
    }
}
