/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CCitadelModifier.hpp"
#include "shade/sdk/client/ModelChange_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x1b0
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Modifier_CopyUlt : public shade::sdk::client::CCitadelModifier {
            public:
                std::int32_t m_nCopiedHeroID; // 0x00c0, 0x4 bytes
                std::uint8_t pad_00c4[0x4]; // 0x00c4, 0x4 bytes
                shade::sdk::client::ModelChange_t m_ModelChange; // 0x00c8, 0xe8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Modifier_CopyUlt) == 0x1B0, "CCitadel_Modifier_CopyUlt size mismatch");
        }
    }
}
