/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CCitadelModifierAura.hpp"
#include "shade/sdk/client/ParticleIndex_t.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x7b8
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Modifier_GraveStone : public shade::sdk::client::CCitadelModifierAura {
            public:
                std::uint8_t pad_0110[0x18]; // 0x0110, 0x18 bytes
                shade::sdk::client::ParticleIndex_t m_nParticleIndexAura; // 0x0128, 0x4 bytes
                shade::sdk::client::ParticleIndex_t m_nParticleIndex; // 0x012c, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flStartTime; // 0x0130, 0x4 bytes
                std::uint8_t pad_0134[0x684]; // 0x0134, 0x684 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Modifier_GraveStone) == 0x7B8, "CCitadel_Modifier_GraveStone size mismatch");
        }
    }
}
