/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_CitadelBaseAbility.hpp"
#include "shade/sdk/client/EFlightState.hpp"
#include "shade/sdk/client/ParticleIndex_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class C_BaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x2320
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Ability_Tengu_AirLift : public shade::sdk::client::C_CitadelBaseAbility {
            public:
                CHandle<shade::sdk::client::C_BaseEntity> m_hGrabTarget; // 0x16d8, 0x4 bytes
                shade::sdk::client::ParticleIndex_t m_nHoldBombEffect; // 0x16dc, 0x4 bytes
                std::uint8_t pad_16e0[0xc28]; // 0x16e0, 0xc28 bytes
                shade::sdk::client::EFlightState m_eFlightState; // 0x2308, 0x1 bytes
                bool m_bIsGrabbing; // 0x2309, 0x1 bytes
                bool m_bIsHoldingBomb; // 0x230a, 0x1 bytes
                std::uint8_t pad_230b[0x1]; // 0x230b, 0x1 bytes
                float m_flCurrentSpeed; // 0x230c, 0x4 bytes
                std::uint8_t pad_2310[0x10]; // 0x2310, 0x10 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Ability_Tengu_AirLift) == 0x2320, "CCitadel_Ability_Tengu_AirLift size mismatch");
        }
    }
}
