/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CitadelItemVData.hpp"

namespace shade {
    namespace sdk {
        namespace resourcesystem {
            class InfoForResourceTypeIParticleSystemDefinition;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x1c78
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Item_ShadowStepVData : public shade::sdk::client::CitadelItemVData {
            public:
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_PulseParticle; // 0x18b8, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_TargetParticle; // 0x1998, 0xe0 bytes
                CSoundEventName m_strPulseTickSound; // 0x1a78, 0x10 bytes
                std::int32_t m_iMaxTargets; // 0x1a88, 0x4 bytes
                std::uint8_t pad_1a8c[0x4]; // 0x1a8c, 0x4 bytes
                CSoundEventName m_strExplodeSound; // 0x1a90, 0x10 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_CastDelayParticle; // 0x1aa0, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_TeleportTrailParticle; // 0x1b80, 0xe0 bytes
                float m_flGroundProbeSpeed; // 0x1c60, 0x4 bytes
                float m_flGroundStepDown; // 0x1c64, 0x4 bytes
                float m_flGroundStepUp; // 0x1c68, 0x4 bytes
                std::int32_t m_iMaxGroundIterations; // 0x1c6c, 0x4 bytes
                float m_flVelocityScale; // 0x1c70, 0x4 bytes
                std::uint8_t pad_1c74[0x4]; // 0x1c74, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Item_ShadowStepVData) == 0x1C78, "CCitadel_Item_ShadowStepVData size mismatch");
        }
    }
}
