/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CCitadel_Item.hpp"
#include "shade/sdk/client/ParticleIndex_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x1790
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Item_WarpStone : public shade::sdk::client::CCitadel_Item {
            public:
                shade::sdk::client::ParticleIndex_t m_nCastDelayParticleIndex; // 0x16d8, 0x4 bytes
                std::uint8_t pad_16dc[0xb4]; // 0x16dc, 0xb4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Item_WarpStone) == 0x1790, "CCitadel_Item_WarpStone size mismatch");
        }
    }
}
