/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_CitadelBaseAbility.hpp"
#include "shade/sdk/client/ParticleIndex_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x1a50
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCitadel_Ability_Fathom_Breach : public shade::sdk::client::C_CitadelBaseAbility {
            public:
                shade::sdk::client::ParticleIndex_t m_nRollFXIndex; // 0x16d8, 0x4 bytes
                bool m_bInFlight; // 0x16dc, 0x1 bytes
                std::uint8_t pad_16dd[0x373]; // 0x16dd, 0x373 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCitadel_Ability_Fathom_Breach) == 0x1A50, "CCitadel_Ability_Fathom_Breach size mismatch");
        }
    }
}
