/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CPlayer_CameraServices.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class C_BaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x2b0
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CCSPlayerBase_CameraServices : public shade::sdk::client::CPlayer_CameraServices {
            public:
                std::uint32_t m_iFOV; // 0x0298, 0x4 bytes
                std::uint32_t m_iFOVStart; // 0x029c, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_flFOVTime; // 0x02a0, 0x4 bytes
                float m_flFOVRate; // 0x02a4, 0x4 bytes
                CHandle<shade::sdk::client::C_BaseEntity> m_hZoomOwner; // 0x02a8, 0x4 bytes
                float m_flLastShotFOV; // 0x02ac, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CCSPlayerBase_CameraServices) == 0x2B0, "CCSPlayerBase_CameraServices size mismatch");
        }
    }
}
