/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/EKillTypes_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class CCSPlayerController;
            class C_CSPlayerPawn;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x78
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDamageRecord {
            public:
                std::uint8_t pad_0000[0x30]; // 0x0000, 0x30 bytes
                CHandle<shade::sdk::client::C_CSPlayerPawn> m_PlayerDamager; // 0x0030, 0x4 bytes
                CHandle<shade::sdk::client::C_CSPlayerPawn> m_PlayerRecipient; // 0x0034, 0x4 bytes
                CHandle<shade::sdk::client::CCSPlayerController> m_hPlayerControllerDamager; // 0x0038, 0x4 bytes
                CHandle<shade::sdk::client::CCSPlayerController> m_hPlayerControllerRecipient; // 0x003c, 0x4 bytes
                CUtlString m_szPlayerDamagerName; // 0x0040, 0x8 bytes
                CUtlString m_szPlayerRecipientName; // 0x0048, 0x8 bytes
                std::uint64_t m_DamagerXuid; // 0x0050, 0x8 bytes
                std::uint64_t m_RecipientXuid; // 0x0058, 0x8 bytes
                float m_flBulletsDamage; // 0x0060, 0x4 bytes
                float m_flDamage; // 0x0064, 0x4 bytes
                float m_flActualHealthRemoved; // 0x0068, 0x4 bytes
                std::int32_t m_iNumHits; // 0x006c, 0x4 bytes
                std::int32_t m_iLastBulletUpdate; // 0x0070, 0x4 bytes
                bool m_bIsOtherEnemy; // 0x0074, 0x1 bytes
                shade::sdk::client::EKillTypes_t m_killType; // 0x0075, 0x1 bytes
                std::uint8_t pad_0076[0x2]; // 0x0076, 0x2 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDamageRecord) == 0x78, "CDamageRecord size mismatch");
        }
    }
}
