/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CDOTA_Buff.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class C_BaseEntity;
            class C_DOTABaseAbility;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x1a90
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTA_Modifier_Undying_Tombstone_Zombie_Deathstrike : public shade::sdk::client::CDOTA_Buff {
            public:
                float radius; // 0x1a78, 0x4 bytes
                float health_threshold_pct; // 0x1a7c, 0x4 bytes
                float duration; // 0x1a80, 0x4 bytes
                CHandle<shade::sdk::client::C_DOTABaseAbility> m_hTombstoneSourceAbility; // 0x1a84, 0x4 bytes
                CHandle<shade::sdk::client::C_BaseEntity> m_hChaseUnit; // 0x1a88, 0x4 bytes
                std::uint8_t pad_1a8c[0x4]; // 0x1a8c, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTA_Modifier_Undying_Tombstone_Zombie_Deathstrike) == 0x1A90, "CDOTA_Modifier_Undying_Tombstone_Zombie_Deathstrike size mismatch");
        }
    }
}
