/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CDOTA_Buff.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x1a88
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTA_Modifier_NightStalker_Void : public shade::sdk::client::CDOTA_Buff {
            public:
                std::int32_t movespeed_slow; // 0x1a78, 0x4 bytes
                std::int32_t attackspeed_slow; // 0x1a7c, 0x4 bytes
                float invisible_damage_pers; // 0x1a80, 0x4 bytes
                float invisible_damage_tickrate; // 0x1a84, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTA_Modifier_NightStalker_Void) == 0x1A88, "CDOTA_Modifier_NightStalker_Void size mismatch");
        }
    }
}
