/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CrownfallCreditsAABB_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0xa0
             * Alignment: 0x8
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class CDOTACrownfallCreditsCharacterDefinition {
            public:
                CPanoramaImageName m_strImage; // 0x0000, 0x10 bytes
                CUtlString m_strLocCharacterName; // 0x0010, 0x8 bytes
                CUtlString m_strLocCharacterTitle; // 0x0018, 0x8 bytes
                std::int32_t m_nUniqueClickKey; // 0x0020, 0x4 bytes
                std::uint8_t pad_0024[0x4]; // 0x0024, 0x4 bytes
                CPanoramaImageName m_strImageAlt; // 0x0028, 0x10 bytes
                CUtlString m_strLocCharacterNameAlt; // 0x0038, 0x8 bytes
                CUtlString m_strLocCharacterTitleAlt; // 0x0040, 0x8 bytes
                bool m_bFlipFacing; // 0x0048, 0x1 bytes
                std::uint8_t pad_0049[0x3]; // 0x0049, 0x3 bytes
                shade::sdk::client::CrownfallCreditsAABB_t m_bounds; // 0x004c, 0x10 bytes
                std::uint8_t pad_005c[0x4]; // 0x005c, 0x4 bytes
                CUtlString m_strLocCharacterTitleAlt2; // 0x0060, 0x8 bytes
                CUtlString m_strLocCharacterTitleAlt3; // 0x0068, 0x8 bytes
                CUtlString m_strLocCharacterTitleAlt4; // 0x0070, 0x8 bytes
                CUtlString m_strLocCharacterTitleAlt5; // 0x0078, 0x8 bytes
                CUtlString m_strLocCharacterTitleAlt6; // 0x0080, 0x8 bytes
                std::int32_t m_nAltImageW; // 0x0088, 0x4 bytes
                std::int32_t m_nAltImageH; // 0x008c, 0x4 bytes
                std::int32_t m_nAltImageFrameTime; // 0x0090, 0x4 bytes
                std::int32_t m_nYOffset; // 0x0094, 0x4 bytes
                std::uint16_t m_unFrameTime; // 0x0098, 0x2 bytes
                std::uint8_t pad_009a[0x6]; // 0x009a, 0x6 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTACrownfallCreditsCharacterDefinition) == 0xA0, "CDOTACrownfallCreditsCharacterDefinition size mismatch");
        }
    }
}
