/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CDOTA_Buff.hpp"
#include "shade/sdk/entity2/GameTime_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x1ac0
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTA_Modifier_Grimstroke_SpiritWalk_Buff : public shade::sdk::client::CDOTA_Buff {
            public:
                shade::sdk::entity2::GameTime_t m_fStartTime; // 0x1a78, 0x4 bytes
                std::int32_t m_nHeroTickDamageApplied; // 0x1a7c, 0x4 bytes
                shade::sdk::entity2::GameTime_t m_fLastEffectsTime; // 0x1a80, 0x4 bytes
                float radius; // 0x1a84, 0x4 bytes
                float buff_duration; // 0x1a88, 0x4 bytes
                float debuff_duration; // 0x1a8c, 0x4 bytes
                std::int32_t max_damage; // 0x1a90, 0x4 bytes
                float max_stun; // 0x1a94, 0x4 bytes
                std::int32_t movespeed_bonus_pct; // 0x1a98, 0x4 bytes
                std::int32_t damage_per_tick; // 0x1a9c, 0x4 bytes
                float tick_rate; // 0x1aa0, 0x4 bytes
                float max_threshold_duration; // 0x1aa4, 0x4 bytes
                std::int32_t can_end_early; // 0x1aa8, 0x4 bytes
                std::int32_t shard_bonus_damage_pct; // 0x1aac, 0x4 bytes
                std::int32_t shard_heal_pct; // 0x1ab0, 0x4 bytes
                float shard_creep_penalty; // 0x1ab4, 0x4 bytes
                bool m_bIsReflection; // 0x1ab8, 0x1 bytes
                std::uint8_t pad_1ab9[0x7]; // 0x1ab9, 0x7 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTA_Modifier_Grimstroke_SpiritWalk_Buff) == 0x1AC0, "CDOTA_Modifier_Grimstroke_SpiritWalk_Buff size mismatch");
        }
    }
}
