/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CDOTA_Buff.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x1a90
             * Alignment: 0xff
             * Has VTable
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CDOTA_Modifier_Pudge_RottenCore : public shade::sdk::client::CDOTA_Buff {
            public:
                float attack_damage_per_stack; // 0x1a78, 0x4 bytes
                std::int32_t max_total_stacks; // 0x1a7c, 0x4 bytes
                float rot_tick; // 0x1a80, 0x4 bytes
                std::int32_t stacks_decrement_per_rot_off_tick; // 0x1a84, 0x4 bytes
                std::int32_t m_nRotOffTicksToDecrement; // 0x1a88, 0x4 bytes
                std::int32_t m_nAccumulatedRotOffTicks; // 0x1a8c, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CDOTA_Modifier_Pudge_RottenCore) == 0x1A90, "CDOTA_Modifier_Pudge_RottenCore size mismatch");
        }
    }
}
