/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CitadelStatsDisplay_t.hpp"
#include "shade/sdk/client/EAbilityResourceType.hpp"
#include "shade/sdk/client/EAbilitySlots_t.hpp"
#include "shade/sdk/client/EHeroType.hpp"
#include "shade/sdk/client/EItemSlotTypes_t.hpp"
#include "shade/sdk/client/EModifierValue.hpp"
#include "shade/sdk/client/EStatsType.hpp"
#include "shade/sdk/client/HeroID_t.hpp"
#include "shade/sdk/client/HeroStatsDisplay_t.hpp"
#include "shade/sdk/client/HeroStatsUI_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            struct HeroAnimGraphDefaultValueOverride_t;
            struct HeroLevel_t;
            struct HeroPurchaseBonus_t;
            struct HeroScalingStat_t;
            struct ItemDraftWeight_t;
            struct ItemSlotInfo_t;
            struct ModCostBonuses_t;
        }

        namespace resourcesystem {
            class InfoForResourceTypeCModel;
            class InfoForResourceTypeCVSoundEventScriptList;
            class InfoForResourceTypeIParticleSystemDefinition;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0xf08
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            struct CitadelHeroData_t {
                std::uint8_t pad_0000[0x8]; // 0x0000, 0x8 bytes
                CUtlVector<shade::sdk::client::HeroAnimGraphDefaultValueOverride_t> m_vecAnimGraphDefaultValueOverrides; // 0x0008, 0x18 bytes
                std::uint8_t pad_0020[0x8]; // 0x0020, 0x8 bytes
                shade::sdk::client::HeroID_t m_HeroID; // 0x0028, 0x4 bytes
                std::uint8_t pad_002c[0x4]; // 0x002c, 0x4 bytes
                CUtlString m_strHeroSortName; // 0x0030, 0x8 bytes
                CUtlString m_strHeroSearchName; // 0x0038, 0x8 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_hDamageTakenParticle; // 0x0040, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_hGroundDamageTakenParticle; // 0x0120, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_hDeathParticle; // 0x0200, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_hLowHealthParticle; // 0x02e0, 0xe0 bytes
                CPanoramaImageName m_strIconImageSmall; // 0x03c0, 0x10 bytes
                CPanoramaImageName m_strIconHeroCard; // 0x03d0, 0x10 bytes
                CPanoramaImageName m_strIconHeroCardCritical; // 0x03e0, 0x10 bytes
                CPanoramaImageName m_strIconHeroCardGloat; // 0x03f0, 0x10 bytes
                CPanoramaImageName m_strMinimapImage; // 0x0400, 0x10 bytes
                CPanoramaImageName m_strTopBarVertical; // 0x0410, 0x10 bytes
                CPanoramaImageName m_strLogoImageEnglish; // 0x0420, 0x10 bytes
                CPanoramaImageName m_strLogoImageLocalized; // 0x0430, 0x10 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeIParticleSystemDefinition>> m_hRespawnParticle; // 0x0440, 0xe0 bytes
                Color m_colorUI; // 0x0520, 0x4 bytes
                std::uint8_t pad_0524[0x4]; // 0x0524, 0x4 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeCModel>> m_strModelName; // 0x0528, 0xe0 bytes
                std::int32_t m_nModelSkin; // 0x0608, 0x4 bytes
                std::uint8_t pad_060c[0x4]; // 0x060c, 0x4 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeCModel>> m_strWIPModelName; // 0x0610, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeCModel>> m_strMainOnlyModelName; // 0x06f0, 0xe0 bytes
                bool m_bUseMainOnlyModelForExperimental; // 0x07d0, 0x1 bytes
                std::uint8_t pad_07d1[0x7]; // 0x07d1, 0x7 bytes
                CUtlString m_strUIPortraitMap; // 0x07d8, 0x8 bytes
                CUtlString m_strUIShoppingMap; // 0x07e0, 0x8 bytes
                CUtlString m_strUITeamRevealMap; // 0x07e8, 0x8 bytes
                CUtlString m_strUIPostgamePortraitMap; // 0x07f0, 0x8 bytes
                shade::sdk::client::HeroStatsUI_t m_heroStatsUI; // 0x07f8, 0x30 bytes
                shade::sdk::client::HeroStatsDisplay_t m_heroStatsDisplay; // 0x0828, 0x90 bytes
                shade::sdk::client::CitadelStatsDisplay_t m_ShopStatDisplay; // 0x08b8, 0xa8 bytes
                CSoundEventName m_strDeathVOSound; // 0x0960, 0x10 bytes
                CSoundEventName m_strDeathSound; // 0x0970, 0x10 bytes
                CSoundEventName m_strLastHitSound; // 0x0980, 0x10 bytes
                CSoundEventName m_strRosterSelectedSound; // 0x0990, 0x10 bytes
                CSoundEventName m_strRosterRemovedSound; // 0x09a0, 0x10 bytes
                CSoundEventName m_strRosterAvoidedSound; // 0x09b0, 0x10 bytes
                CSoundEventName m_strVoteRevealSound; // 0x09c0, 0x10 bytes
                CSoundEventName m_strLowHealthSound; // 0x09d0, 0x10 bytes
                CSoundEventName m_strHeroSpecificLowHealthSound; // 0x09e0, 0x10 bytes
                CSoundEventName m_strMovementLoop; // 0x09f0, 0x10 bytes
                CSoundEventName m_strPostGameVictorySound; // 0x0a00, 0x10 bytes
                CSoundEventName m_strPostGameDefeatSound; // 0x0a10, 0x10 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeCVSoundEventScriptList>> m_hGameSoundEventScript; // 0x0a20, 0xe0 bytes
                CResourceNameTyped<CWeakHandle<shade::sdk::resourcesystem::InfoForResourceTypeCVSoundEventScriptList>> m_hGeneratedVOEventScript; // 0x0b00, 0xe0 bytes
                float m_flStealthSpeedMetersPerSecond; // 0x0be0, 0x4 bytes
                bool m_bInDevelopment; // 0x0be4, 0x1 bytes
                bool m_bAssignedPlayersOnly; // 0x0be5, 0x1 bytes
                bool m_bNewPlayerRecommended; // 0x0be6, 0x1 bytes
                bool m_bLaneTestingRecommended; // 0x0be7, 0x1 bytes
                bool m_bNeedsTesting; // 0x0be8, 0x1 bytes
                bool m_bLimitedTesting; // 0x0be9, 0x1 bytes
                bool m_bDisabled; // 0x0bea, 0x1 bytes
                bool m_bPlayerSelectable; // 0x0beb, 0x1 bytes
                bool m_bPrereleaseOnly; // 0x0bec, 0x1 bytes
                std::uint8_t pad_0bed[0x3]; // 0x0bed, 0x3 bytes
                std::int32_t m_nComplexity; // 0x0bf0, 0x4 bytes
                std::int32_t m_nAllyBotDifficulty; // 0x0bf4, 0x4 bytes
                std::int32_t m_nEnemyBotDifficulty; // 0x0bf8, 0x4 bytes
                float m_flMinLowHealthPercentage; // 0x0bfc, 0x4 bytes
                float m_flMaxLowHealthPercentage; // 0x0c00, 0x4 bytes
                float m_flMinMidHealthPercentage; // 0x0c04, 0x4 bytes
                float m_flMaxMidHealthPercentage; // 0x0c08, 0x4 bytes
                float m_flMinHealthForThreshold; // 0x0c0c, 0x4 bytes
                float m_flMaxHealthForThreshold; // 0x0c10, 0x4 bytes
                float m_flInCombatWithHeroDuration; // 0x0c14, 0x4 bytes
                float m_flInCombatWithNonHeroDuration; // 0x0c18, 0x4 bytes
                float m_flInCombatWithNeutralDuration; // 0x0c1c, 0x4 bytes
                bool m_bNAGunFalloffRange; // 0x0c20, 0x1 bytes
                bool m_bAllowedInTunnels; // 0x0c21, 0x1 bytes
                std::uint8_t pad_0c22[0x6]; // 0x0c22, 0x6 bytes
                CUtlOrderedMap<shade::sdk::client::EStatsType, float> m_mapStartingStats; // 0x0c28, 0x28 bytes
                CUtlOrderedMap<shade::sdk::client::EStatsType, shade::sdk::client::HeroScalingStat_t> m_mapScalingStats; // 0x0c50, 0x28 bytes
                CPiecewiseCurve m_groundDashPositionCurve; // 0x0c78, 0x40 bytes
                CUtlOrderedMap<shade::sdk::client::EItemSlotTypes_t, CUtlVector<shade::sdk::client::ModCostBonuses_t>> m_mapModCostBonuses; // 0x0cb8, 0x28 bytes
                std::uint8_t pad_0ce0[0x18]; // 0x0ce0, 0x18 bytes
                CUtlOrderedMap<shade::sdk::client::EAbilitySlots_t, CSubclassName<4>> m_mapBoundAbilities; // 0x0cf8, 0x28 bytes
                CUtlOrderedMap<shade::sdk::client::EAbilitySlots_t, CSubclassName<4>> m_mapWIPAbilities; // 0x0d20, 0x28 bytes
                CUtlOrderedMap<shade::sdk::client::EItemSlotTypes_t, shade::sdk::client::ItemSlotInfo_t> m_mapItemSlotInfo; // 0x0d48, 0x28 bytes
                std::uint8_t pad_0d70[0x50]; // 0x0d70, 0x50 bytes
                shade::sdk::client::EAbilityResourceType m_eAbilityResourceType; // 0x0dc0, 0x4 bytes
                std::uint8_t pad_0dc4[0x4]; // 0x0dc4, 0x4 bytes
                CUtlString m_strGunTag; // 0x0dc8, 0x8 bytes
                CUtlVector<CUtlString> m_vecHeroTags; // 0x0dd0, 0x18 bytes
                shade::sdk::client::EHeroType m_eHeroType; // 0x0de8, 0x4 bytes
                std::uint8_t pad_0dec[0x4]; // 0x0dec, 0x4 bytes
                CUtlString m_strRosterBackgroundLayout; // 0x0df0, 0x8 bytes
                CUtlString m_strHideoutRichPresence; // 0x0df8, 0x8 bytes
                CUtlOrderedMap<CUtlString, float> m_mapItemDraftCounterWeights; // 0x0e00, 0x28 bytes
                std::uint8_t pad_0e28[0x18]; // 0x0e28, 0x18 bytes
                CUtlOrderedMap<shade::sdk::client::EModifierValue, float> m_mapStandardLevelUpUpgrades; // 0x0e40, 0x28 bytes
                CUtlOrderedMap<std::int32_t, shade::sdk::client::HeroLevel_t> m_mapLevelInfo; // 0x0e68, 0x28 bytes
                CUtlOrderedMap<shade::sdk::client::EItemSlotTypes_t, CUtlVector<shade::sdk::client::HeroPurchaseBonus_t>> m_mapPurchaseBonuses; // 0x0e90, 0x28 bytes
                CUtlOrderedMap<CUtlString, shade::sdk::client::ItemDraftWeight_t> m_mapItemDraftBucketing; // 0x0eb8, 0x28 bytes
                std::uint8_t pad_0ee0[0x28]; // 0x0ee0, 0x28 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CitadelHeroData_t) == 0xF08, "CitadelHeroData_t size mismatch");
        }
    }
}
