/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_CitadelProjectile.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0xce8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CItemExplosiveBarrel : public shade::sdk::client::C_CitadelProjectile {
            public:
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CItemExplosiveBarrel) == 0xCE8, "CItemExplosiveBarrel size mismatch");
        }
    }
}
