/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/EMonsterHunterSmallRewardCategory.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x10
             * Alignment: 0x8
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class CMonsterHunterSmallRewardCategoryDefinition {
            public:
                shade::sdk::client::EMonsterHunterSmallRewardCategory m_eCategory; // 0x0000, 0x4 bytes
                std::uint32_t m_unActionID; // 0x0004, 0x4 bytes
                CUtlString m_strLocName; // 0x0008, 0x8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CMonsterHunterSmallRewardCategoryDefinition) == 0x10, "CMonsterHunterSmallRewardCategoryDefinition size mismatch");
        }
    }
}
