/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/animlib/CNmPassthroughNode__CDefinition.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x38
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class CNmAimCSNode__CDefinition : public shade::sdk::animlib::CNmPassthroughNode__CDefinition {
            public:
                std::int16_t m_nVerticalAngleNodeIdx; // 0x0018, 0x2 bytes
                std::int16_t m_nHorizontalAngleNodeIdx; // 0x001a, 0x2 bytes
                std::int16_t m_nWeaponCategoryNodeIdx; // 0x001c, 0x2 bytes
                std::int16_t m_nWeaponTypeNodeIdx; // 0x001e, 0x2 bytes
                std::int16_t m_nWeaponActionNodeIdx; // 0x0020, 0x2 bytes
                std::int16_t m_nWeaponDropNodeIdx; // 0x0022, 0x2 bytes
                std::int16_t m_nIsDefusingNodeIdx; // 0x0024, 0x2 bytes
                std::int16_t m_nCrouchWeightNodeIdx; // 0x0026, 0x2 bytes
                float m_flHandIKBlendInTimeSeconds; // 0x0028, 0x4 bytes
                float m_flActionBlendTimeSeconds; // 0x002c, 0x4 bytes
                float m_flPlantingBlendTimeSeconds; // 0x0030, 0x4 bytes
                std::uint8_t pad_0034[0x4]; // 0x0034, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CNmAimCSNode__CDefinition) == 0x38, "CNmAimCSNode__CDefinition size mismatch");
        }
    }
}
