/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CPathSimple.hpp"
#include "shade/sdk/client/DirectionAlongSimplePath_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class CPathNode;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x760
             * Alignment: 0x10
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CPathWithDynamicNodes : public shade::sdk::client::CPathSimple {
            public:
                C_NetworkUtlVectorBase<CHandle<shade::sdk::client::CPathNode>> m_vecPathNodes; // 0x0710, 0x18 bytes
                std::uint8_t pad_0728[0x8]; // 0x0728, 0x8 bytes
                CTransform m_xInitialPathWorldToLocal; // 0x0730, 0x20 bytes
                shade::sdk::client::DirectionAlongSimplePath_t m_eDesiredDirection; // 0x0750, 0x4 bytes
                bool m_bIgnoreParentRotation; // 0x0754, 0x1 bytes
                std::uint8_t pad_0755[0xb]; // 0x0755, 0xb bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CPathWithDynamicNodes) == 0x760, "CPathWithDynamicNodes size mismatch");
        }
    }
}
