/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/C_BaseEntity.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class C_SkyCamera;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x5f8
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             * Module Local Type Scope
             */
            #pragma pack(push, 1)
            class CSkyboxReference : public shade::sdk::client::C_BaseEntity {
            public:
                WorldGroupId_t m_worldGroupId; // 0x05f0, 0x4 bytes
                CHandle<shade::sdk::client::C_SkyCamera> m_hSkyCamera; // 0x05f4, 0x4 bytes
            };
            #pragma pack(pop)

            /* Data Map Fields
             * char *worldGroupID; // Offset: 0x7fffffff, Size: 0x1, Size In Bytes: 0x0
             */

            static_assert(sizeof(CSkyboxReference) == 0x5F8, "CSkyboxReference size mismatch");
        }
    }
}
