/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CSurvivorsPowerUp_AreaAttack.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x800
             * Alignment: 0xff
             * Has VTable
             */
            #pragma pack(push, 1)
            class CSurvivorsPowerUp_AreaAttack_Circle : public shade::sdk::client::CSurvivorsPowerUp_AreaAttack {
            public:
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CSurvivorsPowerUp_AreaAttack_Circle) == 0x800, "CSurvivorsPowerUp_AreaAttack_Circle size mismatch");
        }
    }
}
