/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CSurvivorsPowerUp_AreaAttack_Circle.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            struct SurvivorsUnitID_t;
        }

        namespace particleslib {
            class CNewParticleEffect;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x850
             * Alignment: 0xff
             * Has VTable
             */
            #pragma pack(push, 1)
            class CSurvivorsPowerUp_AreaAttack_CircleConstant : public shade::sdk::client::CSurvivorsPowerUp_AreaAttack_Circle {
            public:
                CUtlOrderedMap<shade::sdk::client::SurvivorsUnitID_t, float> m_mapEnemyDamagedTimers; // 0x0800, 0x28 bytes
                shade::sdk::particleslib::CNewParticleEffect *m_pParticleEffect; // 0x0828, 0x8 bytes
                std::uint8_t pad_0830[0x18]; // 0x0830, 0x18 bytes
                float m_flNextTrailCreationTimer; // 0x0848, 0x4 bytes
                std::uint8_t pad_084c[0x4]; // 0x084c, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CSurvivorsPowerUp_AreaAttack_CircleConstant) == 0x850, "CSurvivorsPowerUp_AreaAttack_CircleConstant size mismatch");
        }
    }
}
