/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CDOTAOverworldCharacterBase.hpp"
#include "shade/sdk/client/CDOTAOverworldCharacterConditional.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x58
             * Alignment: 0x8
             * Construct Allowed
             */
            #pragma pack(push, 1)
            struct DOTAOverworldCharacterOverrideConditional_t {
                shade::sdk::client::CDOTAOverworldCharacterConditional m_condition; // 0x0000, 0x20 bytes
                shade::sdk::client::CDOTAOverworldCharacterBase m_character; // 0x0020, 0x38 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(DOTAOverworldCharacterOverrideConditional_t) == 0x58, "DOTAOverworldCharacterOverrideConditional_t size mismatch");
        }
    }
}
