/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

namespace shade {
    namespace sdk {
        namespace client {
            enum class ECitadelServerMode : std::uint32_t {
                k_eCitadelServerMode_Match = 0x0,
                k_eCitadelServerMode_Hideout = 0x1,
                k_eCitadelServerMode_CoopBot = 0x2,
                k_eCitadelServerMode_Internal = 0x3
            };
        }
    }
}
