/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

namespace shade {
    namespace sdk {
        namespace client {
            enum class ECommunityItemAttribute : std::uint32_t {
                k_ECommunityItemAttribute_Invalid = 0x0,
                k_ECommunityItemAttribute_CardBorder = 0x1,
                k_ECommunityItemAttribute_Level = 0x2,
                k_ECommunityItemAttribute_IssueNumber = 0x3,
                k_ECommunityItemAttribute_TradableTime = 0x4,
                k_ECommunityItemAttribute_StorePackageID = 0x5,
                k_ECommunityItemAttribute_CommunityItemAppID = 0x6,
                k_ECommunityItemAttribute_CommunityItemType = 0x7,
                k_ECommunityItemAttribute_ProfileModiferEnabled = 0x8,
                k_ECommunityItemAttribute_ExpiryTime = 0x9
            };
        }
    }
}
