/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

namespace shade {
    namespace sdk {
        namespace client {
            enum class EMonsterHunterMaterialsSource_t : std::int32_t {
                Invalid = -0x1,
                PremiumPass = 0x0,
                Tutorial = 0x1,
                HunterRankReward = 0x2,
                HeroAtlasReward = 0x3,
                MaterialTrader = 0x4,
                HolidayReward = 0x5,
                EarlyPremiumPassHolder = 0x6,
                UniversalMaterials = 0x7
            };
        }
    }
}
