/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

namespace shade {
    namespace sdk {
        namespace client {
            enum class ENeutralNPCType : std::int32_t {
                NEUTRAL_INVALID = -0x1,
                NEUTRAL_NPC_WEAK = 0x1,
                NEUTRAL_NPC_NORMAL = 0x2,
                NEUTRAL_NPC_STRONG = 0x3,
                NEUTRAL_SUPER = 0x5,
                NEUTRAL_SINNERS_SACRIFICE = 0x6,
                NEUTRAL_BUG = 0x7,
                NEUTRAL_GARGOYLE = 0x9,
                NEUTRAL_TRASHBUG = 0xa,
                NEUTRAL_WHACK_A_GHOST = 0xb,
                NEUTRAL_VAULT = 0xc
            };
        }
    }
}
