/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

namespace shade {
    namespace sdk {
        namespace client {
            enum class ESurvivorsAttackTargeting : std::int32_t {
                INVALID_TARGET = -0x1,
                CLOSEST_TARGET = 0x0,
                RANDOM_TARGET_IN_RANGE = 0x1,
                STRONGEST_TARGET_IN_RANGE = 0x2,
                RANDOM_TARGET_AT_RANGE = 0x3,
                PLAYER_FACING = 0x4
            };
        }
    }
}
