/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/inv_image_camera_t.hpp"
#include "shade/sdk/client/inv_image_clearcolor_t.hpp"
#include "shade/sdk/client/inv_image_item_t.hpp"
#include "shade/sdk/client/inv_image_light_barn_t.hpp"
#include "shade/sdk/client/inv_image_light_fill_t.hpp"
#include "shade/sdk/client/inv_image_light_sun_t.hpp"
#include "shade/sdk/client/inv_image_map_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0xe8
             * Alignment: 0x8
             * Construct Allowed
             */
            #pragma pack(push, 1)
            struct inv_image_data_t {
                shade::sdk::client::inv_image_map_t map; // 0x0000, 0x10 bytes
                shade::sdk::client::inv_image_item_t item; // 0x0010, 0x20 bytes
                shade::sdk::client::inv_image_camera_t camera; // 0x0030, 0x34 bytes
                shade::sdk::client::inv_image_light_sun_t lightsun; // 0x0064, 0x1c bytes
                shade::sdk::client::inv_image_light_fill_t lightfill; // 0x0080, 0x1c bytes
                shade::sdk::client::inv_image_light_barn_t light0; // 0x009c, 0x20 bytes
                shade::sdk::client::inv_image_light_barn_t light1; // 0x00bc, 0x20 bytes
                shade::sdk::client::inv_image_clearcolor_t clearcolor; // 0x00dc, 0xc bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(inv_image_data_t) == 0xE8, "inv_image_data_t size mismatch");
        }
    }
}
