/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

namespace shade {
    namespace sdk {
        namespace client {
            enum class NET_Messages : std::uint32_t {
                net_NOP = 0x0,
                net_Disconnect_Legacy = 0x1,
                net_SplitScreenUser = 0x3,
                net_Tick = 0x4,
                net_StringCmd = 0x5,
                net_SetConVar = 0x6,
                net_SignonState = 0x7,
                net_SpawnGroup_Load = 0x8,
                net_SpawnGroup_ManifestUpdate = 0x9,
                net_SpawnGroup_SetCreationTick = 0xb,
                net_SpawnGroup_Unload = 0xc,
                net_SpawnGroup_LoadCompleted = 0xd,
                net_DebugOverlay = 0xf
            };
        }
    }
}
