/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>
#include <optional>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/Class_T.hpp"
#include "shade/sdk/client/EPingSubjectSourceContext_t.hpp"
#include "shade/sdk/client/EPingTargetAllegiance_t.hpp"
#include "shade/sdk/client/EPingTristate_t.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x30
             * Alignment: 0x8
             * Construct Allowed
             */
            #pragma pack(push, 1)
            struct PingConditions_t {
                CUtlVector<shade::sdk::client::Class_T> m_vecEntityClasses; // 0x0000, 0x18 bytes
                shade::sdk::client::EPingTargetAllegiance_t m_eAllegiance; // 0x0018, 0x4 bytes
                shade::sdk::client::EPingSubjectSourceContext_t m_eSourceContext; // 0x001c, 0x4 bytes
                shade::sdk::client::EPingTristate_t m_eUltimateReady; // 0x0020, 0x4 bytes
                shade::sdk::client::EPingTristate_t m_eUltimateTrained; // 0x0024, 0x4 bytes
                shade::sdk::client::EPingTristate_t m_eSubjectAlive; // 0x0028, 0x4 bytes
                shade::sdk::client::EPingTristate_t m_eSubjectVisible; // 0x002c, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(PingConditions_t) == 0x30, "PingConditions_t size mismatch");
        }
    }
}
