/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

namespace shade {
    namespace sdk {
        namespace client {
            enum class ScoutState_t : std::int32_t {
                SCOUT_STATE_INIT = -0x1,
                SCOUT_STATE_IDLE = 0x0,
                SCOUT_STATE_AT_BASE = 0x1,
                SCOUT_STATE_MOVING = 0x2,
                SCOUT_STATE_DEAD = 0x3,
                SCOUT_NUM_STATES = 0x4
            };
        }
    }
}
