/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/client/CTakeDamageInfo.hpp"
#include "shade/sdk/client/CTakeDamageResult.hpp"

namespace shade {
    namespace sdk {
        namespace client {
            class C_BaseEntity;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace client {
            /* Class Parameters
             * Size: 0x140
             * Alignment: 0xff
             */
            #pragma pack(push, 1)
            struct SummaryTakeDamageInfo_t {
                std::int32_t nSummarisedCount; // 0x0000, 0x4 bytes
                std::uint8_t pad_0004[0x4]; // 0x0004, 0x4 bytes
                shade::sdk::client::CTakeDamageInfo info; // 0x0008, 0x100 bytes
                shade::sdk::client::CTakeDamageResult result; // 0x0108, 0x30 bytes
                CHandle<shade::sdk::client::C_BaseEntity> hTarget; // 0x0138, 0x4 bytes
                std::uint8_t pad_013c[0x4]; // 0x013c, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(SummaryTakeDamageInfo_t) == 0x140, "SummaryTakeDamageInfo_t size mismatch");
        }
    }
}
