/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

namespace shade {
    namespace sdk {
        namespace animlib {
            struct CNmSyncTrack__Event_t;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace animlib {
            /* Class Parameters
             * Size: 0xb0
             * Alignment: 0x8
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class CNmSyncTrack {
            public:
                CUtlLeanVectorFixedGrowable<shade::sdk::animlib::CNmSyncTrack__Event_t, 10> m_syncEvents; // 0x0000, 0xa8 bytes
                std::int32_t m_nStartEventOffset; // 0x00a8, 0x4 bytes
                std::uint8_t pad_00ac[0x4]; // 0x00ac, 0x4 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CNmSyncTrack) == 0xB0, "CNmSyncTrack size mismatch");
        }
    }
}
