/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

#include "shade/sdk/animlib/CNmEvent.hpp"
#include "shade/sdk/animlib/NmTransitionRule_t.hpp"

namespace shade {
    namespace sdk {
        namespace animlib {
            /* Class Parameters
             * Size: 0x28
             * Alignment: 0x8
             * Has VTable
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class CNmTransitionEvent : public shade::sdk::animlib::CNmEvent {
            public:
                shade::sdk::animlib::NmTransitionRule_t m_rule; // 0x0018, 0x1 bytes
                std::uint8_t pad_0019[0x7]; // 0x0019, 0x7 bytes
                CGlobalSymbol m_ID; // 0x0020, 0x8 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CNmTransitionEvent) == 0x28, "CNmTransitionEvent size mismatch");
        }
    }
}
