/*
 * This file was generated by the Shade SDK generator and does not guarantee 100% accuracy of the information.
 * This file may be used for educational purposes only.
 */

/*
 * Link to the SDK generator: https://github.com/arisuwine/shadegenerator
 * Link to the SDK generator developer: https://github.com/arisuwine
 */

#pragma once
#include <cstdint>
#include <memory>
#include <utility>

#include "shade/sdk/types.hpp"

namespace shade {
    namespace sdk {
        namespace worldrenderer {
            struct InfoForResourceTypeVMapResourceData_t;
        }
    }
}

namespace shade {
    namespace sdk {
        namespace toolscene {
            /* Class Parameters
             * Size: 0xe8
             * Alignment: 0x8
             * Construct Allowed
             */
            #pragma pack(push, 1)
            class CLightRigVMap {
            public:
                CResourceNameTyped<CWeakHandle<shade::sdk::worldrenderer::InfoForResourceTypeVMapResourceData_t>> m_MapName; // 0x0000, 0xe0 bytes
                bool m_bRender3DSkybox; // 0x00e0, 0x1 bytes
                bool m_bParticlesTraceAgainstMap; // 0x00e1, 0x1 bytes
                std::uint8_t pad_00e2[0x6]; // 0x00e2, 0x6 bytes
            };
            #pragma pack(pop)

            // No unique data map fields

            static_assert(sizeof(CLightRigVMap) == 0xE8, "CLightRigVMap size mismatch");
        }
    }
}
